// Package bullets provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package bullets

// Defines values for BulletSection.
const (
	Custom          BulletSection = "custom"
	Education       BulletSection = "education"
	Employment      BulletSection = "employment"
	ExtraCurricular BulletSection = "extra_curricular"
	Projects        BulletSection = "projects"
)

// Valid indicates whether the value is a known member of the BulletSection enum.
func (e BulletSection) Valid() bool {
	switch e {
	case Custom:
		return true
	case Education:
		return true
	case Employment:
		return true
	case ExtraCurricular:
		return true
	case Projects:
		return true
	default:
		return false
	}
}

// Defines values for BulletsSuggestRequestLocale.
const (
	BulletsSuggestRequestLocaleDa BulletsSuggestRequestLocale = "da"
	BulletsSuggestRequestLocaleDe BulletsSuggestRequestLocale = "de"
	BulletsSuggestRequestLocaleEn BulletsSuggestRequestLocale = "en"
	BulletsSuggestRequestLocaleEs BulletsSuggestRequestLocale = "es"
	BulletsSuggestRequestLocaleEt BulletsSuggestRequestLocale = "et"
	BulletsSuggestRequestLocaleFi BulletsSuggestRequestLocale = "fi"
	BulletsSuggestRequestLocaleFr BulletsSuggestRequestLocale = "fr"
	BulletsSuggestRequestLocaleIs BulletsSuggestRequestLocale = "is"
	BulletsSuggestRequestLocaleIt BulletsSuggestRequestLocale = "it"
	BulletsSuggestRequestLocaleNl BulletsSuggestRequestLocale = "nl"
	BulletsSuggestRequestLocaleNo BulletsSuggestRequestLocale = "no"
	BulletsSuggestRequestLocalePl BulletsSuggestRequestLocale = "pl"
	BulletsSuggestRequestLocalePt BulletsSuggestRequestLocale = "pt"
	BulletsSuggestRequestLocaleSv BulletsSuggestRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the BulletsSuggestRequestLocale enum.
func (e BulletsSuggestRequestLocale) Valid() bool {
	switch e {
	case BulletsSuggestRequestLocaleDa:
		return true
	case BulletsSuggestRequestLocaleDe:
		return true
	case BulletsSuggestRequestLocaleEn:
		return true
	case BulletsSuggestRequestLocaleEs:
		return true
	case BulletsSuggestRequestLocaleEt:
		return true
	case BulletsSuggestRequestLocaleFi:
		return true
	case BulletsSuggestRequestLocaleFr:
		return true
	case BulletsSuggestRequestLocaleIs:
		return true
	case BulletsSuggestRequestLocaleIt:
		return true
	case BulletsSuggestRequestLocaleNl:
		return true
	case BulletsSuggestRequestLocaleNo:
		return true
	case BulletsSuggestRequestLocalePl:
		return true
	case BulletsSuggestRequestLocalePt:
		return true
	case BulletsSuggestRequestLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for BulletsWorkerRequestLocale.
const (
	BulletsWorkerRequestLocaleDa BulletsWorkerRequestLocale = "da"
	BulletsWorkerRequestLocaleDe BulletsWorkerRequestLocale = "de"
	BulletsWorkerRequestLocaleEn BulletsWorkerRequestLocale = "en"
	BulletsWorkerRequestLocaleEs BulletsWorkerRequestLocale = "es"
	BulletsWorkerRequestLocaleEt BulletsWorkerRequestLocale = "et"
	BulletsWorkerRequestLocaleFi BulletsWorkerRequestLocale = "fi"
	BulletsWorkerRequestLocaleFr BulletsWorkerRequestLocale = "fr"
	BulletsWorkerRequestLocaleIs BulletsWorkerRequestLocale = "is"
	BulletsWorkerRequestLocaleIt BulletsWorkerRequestLocale = "it"
	BulletsWorkerRequestLocaleNl BulletsWorkerRequestLocale = "nl"
	BulletsWorkerRequestLocaleNo BulletsWorkerRequestLocale = "no"
	BulletsWorkerRequestLocalePl BulletsWorkerRequestLocale = "pl"
	BulletsWorkerRequestLocalePt BulletsWorkerRequestLocale = "pt"
	BulletsWorkerRequestLocaleSv BulletsWorkerRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the BulletsWorkerRequestLocale enum.
func (e BulletsWorkerRequestLocale) Valid() bool {
	switch e {
	case BulletsWorkerRequestLocaleDa:
		return true
	case BulletsWorkerRequestLocaleDe:
		return true
	case BulletsWorkerRequestLocaleEn:
		return true
	case BulletsWorkerRequestLocaleEs:
		return true
	case BulletsWorkerRequestLocaleEt:
		return true
	case BulletsWorkerRequestLocaleFi:
		return true
	case BulletsWorkerRequestLocaleFr:
		return true
	case BulletsWorkerRequestLocaleIs:
		return true
	case BulletsWorkerRequestLocaleIt:
		return true
	case BulletsWorkerRequestLocaleNl:
		return true
	case BulletsWorkerRequestLocaleNo:
		return true
	case BulletsWorkerRequestLocalePl:
		return true
	case BulletsWorkerRequestLocalePt:
		return true
	case BulletsWorkerRequestLocaleSv:
		return true
	default:
		return false
	}
}

// BulletSection Which resume section the chip strip is rendering under. Drives:
// - which `<section>/` subdirectory of the template bank the worker reads
// - which item-id field on the request the backend honors
// - which auto-fill placeholders the worker substitutes
type BulletSection string

// BulletsSuggestRequest Public envelope: `POST /api/bullets/suggest` body (web → backend).
// Backend looks up the resume, walks to the section item the matching
// `*ItemId` field points at, extracts context, then forwards a
// `BulletsWorkerRequest` to ai-core. Exactly one of the five item-id
// fields must be present and it must match `section`.
type BulletsSuggestRequest struct {
	// CustomItemId Required when `section = custom`.
	CustomItemId *string `json:"customItemId,omitempty"`

	// EducationItemId Required when `section = education`.
	EducationItemId *string `json:"educationItemId,omitempty"`

	// EmploymentItemId Required when `section = employment`. Id of the employment item
	// the chip strip will render under.
	EmploymentItemId *string `json:"employmentItemId,omitempty"`

	// Exclude Raw template strings currently visible on the chip strip — the
	// worker never re-suggests these even if they outrank everything
	// else. Protects the "remove one chip, refill one chip, others
	// stay put" UX.
	Exclude *[]string `json:"exclude,omitempty"`

	// ExtraCurricularItemId Required when `section = extra_curricular`.
	ExtraCurricularItemId *string `json:"extraCurricularItemId,omitempty"`

	// Limit How many fresh templates to return. First paint sends 5; chip
	// refill sends 1.
	Limit int `json:"limit"`

	// Locale Drives which `<bucket>_<locale>.json` cell the worker loads. No
	// English fallback — if the locale × section cell is empty, the
	// response returns zero templates and the frontend renders nothing.
	Locale BulletsSuggestRequestLocale `json:"locale"`

	// ProjectItemId Required when `section = projects`.
	ProjectItemId *string `json:"projectItemId,omitempty"`

	// ResumeId Resume id the bullets belong to.
	ResumeId string `json:"resumeId"`

	// Section Which resume section the chip strip is rendering under. Drives:
	// - which `<section>/` subdirectory of the template bank the worker reads
	// - which item-id field on the request the backend honors
	// - which auto-fill placeholders the worker substitutes
	Section BulletSection `json:"section"`
}

// BulletsSuggestRequestLocale Drives which `<bucket>_<locale>.json` cell the worker loads. No
// English fallback — if the locale × section cell is empty, the
// response returns zero templates and the frontend renders nothing.
type BulletsSuggestRequestLocale string

// BulletsSuggestResponse Response from ai-core for `POST /v1/bullets/suggest`. Backend
// forwards this verbatim to the frontend on `POST /api/bullets/suggest`.
//
// Two parallel arrays of equal length:
//   - `bullets` — templates after auto-placeholder substitution. User-fill
//     placeholders ([METRIC], [X%], etc.) remain in the string and the
//     frontend renders them as editable spans.
//   - `rawTemplates` — the original template strings before substitution.
//     The frontend uses these as stable identifiers for the `exclude`
//     list (substituted strings change as resume context changes).
type BulletsSuggestResponse struct {
	// Bullets Length 0..limit. Empty array means the locale × section cell has
	// no templates yet — frontend renders nothing (no English fallback).
	Bullets []string `json:"bullets"`

	// RawTemplates Same length as `bullets`. Indexed pair: `rawTemplates[i]` is the
	// unsubstituted source of `bullets[i]`.
	RawTemplates []string `json:"rawTemplates"`
}

// BulletsWorkerRequest Backend → ai-core wire body for `POST /v1/bullets/suggest`. Backend
// has the DB and the user session, so it pre-extracts every field the
// worker needs to fill auto-placeholders. ai-core stays stateless and
// the worker never queries Postgres.
//
// The per-section context fields below are populated only when relevant
// to `section`. The worker reads only the ones its template references
// — sending an unused field is a no-op, not an error.
type BulletsWorkerRequest struct {
	// Company Fills `[COMPANY]`. Sourced from the employment item's `company`.
	// Empty for non-employment sections.
	Company *string `json:"company,omitempty"`

	// EducationField Fills `[FIELD]`. Sourced from the education item's `field`.
	// Empty for non-education sections.
	EducationField *string `json:"educationField,omitempty"`

	// Exclude Raw template strings to suppress. Forwarded verbatim.
	Exclude *[]string `json:"exclude,omitempty"`

	// ExistingSkills Up to ~5 skill names from the resume. Joined locale-aware by the
	// worker to fill the `[STACK]` placeholder. Used by every section
	// that references `[STACK]` (employment, projects, custom).
	ExistingSkills *[]string                  `json:"existingSkills,omitempty"`
	Limit          int                        `json:"limit"`
	Locale         BulletsWorkerRequestLocale `json:"locale"`

	// Organization Fills `[ORG]`. Sourced from the extra-curricular item's
	// `organization`. Empty for other sections.
	Organization *string `json:"organization,omitempty"`

	// ProjectName Fills `[PROJECT_NAME]`. Sourced from the project item's `title`.
	// Empty for non-project sections.
	ProjectName *string `json:"projectName,omitempty"`

	// Role Fills `[ROLE]`. Source per section:
	// - employment: employment item's `position`
	// - extra_curricular: extra-curricular item's `role`
	// - other sections: empty string
	Role *string `json:"role,omitempty"`

	// School Fills `[SCHOOL]`. Sourced from the education item's `institution`.
	// Empty for non-education sections.
	School *string `json:"school,omitempty"`

	// Section Which resume section the chip strip is rendering under. Drives:
	// - which `<section>/` subdirectory of the template bank the worker reads
	// - which item-id field on the request the backend honors
	// - which auto-fill placeholders the worker substitutes
	Section BulletSection `json:"section"`
}

// BulletsWorkerRequestLocale defines model for BulletsWorkerRequest.Locale.
type BulletsWorkerRequestLocale string
