// Package coverletter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package coverletter

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CoverLetterLocale.
const (
	Da CoverLetterLocale = "da"
	De CoverLetterLocale = "de"
	En CoverLetterLocale = "en"
	Es CoverLetterLocale = "es"
	Et CoverLetterLocale = "et"
	Fi CoverLetterLocale = "fi"
	Fr CoverLetterLocale = "fr"
	Is CoverLetterLocale = "is"
	It CoverLetterLocale = "it"
	Nl CoverLetterLocale = "nl"
	No CoverLetterLocale = "no"
	Pl CoverLetterLocale = "pl"
	Pt CoverLetterLocale = "pt"
	Sv CoverLetterLocale = "sv"
)

// Valid indicates whether the value is a known member of the CoverLetterLocale enum.
func (e CoverLetterLocale) Valid() bool {
	switch e {
	case Da:
		return true
	case De:
		return true
	case En:
		return true
	case Es:
		return true
	case Et:
		return true
	case Fi:
		return true
	case Fr:
		return true
	case Is:
		return true
	case It:
		return true
	case Nl:
		return true
	case No:
		return true
	case Pl:
		return true
	case Pt:
		return true
	case Sv:
		return true
	default:
		return false
	}
}

// CoverLetter defines model for CoverLetter.
type CoverLetter struct {
	Completeness *int                `json:"completeness,omitempty"`
	Content      CoverLetterContent  `json:"content"`
	CreatedAt    *time.Time          `json:"createdAt,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Locale       CoverLetterLocale   `json:"locale"`

	// Styling Cover letter visual settings. All fields optional — template defaults
	// apply when omitted.
	Styling *CoverLetterStyling `json:"styling,omitempty"`

	// TemplateId Slug from the cover-letter template catalog. Defaults to `emerald`
	// when omitted.
	TemplateId *string    `json:"templateId,omitempty"`
	Title      string     `json:"title"`
	UpdatedAt  *time.Time `json:"updatedAt,omitempty"`
}

// CoverLetterLocale defines model for CoverLetter.Locale.
type CoverLetterLocale string

// CoverLetterContent defines model for CoverLetterContent.
type CoverLetterContent struct {
	EmployerDetails CoverLetterEmployerDetails `json:"employerDetails"`

	// LetterContent Body of the letter. HTML allowed (paragraphs and lists).
	LetterContent   string                     `json:"letterContent"`
	PersonalDetails CoverLetterPersonalDetails `json:"personalDetails"`
}

// CoverLetterEmployerDetails defines model for CoverLetterEmployerDetails.
type CoverLetterEmployerDetails struct {
	CompanyName       *string `json:"companyName,omitempty"`
	HiringManagerName *string `json:"hiringManagerName,omitempty"`
}

// CoverLetterPersonalDetails defines model for CoverLetterPersonalDetails.
type CoverLetterPersonalDetails struct {
	Address  *string              `json:"address,omitempty"`
	Email    *openapi_types.Email `json:"email,omitempty"`
	FullName string               `json:"fullName"`
	JobTitle *string              `json:"jobTitle,omitempty"`
	Phone    *string              `json:"phone,omitempty"`
}

// CoverLetterStyling Cover letter visual settings. All fields optional — template defaults
// apply when omitted.
type CoverLetterStyling struct {
	Color      *string  `json:"color,omitempty"`
	Font       *string  `json:"font,omitempty"`
	FontSize   *int     `json:"fontSize,omitempty"`
	LineHeight *float32 `json:"lineHeight,omitempty"`
	Margin     *float32 `json:"margin,omitempty"`
}
