// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentImproveSource

package com.laddro.schemas.content

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Which path produced this response.
 * - `no_change_needed` — input scored >= 85, no LLM call, no rewrite.
 * - `too_short` — input under 5 tokens, refused. Improve and write-for-me
 *   are conceptually different; we don't silently switch lanes.
 * - `cache` — a `crowdsourceImprovements` candidate matched the input
 *   fingerprint above the Jaccard threshold; that candidate is returned.
 *   Zero LLM cost.
 * - `gemini` — input had fixable weaknesses, cache miss, Gemini Flash 2.5
 *   produced a rewrite that passed BOTH the scorer gate (new score >
 *   old score) AND the verifier gate (no fabricated numbers).
 * - `rejected_scorer` — Gemini's rewrite did not improve the score.
 *   Returned with `text` omitted; frontend leaves the user's draft.
 * - `rejected_verifier` — Gemini's rewrite contained a number,
 *   percentage, or quantity not in the original. Hard reject.
 */
@Serializable
enum class ContentImproveSource {
    @SerialName("no_change_needed") NO_CHANGE_NEEDED,
    @SerialName("too_short") TOO_SHORT,
    @SerialName("cache") CACHE,
    @SerialName("gemini") GEMINI,
    @SerialName("rejected_scorer") REJECTED_SCORER,
    @SerialName("rejected_verifier") REJECTED_VERIFIER,
}
