// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentImproveRequest

package com.laddro.schemas.content

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request body for `POST /v1/content/improve` on laddro-ai-core (and the
 * matching `POST /api/content/improve` on laddro-backend, which forwards
 * the same envelope after loading the resume + crowdsource slice).
 *
 * The contract is intentionally narrow: backend has the DB and the user
 * session, so it knows the role / company / other bullets / top skills
 * of the item the user is editing. Shipping them directly keeps the
 * ai-core surface stateless and the LLM brief honest — every field here
 * lands in the prompt, nothing else does. The full resume is never
 * sent to ai-core for improve (it would just inflate the request and
 * risk Gemini drifting into unrelated sections).
 */
@Serializable
data class ContentImproveRequest(
    /**
     * The current bullet text the user wants to improve. Passed verbatim
     * to the local scorer and (if the input gate passes) into the Gemini
     * prompt as `Original:`.
     */
    val text: String,
    /**
     * Position title from the employment item the bullet belongs to.
     * E.g. "Senior Backend Engineer". Used in the prompt to anchor the
     * rewrite ("for {role} at {company}") and as a signal to the
     * seniority detector when bucketId is absent.
     */
    val role: String,
    /**
     * Employer name from the employment item. Used in the prompt for
     * anchoring; never echoed into the rewrite unless the original text
     * already mentions it.
     */
    val company: String,
    /**
     * Drives prompt language for Gemini and which slice of
     * `improve_selections` is consulted for the cache hit. No English
     * fallback — if the user's bullet is German, the rewrite is German.
     */
    val locale: ContentImproveRequestLocale,
    /**
     * Up to 3 other description bullets from the same employment item,
     * excluding the one being improved. Used as a non-repetition signal
     * in the prompt so Gemini doesn't propose a rewrite that duplicates
     * another bullet on the same role. Backend caps at 3 — sending more
     * inflates the brief without changing model behaviour.
     */
    val otherBullets: List<String>? = null,
    /**
     * Up to 5 skill names from the candidate's resume. Used to anchor
     * Gemini's stack choice — "preserve {existingSkills}; don't swap for
     * adjacent tech." Without this anchor the model will happily swap
     * Postgres for MySQL or React for Vue. Backend caps at 5.
     */
    val existingSkills: List<String>? = null,
    /**
     * Cached bucket id from a previous skills-suggest response on the
     * same resume. When present, ai-core skips classifying. When absent,
     * ai-core classifies the bullet via the same nearest-centroid pass
     * and returns the chosen bucket in `bucketId` of the response.
     */
    val bucketId: String? = null,
    /**
     * Top accepted improvement candidates for this
     * `(bucketId, weaknessPattern, locale)` slice, ranked by
     * `accepts - rejects`. Backend reads `improve_selections` and ships
     * the top ~10 per slice. ai-core checks if any candidate's
     * `inputPatternHash` matches the current input's shingled fingerprint
     * (k=3, MinHash, similarity >= 0.8); on hit it returns the candidate
     * output with `source: cache` and zero LLM cost.
     */
    val crowdsourceImprovements: List<CrowdsourcedImprovement>? = null,
)

/**
 * Drives prompt language for Gemini and which slice of
 * `improve_selections` is consulted for the cache hit. No English
 * fallback — if the user's bullet is German, the rewrite is German.
 */
@Serializable
enum class ContentImproveRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
