// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentScoreRequest

package com.laddro.schemas.content

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Lightweight request for the local scorer alone — used by the frontend
 * to decide whether to render the ✨ button on a bullet (debounce ~800ms).
 * Same scorer as the improve flow, exposed as its own endpoint so the
 * button visibility check doesn't pay for the brief assembly.
 */
@Serializable
data class ContentScoreRequest(
    val text: String,
    val locale: ContentScoreRequestLocale,
)

@Serializable
enum class ContentScoreRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
