// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentImproveResponse

package com.laddro.schemas.content

import kotlinx.serialization.Serializable

/**
 * Result of a `POST /v1/content/improve` call. `text` is omitted on the
 * no-change-needed / rejected paths so the frontend can render the
 * right state without a sentinel string. `source` always reports which
 * path produced the response, for observability.
 */
@Serializable
data class ContentImproveResponse(
    /**
     * The rewritten bullet. Present only when `source` is `gemini` or
     * `cache`. Omitted (null) on `no_change_needed`, `rejected_scorer`,
     * `rejected_verifier`, and `too_short`.
     */
    val text: String? = null,
    val source: ContentImproveSource,
    /**
     * Bucket id ai-core used — either passed in by the caller (verbatim)
     * or classified locally when the request omitted it. Backend
     * persists this on the content_improvements row.
     */
    val bucketId: String? = null,
    /**
     * What the local scorer flagged on the input — surfaced even when
     * the LLM call is skipped so the frontend can show a "looks good"
     * or "too short to improve" message with detail.
     */
    val weaknesses: List<ContentWeakness>,
    /**
     * Composite 0–100 score the local scorer assigned to the INPUT.
     * Useful for the visibility gate on the ✨ button (frontend hides
     * the button when score >= 85).
     */
    val score: Int? = null,
    val usage: ContentGenerationUsage,
)
