// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentGenerationUsage

package com.laddro.schemas.content

import kotlinx.serialization.Serializable

/**
 * Per-call usage block. On `cache` / `no_change_needed` / `too_short`,
 * token counts are zero and `model` is the empty string. On the Gemini
 * path, counts include BOTH the rewrite call and the verifier call so
 * downstream cost accounting is honest.
 */
@Serializable
data class ContentGenerationUsage(
    val promptTokens: Int? = 0,
    val outputTokens: Int? = 0,
    val model: String,
)
