// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentWeakness

package com.laddro.schemas.content

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Classes of weakness the local scorer detects. All detected without
 * regex or keyword lists — `weak_verb` / `vague_filler` use cosine
 * against pre-computed centroids; `no_metric` / `first_person` /
 * `no_outcome` use GLiNER entity extraction; `too_short` / `too_long`
 * are structural token counts (not extraction).
 */
@Serializable
enum class ContentWeakness {
    @SerialName("weak_verb") WEAK_VERB,
    @SerialName("no_metric") NO_METRIC,
    @SerialName("first_person") FIRST_PERSON,
    @SerialName("vague_filler") VAGUE_FILLER,
    @SerialName("no_outcome") NO_OUTCOME,
    @SerialName("too_short") TOO_SHORT,
    @SerialName("too_long") TOO_LONG,
}
