// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.ContentScoreResponse

package com.laddro.schemas.content

import kotlinx.serialization.Serializable

@Serializable
data class ContentScoreResponse(
    val score: Int,
    val weaknesses: List<ContentWeakness>,
)
