// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: content/content.v1.yaml -> components.schemas.CrowdsourcedImprovement

package com.laddro.schemas.content

import kotlinx.serialization.Serializable

@Serializable
data class CrowdsourcedImprovement(
    /**
     * MinHash fingerprint of the original input text (k=3 shingles).
     * ai-core compares the current input's fingerprint against this and
     * promotes a cache hit when Jaccard estimate >= 0.8.
     */
    val inputPatternHash: String,
    /**
     * The accepted rewrite to serve on a hit.
     */
    val outputText: String,
    val accepts: Int,
    val rejects: Int,
)
