// Package tailor provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tailor

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BulletTargetScope.
const (
	Bullet BulletTargetScope = "bullet"
)

// Valid indicates whether the value is a known member of the BulletTargetScope enum.
func (e BulletTargetScope) Valid() bool {
	switch e {
	case Bullet:
		return true
	default:
		return false
	}
}

// Defines values for FillRequestLocale.
const (
	FillRequestLocaleCs FillRequestLocale = "cs"
	FillRequestLocaleDa FillRequestLocale = "da"
	FillRequestLocaleDe FillRequestLocale = "de"
	FillRequestLocaleEn FillRequestLocale = "en"
	FillRequestLocaleEs FillRequestLocale = "es"
	FillRequestLocaleEt FillRequestLocale = "et"
	FillRequestLocaleFi FillRequestLocale = "fi"
	FillRequestLocaleFr FillRequestLocale = "fr"
	FillRequestLocaleHu FillRequestLocale = "hu"
	FillRequestLocaleIs FillRequestLocale = "is"
	FillRequestLocaleIt FillRequestLocale = "it"
	FillRequestLocaleLt FillRequestLocale = "lt"
	FillRequestLocaleLv FillRequestLocale = "lv"
	FillRequestLocaleNl FillRequestLocale = "nl"
	FillRequestLocaleNo FillRequestLocale = "no"
	FillRequestLocalePl FillRequestLocale = "pl"
	FillRequestLocalePt FillRequestLocale = "pt"
	FillRequestLocaleRo FillRequestLocale = "ro"
	FillRequestLocaleSk FillRequestLocale = "sk"
	FillRequestLocaleSv FillRequestLocale = "sv"
	FillRequestLocaleUk FillRequestLocale = "uk"
)

// Valid indicates whether the value is a known member of the FillRequestLocale enum.
func (e FillRequestLocale) Valid() bool {
	switch e {
	case FillRequestLocaleCs:
		return true
	case FillRequestLocaleDa:
		return true
	case FillRequestLocaleDe:
		return true
	case FillRequestLocaleEn:
		return true
	case FillRequestLocaleEs:
		return true
	case FillRequestLocaleEt:
		return true
	case FillRequestLocaleFi:
		return true
	case FillRequestLocaleFr:
		return true
	case FillRequestLocaleHu:
		return true
	case FillRequestLocaleIs:
		return true
	case FillRequestLocaleIt:
		return true
	case FillRequestLocaleLt:
		return true
	case FillRequestLocaleLv:
		return true
	case FillRequestLocaleNl:
		return true
	case FillRequestLocaleNo:
		return true
	case FillRequestLocalePl:
		return true
	case FillRequestLocalePt:
		return true
	case FillRequestLocaleRo:
		return true
	case FillRequestLocaleSk:
		return true
	case FillRequestLocaleSv:
		return true
	case FillRequestLocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for JobDescriptionLocale.
const (
	JobDescriptionLocaleCs JobDescriptionLocale = "cs"
	JobDescriptionLocaleDa JobDescriptionLocale = "da"
	JobDescriptionLocaleDe JobDescriptionLocale = "de"
	JobDescriptionLocaleEn JobDescriptionLocale = "en"
	JobDescriptionLocaleEs JobDescriptionLocale = "es"
	JobDescriptionLocaleEt JobDescriptionLocale = "et"
	JobDescriptionLocaleFi JobDescriptionLocale = "fi"
	JobDescriptionLocaleFr JobDescriptionLocale = "fr"
	JobDescriptionLocaleHu JobDescriptionLocale = "hu"
	JobDescriptionLocaleIs JobDescriptionLocale = "is"
	JobDescriptionLocaleIt JobDescriptionLocale = "it"
	JobDescriptionLocaleLt JobDescriptionLocale = "lt"
	JobDescriptionLocaleLv JobDescriptionLocale = "lv"
	JobDescriptionLocaleNl JobDescriptionLocale = "nl"
	JobDescriptionLocaleNo JobDescriptionLocale = "no"
	JobDescriptionLocalePl JobDescriptionLocale = "pl"
	JobDescriptionLocalePt JobDescriptionLocale = "pt"
	JobDescriptionLocaleRo JobDescriptionLocale = "ro"
	JobDescriptionLocaleSk JobDescriptionLocale = "sk"
	JobDescriptionLocaleSv JobDescriptionLocale = "sv"
	JobDescriptionLocaleUk JobDescriptionLocale = "uk"
)

// Valid indicates whether the value is a known member of the JobDescriptionLocale enum.
func (e JobDescriptionLocale) Valid() bool {
	switch e {
	case JobDescriptionLocaleCs:
		return true
	case JobDescriptionLocaleDa:
		return true
	case JobDescriptionLocaleDe:
		return true
	case JobDescriptionLocaleEn:
		return true
	case JobDescriptionLocaleEs:
		return true
	case JobDescriptionLocaleEt:
		return true
	case JobDescriptionLocaleFi:
		return true
	case JobDescriptionLocaleFr:
		return true
	case JobDescriptionLocaleHu:
		return true
	case JobDescriptionLocaleIs:
		return true
	case JobDescriptionLocaleIt:
		return true
	case JobDescriptionLocaleLt:
		return true
	case JobDescriptionLocaleLv:
		return true
	case JobDescriptionLocaleNl:
		return true
	case JobDescriptionLocaleNo:
		return true
	case JobDescriptionLocalePl:
		return true
	case JobDescriptionLocalePt:
		return true
	case JobDescriptionLocaleRo:
		return true
	case JobDescriptionLocaleSk:
		return true
	case JobDescriptionLocaleSv:
		return true
	case JobDescriptionLocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for NoFitReasonPrimary.
const (
	IndustryMismatch     NoFitReasonPrimary = "industry_mismatch"
	InsufficientEvidence NoFitReasonPrimary = "insufficient_evidence"
	SeniorityGap         NoFitReasonPrimary = "seniority_gap"
	SkillsGap            NoFitReasonPrimary = "skills_gap"
)

// Valid indicates whether the value is a known member of the NoFitReasonPrimary enum.
func (e NoFitReasonPrimary) Valid() bool {
	switch e {
	case IndustryMismatch:
		return true
	case InsufficientEvidence:
		return true
	case SeniorityGap:
		return true
	case SkillsGap:
		return true
	default:
		return false
	}
}

// Defines values for RequirementCategory.
const (
	RequirementCategoryExperience     RequirementCategory = "experience"
	RequirementCategoryQualification  RequirementCategory = "qualification"
	RequirementCategoryResponsibility RequirementCategory = "responsibility"
	RequirementCategorySkill          RequirementCategory = "skill"
	RequirementCategorySoft           RequirementCategory = "soft"
)

// Valid indicates whether the value is a known member of the RequirementCategory enum.
func (e RequirementCategory) Valid() bool {
	switch e {
	case RequirementCategoryExperience:
		return true
	case RequirementCategoryQualification:
		return true
	case RequirementCategoryResponsibility:
		return true
	case RequirementCategorySkill:
		return true
	case RequirementCategorySoft:
		return true
	default:
		return false
	}
}

// Defines values for SeniorityLevel.
const (
	Entry   SeniorityLevel = "entry"
	Lead    SeniorityLevel = "lead"
	Mid     SeniorityLevel = "mid"
	Senior  SeniorityLevel = "senior"
	Unknown SeniorityLevel = "unknown"
)

// Valid indicates whether the value is a known member of the SeniorityLevel enum.
func (e SeniorityLevel) Valid() bool {
	switch e {
	case Entry:
		return true
	case Lead:
		return true
	case Mid:
		return true
	case Senior:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SkillTargetScope.
const (
	SkillTargetScopeSkill SkillTargetScope = "skill"
)

// Valid indicates whether the value is a known member of the SkillTargetScope enum.
func (e SkillTargetScope) Valid() bool {
	switch e {
	case SkillTargetScopeSkill:
		return true
	default:
		return false
	}
}

// Defines values for SuggestionKind.
const (
	AddBullet      SuggestionKind = "add_bullet"
	AddSkill       SuggestionKind = "add_skill"
	RewriteBullet  SuggestionKind = "rewrite_bullet"
	RewriteSummary SuggestionKind = "rewrite_summary"
)

// Valid indicates whether the value is a known member of the SuggestionKind enum.
func (e SuggestionKind) Valid() bool {
	switch e {
	case AddBullet:
		return true
	case AddSkill:
		return true
	case RewriteBullet:
		return true
	case RewriteSummary:
		return true
	default:
		return false
	}
}

// Defines values for SummaryTargetScope.
const (
	Summary SummaryTargetScope = "summary"
)

// Valid indicates whether the value is a known member of the SummaryTargetScope enum.
func (e SummaryTargetScope) Valid() bool {
	switch e {
	case Summary:
		return true
	default:
		return false
	}
}

// Defines values for TailorJobCreateRequestApprovalMode.
const (
	AutoApply         TailorJobCreateRequestApprovalMode = "autoApply"
	ReviewSuggestions TailorJobCreateRequestApprovalMode = "reviewSuggestions"
)

// Valid indicates whether the value is a known member of the TailorJobCreateRequestApprovalMode enum.
func (e TailorJobCreateRequestApprovalMode) Valid() bool {
	switch e {
	case AutoApply:
		return true
	case ReviewSuggestions:
		return true
	default:
		return false
	}
}

// Defines values for TailorJobCreateRequestLocale.
const (
	TailorJobCreateRequestLocaleCs TailorJobCreateRequestLocale = "cs"
	TailorJobCreateRequestLocaleDa TailorJobCreateRequestLocale = "da"
	TailorJobCreateRequestLocaleDe TailorJobCreateRequestLocale = "de"
	TailorJobCreateRequestLocaleEn TailorJobCreateRequestLocale = "en"
	TailorJobCreateRequestLocaleEs TailorJobCreateRequestLocale = "es"
	TailorJobCreateRequestLocaleEt TailorJobCreateRequestLocale = "et"
	TailorJobCreateRequestLocaleFi TailorJobCreateRequestLocale = "fi"
	TailorJobCreateRequestLocaleFr TailorJobCreateRequestLocale = "fr"
	TailorJobCreateRequestLocaleHu TailorJobCreateRequestLocale = "hu"
	TailorJobCreateRequestLocaleIs TailorJobCreateRequestLocale = "is"
	TailorJobCreateRequestLocaleIt TailorJobCreateRequestLocale = "it"
	TailorJobCreateRequestLocaleLt TailorJobCreateRequestLocale = "lt"
	TailorJobCreateRequestLocaleLv TailorJobCreateRequestLocale = "lv"
	TailorJobCreateRequestLocaleNl TailorJobCreateRequestLocale = "nl"
	TailorJobCreateRequestLocaleNo TailorJobCreateRequestLocale = "no"
	TailorJobCreateRequestLocalePl TailorJobCreateRequestLocale = "pl"
	TailorJobCreateRequestLocalePt TailorJobCreateRequestLocale = "pt"
	TailorJobCreateRequestLocaleRo TailorJobCreateRequestLocale = "ro"
	TailorJobCreateRequestLocaleSk TailorJobCreateRequestLocale = "sk"
	TailorJobCreateRequestLocaleSv TailorJobCreateRequestLocale = "sv"
	TailorJobCreateRequestLocaleUk TailorJobCreateRequestLocale = "uk"
)

// Valid indicates whether the value is a known member of the TailorJobCreateRequestLocale enum.
func (e TailorJobCreateRequestLocale) Valid() bool {
	switch e {
	case TailorJobCreateRequestLocaleCs:
		return true
	case TailorJobCreateRequestLocaleDa:
		return true
	case TailorJobCreateRequestLocaleDe:
		return true
	case TailorJobCreateRequestLocaleEn:
		return true
	case TailorJobCreateRequestLocaleEs:
		return true
	case TailorJobCreateRequestLocaleEt:
		return true
	case TailorJobCreateRequestLocaleFi:
		return true
	case TailorJobCreateRequestLocaleFr:
		return true
	case TailorJobCreateRequestLocaleHu:
		return true
	case TailorJobCreateRequestLocaleIs:
		return true
	case TailorJobCreateRequestLocaleIt:
		return true
	case TailorJobCreateRequestLocaleLt:
		return true
	case TailorJobCreateRequestLocaleLv:
		return true
	case TailorJobCreateRequestLocaleNl:
		return true
	case TailorJobCreateRequestLocaleNo:
		return true
	case TailorJobCreateRequestLocalePl:
		return true
	case TailorJobCreateRequestLocalePt:
		return true
	case TailorJobCreateRequestLocaleRo:
		return true
	case TailorJobCreateRequestLocaleSk:
		return true
	case TailorJobCreateRequestLocaleSv:
		return true
	case TailorJobCreateRequestLocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for TailorJobEventType.
const (
	TailorCancelled          TailorJobEventType = "tailor.cancelled"
	TailorCompleted          TailorJobEventType = "tailor.completed"
	TailorExtractJdDone      TailorJobEventType = "tailor.extract_jd.done"
	TailorExtractProfileDone TailorJobEventType = "tailor.extract_profile.done"
	TailorFailed             TailorJobEventType = "tailor.failed"
	TailorFillProgress       TailorJobEventType = "tailor.fill.progress"
	TailorMatchDone          TailorJobEventType = "tailor.match.done"
	TailorPretrimDone        TailorJobEventType = "tailor.pretrim.done"
	TailorRecommendDone      TailorJobEventType = "tailor.recommend.done"
	TailorStarted            TailorJobEventType = "tailor.started"
	TailorVerdictDone        TailorJobEventType = "tailor.verdict.done"
)

// Valid indicates whether the value is a known member of the TailorJobEventType enum.
func (e TailorJobEventType) Valid() bool {
	switch e {
	case TailorCancelled:
		return true
	case TailorCompleted:
		return true
	case TailorExtractJdDone:
		return true
	case TailorExtractProfileDone:
		return true
	case TailorFailed:
		return true
	case TailorFillProgress:
		return true
	case TailorMatchDone:
		return true
	case TailorPretrimDone:
		return true
	case TailorRecommendDone:
		return true
	case TailorStarted:
		return true
	case TailorVerdictDone:
		return true
	default:
		return false
	}
}

// Defines values for TailorJobStatus.
const (
	TailorJobStatusCancelled TailorJobStatus = "cancelled"
	TailorJobStatusCompleted TailorJobStatus = "completed"
	TailorJobStatusFailed    TailorJobStatus = "failed"
	TailorJobStatusNoFit     TailorJobStatus = "no_fit"
	TailorJobStatusPending   TailorJobStatus = "pending"
	TailorJobStatusRunning   TailorJobStatus = "running"
)

// Valid indicates whether the value is a known member of the TailorJobStatus enum.
func (e TailorJobStatus) Valid() bool {
	switch e {
	case TailorJobStatusCancelled:
		return true
	case TailorJobStatusCompleted:
		return true
	case TailorJobStatusFailed:
		return true
	case TailorJobStatusNoFit:
		return true
	case TailorJobStatusPending:
		return true
	case TailorJobStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for TailorRequestLocale.
const (
	TailorRequestLocaleCs TailorRequestLocale = "cs"
	TailorRequestLocaleDa TailorRequestLocale = "da"
	TailorRequestLocaleDe TailorRequestLocale = "de"
	TailorRequestLocaleEn TailorRequestLocale = "en"
	TailorRequestLocaleEs TailorRequestLocale = "es"
	TailorRequestLocaleEt TailorRequestLocale = "et"
	TailorRequestLocaleFi TailorRequestLocale = "fi"
	TailorRequestLocaleFr TailorRequestLocale = "fr"
	TailorRequestLocaleHu TailorRequestLocale = "hu"
	TailorRequestLocaleIs TailorRequestLocale = "is"
	TailorRequestLocaleIt TailorRequestLocale = "it"
	TailorRequestLocaleLt TailorRequestLocale = "lt"
	TailorRequestLocaleLv TailorRequestLocale = "lv"
	TailorRequestLocaleNl TailorRequestLocale = "nl"
	TailorRequestLocaleNo TailorRequestLocale = "no"
	TailorRequestLocalePl TailorRequestLocale = "pl"
	TailorRequestLocalePt TailorRequestLocale = "pt"
	TailorRequestLocaleRo TailorRequestLocale = "ro"
	TailorRequestLocaleSk TailorRequestLocale = "sk"
	TailorRequestLocaleSv TailorRequestLocale = "sv"
	TailorRequestLocaleUk TailorRequestLocale = "uk"
)

// Valid indicates whether the value is a known member of the TailorRequestLocale enum.
func (e TailorRequestLocale) Valid() bool {
	switch e {
	case TailorRequestLocaleCs:
		return true
	case TailorRequestLocaleDa:
		return true
	case TailorRequestLocaleDe:
		return true
	case TailorRequestLocaleEn:
		return true
	case TailorRequestLocaleEs:
		return true
	case TailorRequestLocaleEt:
		return true
	case TailorRequestLocaleFi:
		return true
	case TailorRequestLocaleFr:
		return true
	case TailorRequestLocaleHu:
		return true
	case TailorRequestLocaleIs:
		return true
	case TailorRequestLocaleIt:
		return true
	case TailorRequestLocaleLt:
		return true
	case TailorRequestLocaleLv:
		return true
	case TailorRequestLocaleNl:
		return true
	case TailorRequestLocaleNo:
		return true
	case TailorRequestLocalePl:
		return true
	case TailorRequestLocalePt:
		return true
	case TailorRequestLocaleRo:
		return true
	case TailorRequestLocaleSk:
		return true
	case TailorRequestLocaleSv:
		return true
	case TailorRequestLocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for TailorResponseFitVerdict.
const (
	TailorResponseFitVerdictNoFit      TailorResponseFitVerdict = "no_fit"
	TailorResponseFitVerdictPartialFit TailorResponseFitVerdict = "partial_fit"
	TailorResponseFitVerdictStrongFit  TailorResponseFitVerdict = "strong_fit"
	TailorResponseFitVerdictWeakFit    TailorResponseFitVerdict = "weak_fit"
)

// Valid indicates whether the value is a known member of the TailorResponseFitVerdict enum.
func (e TailorResponseFitVerdict) Valid() bool {
	switch e {
	case TailorResponseFitVerdictNoFit:
		return true
	case TailorResponseFitVerdictPartialFit:
		return true
	case TailorResponseFitVerdictStrongFit:
		return true
	case TailorResponseFitVerdictWeakFit:
		return true
	default:
		return false
	}
}

// Defines values for WorkerAnalyzeRequestLocale.
const (
	WorkerAnalyzeRequestLocaleCs WorkerAnalyzeRequestLocale = "cs"
	WorkerAnalyzeRequestLocaleDa WorkerAnalyzeRequestLocale = "da"
	WorkerAnalyzeRequestLocaleDe WorkerAnalyzeRequestLocale = "de"
	WorkerAnalyzeRequestLocaleEn WorkerAnalyzeRequestLocale = "en"
	WorkerAnalyzeRequestLocaleEs WorkerAnalyzeRequestLocale = "es"
	WorkerAnalyzeRequestLocaleEt WorkerAnalyzeRequestLocale = "et"
	WorkerAnalyzeRequestLocaleFi WorkerAnalyzeRequestLocale = "fi"
	WorkerAnalyzeRequestLocaleFr WorkerAnalyzeRequestLocale = "fr"
	WorkerAnalyzeRequestLocaleHu WorkerAnalyzeRequestLocale = "hu"
	WorkerAnalyzeRequestLocaleIs WorkerAnalyzeRequestLocale = "is"
	WorkerAnalyzeRequestLocaleIt WorkerAnalyzeRequestLocale = "it"
	WorkerAnalyzeRequestLocaleLt WorkerAnalyzeRequestLocale = "lt"
	WorkerAnalyzeRequestLocaleLv WorkerAnalyzeRequestLocale = "lv"
	WorkerAnalyzeRequestLocaleNl WorkerAnalyzeRequestLocale = "nl"
	WorkerAnalyzeRequestLocaleNo WorkerAnalyzeRequestLocale = "no"
	WorkerAnalyzeRequestLocalePl WorkerAnalyzeRequestLocale = "pl"
	WorkerAnalyzeRequestLocalePt WorkerAnalyzeRequestLocale = "pt"
	WorkerAnalyzeRequestLocaleRo WorkerAnalyzeRequestLocale = "ro"
	WorkerAnalyzeRequestLocaleSk WorkerAnalyzeRequestLocale = "sk"
	WorkerAnalyzeRequestLocaleSv WorkerAnalyzeRequestLocale = "sv"
	WorkerAnalyzeRequestLocaleUk WorkerAnalyzeRequestLocale = "uk"
)

// Valid indicates whether the value is a known member of the WorkerAnalyzeRequestLocale enum.
func (e WorkerAnalyzeRequestLocale) Valid() bool {
	switch e {
	case WorkerAnalyzeRequestLocaleCs:
		return true
	case WorkerAnalyzeRequestLocaleDa:
		return true
	case WorkerAnalyzeRequestLocaleDe:
		return true
	case WorkerAnalyzeRequestLocaleEn:
		return true
	case WorkerAnalyzeRequestLocaleEs:
		return true
	case WorkerAnalyzeRequestLocaleEt:
		return true
	case WorkerAnalyzeRequestLocaleFi:
		return true
	case WorkerAnalyzeRequestLocaleFr:
		return true
	case WorkerAnalyzeRequestLocaleHu:
		return true
	case WorkerAnalyzeRequestLocaleIs:
		return true
	case WorkerAnalyzeRequestLocaleIt:
		return true
	case WorkerAnalyzeRequestLocaleLt:
		return true
	case WorkerAnalyzeRequestLocaleLv:
		return true
	case WorkerAnalyzeRequestLocaleNl:
		return true
	case WorkerAnalyzeRequestLocaleNo:
		return true
	case WorkerAnalyzeRequestLocalePl:
		return true
	case WorkerAnalyzeRequestLocalePt:
		return true
	case WorkerAnalyzeRequestLocaleRo:
		return true
	case WorkerAnalyzeRequestLocaleSk:
		return true
	case WorkerAnalyzeRequestLocaleSv:
		return true
	case WorkerAnalyzeRequestLocaleUk:
		return true
	default:
		return false
	}
}

// BulletTarget defines model for BulletTarget.
type BulletTarget struct {
	// ItemIndex Index into `resume.sections[section_index].items[]`. The pointed-at
	// section MUST be one whose items have a `description` field:
	// employment, education, certifications, projects,
	// extraCurricularActivities. Skills/Languages/References sections
	// are not valid targets for rewrite_bullet/add_bullet.
	ItemIndex int               `json:"item_index"`
	Scope     BulletTargetScope `json:"scope"`

	// SectionIndex Index into `resume.sections[]`.
	SectionIndex int `json:"section_index"`
}

// BulletTargetScope defines model for BulletTarget.Scope.
type BulletTargetScope string

// CompatibilityScore defines model for CompatibilityScore.
type CompatibilityScore struct {
	Breakdown ScoreBreakdown `json:"breakdown"`

	// Total Live-updating score shown at top of suggestion stack. Recomputed
	// client-side as suggestions are accepted/discarded using the same
	// formula the backend would produce.
	Total int `json:"total"`
}

// Evidence defines model for Evidence.
type Evidence struct {
	Source EvidenceSource `json:"source"`

	// Text The evidence text verbatim from the resume.
	Text string `json:"text"`
}

// EvidenceSource defines model for EvidenceSource.
type EvidenceSource struct {
	// FragmentAnchor Verbatim HTML fragment within the item's description (or skill
	// label / etc) that this evidence quotes. Empty when the evidence
	// is the whole item (e.g. a SkillItem or LanguageItem). Used by
	// auditing and by the writer to know exactly which span to ground
	// against — NEVER for regex or substring rewriting in the writer.
	FragmentAnchor *string `json:"fragment_anchor,omitempty"`

	// ItemIndex Index into that section's `items[]`.
	ItemIndex int `json:"item_index"`

	// SectionIndex Index into `resume.sections[]` this evidence came from.
	SectionIndex int `json:"section_index"`
}

// FillRequest defines model for FillRequest.
type FillRequest struct {
	// Evidence Resume spans the writer is allowed to draw from. The writer
	// refuses (422) when none of the evidence supports the instruction
	// — the no-fabrication gate. Every span carries a structured
	// EvidenceSource so the writer's grounding is auditable: we can
	// always answer "which bullet did this proposed text come from?"
	Evidence   []Evidence        `json:"evidence"`
	Locale     FillRequestLocale `json:"locale"`
	Suggestion Suggestion        `json:"suggestion"`
}

// FillRequestLocale defines model for FillRequest.Locale.
type FillRequestLocale string

// FillResponse defines model for FillResponse.
type FillResponse struct {
	// ProposedText Writer LLM output, in the requested locale. Single bullet, no
	// headers, no preamble. Strictly grounded in `evidence`.
	ProposedText string `json:"proposed_text"`
}

// JobDescription defines model for JobDescription.
type JobDescription struct {
	// Company Company / organization name from NER. Empty string when none
	// detected. Never falls back to text patterns.
	Company *string              `json:"company,omitempty"`
	Locale  JobDescriptionLocale `json:"locale"`

	// RawText The original input, preserved verbatim for source-span lookups.
	RawText      string        `json:"raw_text"`
	Requirements []Requirement `json:"requirements"`
	Seniority    Seniority     `json:"seniority"`
	Skills       []Skill       `json:"skills"`

	// Title Job title as identified by NER, in the JD's source language. Empty
	// string when the model could not identify one. Never falls back to
	// "first non-empty line" or any other structural heuristic.
	Title *string `json:"title,omitempty"`
}

// JobDescriptionLocale defines model for JobDescription.Locale.
type JobDescriptionLocale string

// NoFitReason defines model for NoFitReason.
type NoFitReason struct {
	// Explanation One- or two-sentence reason in the user's locale, drawn from i18n
	// strings — not free-form LLM output. Frontend shows verbatim.
	Explanation string `json:"explanation"`

	// Primary - `skills_gap`            JD's required skills aren't present in the resume
	//                           and no anchors support adding them.
	// - `seniority_gap`         Resume's experience level is materially off from
	//                           what the JD asks for (junior → director, or vice
	//                           versa).
	// - `industry_mismatch`     Resume's occupation graph and the JD's occupation
	//                           don't overlap (nurse vs. backend engineer).
	// - `insufficient_evidence` Resume itself is too thin (empty descriptions,
	//                           no experiences) for any meaningful matching.
	Primary NoFitReasonPrimary `json:"primary"`
}

// NoFitReasonPrimary - `skills_gap`            JD's required skills aren't present in the resume
//
//		and no anchors support adding them.
//	  - `seniority_gap`         Resume's experience level is materially off from
//	    what the JD asks for (junior → director, or vice
//	    versa).
//	  - `industry_mismatch`     Resume's occupation graph and the JD's occupation
//	    don't overlap (nurse vs. backend engineer).
//	  - `insufficient_evidence` Resume itself is too thin (empty descriptions,
//	    no experiences) for any meaningful matching.
type NoFitReasonPrimary string

// Requirement defines model for Requirement.
type Requirement struct {
	// Category Canonical category, classified by the model. This set is
	// deliberately industry-agnostic: a nurse's "patient handover" and
	// an engineer's "deploy to prod" both map to `responsibility`. A
	// welder's "MIG certification" and a lawyer's "bar admission" both
	// map to `qualification`. New categories require a contract bump,
	// not a code patch.
	Category   RequirementCategory `json:"category"`
	Confidence float32             `json:"confidence"`

	// Id Stable identifier scoped to a single TailorResponse. Suggestion
	// records targeting this requirement set `requirement_ref` to
	// this UUID. See Skill.id for the same scoping rule.
	Id          openapi_types.UUID `json:"id"`
	SourceQuote string             `json:"source_quote"`

	// Text The requirement span, verbatim from raw_text.
	Text string `json:"text"`
}

// RequirementCategory Canonical category, classified by the model. This set is
// deliberately industry-agnostic: a nurse's "patient handover" and
// an engineer's "deploy to prod" both map to `responsibility`. A
// welder's "MIG certification" and a lawyer's "bar admission" both
// map to `qualification`. New categories require a contract bump,
// not a code patch.
type RequirementCategory string

// ScoreBreakdown defines model for ScoreBreakdown.
type ScoreBreakdown struct {
	// AdjacentSkills Share covered by semantically-adjacent skills (embedding
	// similarity above the calibrated threshold). NEVER token overlap.
	AdjacentSkills float32 `json:"adjacent_skills"`

	// ExactSkills Share of required skills the resume already covers exactly.
	ExactSkills float32 `json:"exact_skills"`

	// SeniorityFit How well the resume's experience aligns with JobDescription.
	// seniority — calibrated against the eval set, not a hardcoded
	// ladder.
	SeniorityFit float32 `json:"seniority_fit"`
}

// Seniority defines model for Seniority.
type Seniority struct {
	// Confidence Model confidence in the `level` label.
	Confidence float32 `json:"confidence"`

	// Level Seniority bucket, classified by a multilingual model. `unknown`
	// when the model's confidence is below the configured floor — NEVER
	// inferred from years_min via a hardcoded ladder.
	Level SeniorityLevel `json:"level"`

	// YearsMax Maximum years asked for. 0 when none stated.
	YearsMax *int `json:"years_max,omitempty"`

	// YearsMin Minimum years-of-experience asked for, extracted via locale-aware
	// structured extraction. 0 when none stated. Phrasing varies wildly
	// across locales ("3+ years", "Berufserfahrung von 3 Jahren",
	// "5 vuoden kokemus") — extraction is the model's job, not regex.
	YearsMin *int `json:"years_min,omitempty"`
}

// SeniorityLevel Seniority bucket, classified by a multilingual model. `unknown`
// when the model's confidence is below the configured floor — NEVER
// inferred from years_min via a hardcoded ladder.
type SeniorityLevel string

// Skill defines model for Skill.
type Skill struct {
	Confidence float32 `json:"confidence"`

	// EscoId ESCO concept URI when the multilingual ESCO linker matched this
	// skill. Empty when no link — scorer falls back to embedding
	// similarity, never to string matching.
	EscoId *string `json:"esco_id,omitempty"`

	// Id Stable identifier. The worker assigns a UUID at extraction time
	// so the orchestrator and the frontend can reference the same
	// Skill across the request → suggestion → fill round-trip. Suggestion
	// records targeting this skill set `requirement_ref` to this UUID.
	// Different worker calls on the same JD MAY produce different
	// UUIDs — IDs are scoped to a single TailorResponse, not stable
	// across calls.
	Id openapi_types.UUID `json:"id"`

	// Label Skill name as it appeared in the JD, in source language.
	Label string `json:"label"`

	// Normalized Canonical form for deduplication only. Produced by the model's
	// normalizer (lowercase + locale-aware diacritic handling). Not
	// used for semantic matching — that's embeddings' job.
	Normalized string `json:"normalized"`

	// Required Whether the JD treats this skill as required vs nice-to-have.
	// This is a span-classifier output across all 14 locales — NOT a
	// keyword scan over "required"/"must have"/"nice to have". When
	// the classifier's confidence is below the configured floor, the
	// worker omits the skill rather than defaulting to required.
	Required bool `json:"required"`

	// SourceQuote The original span the model attributed this skill to, verbatim
	// from raw_text. The frontend shows it as "from the JD: ...".
	SourceQuote string `json:"source_quote"`
}

// SkillTarget defines model for SkillTarget.
type SkillTarget struct {
	Scope SkillTargetScope `json:"scope"`

	// SectionIndex Index into `resume.sections[]`. The pointed-at section MUST be a
	// SkillsSection (`type: skills`). For `add_skill`, the new SkillItem
	// is appended to `items[]`.
	SectionIndex int `json:"section_index"`
}

// SkillTargetScope defines model for SkillTarget.Scope.
type SkillTargetScope string

// Suggestion defines model for Suggestion.
type Suggestion struct {
	Id openapi_types.UUID `json:"id"`

	// Instruction Locale-aware instruction the writer LLM uses to produce
	// proposed_text. Generated by the recommender, not free-form.
	Instruction string `json:"instruction"`

	// Kind What this suggestion does to the resume. Each kind has a matching
	// `target` shape (see SuggestionTarget) and a per-kind meaning for
	// `original_text`:
	//
	// - `rewrite_bullet`   Replace one `<li>` (or `<p>`) inside
	//                      `resume.sections[target.section_index].items[target.item_index].description`.
	//                      `original_text` is the verbatim HTML fragment
	//                      to find and replace.
	// - `add_bullet`       Append a new `<li>` to the same description.
	//                      `original_text` is the resume "anchor" — the
	//                      existing experience text the new bullet must
	//                      stay faithful to. The anchor is NOT in the
	//                      description being mutated; it's evidence from
	//                      elsewhere in the resume.
	// - `rewrite_summary`  Replace `resume.summary.value` entirely.
	//                      `original_text` is the current summary verbatim.
	// - `add_skill`        Append a SkillItem to a SkillsSection.
	//                      `original_text` is the bullet/text from the
	//                      resume that proves the user already has the
	//                      skill. Refused (no suggestion emitted) when
	//                      no anchor exists — the no-fabrication gate.
	//
	// Suggestions can be applied in any order. Frontend matches the
	// verbatim `original_text` substring on `rewrite_*` to stay robust
	// against user edits between fetch and accept; if not found, the
	// card goes stale-grayed in the UI.
	Kind SuggestionKind `json:"kind"`

	// OriginalText Per-kind semantics — see `kind`. Always shown to the user as proof
	// of grounding ("from your resume: ...").
	OriginalText string `json:"original_text"`

	// ProposedText Empty until the writer LLM is called for this suggestion (lazy
	// per-card via /v1/tailor/fill). Discarded suggestions stay empty
	// and cost zero LLM tokens.
	ProposedText *string `json:"proposed_text,omitempty"`

	// RequirementRef ID of the JobDescription requirement (or skill) this suggestion
	// addresses. Lets the frontend show "this card addresses THIS ask
	// from the JD" with the source_quote highlighted.
	RequirementRef string `json:"requirement_ref"`

	// Target Discriminated union pointing at the exact Resume object a Suggestion
	// mutates. `scope` matches the Suggestion.kind's natural target:
	//   rewrite_bullet, add_bullet  → BulletTarget   (scope=bullet)
	//   rewrite_summary             → SummaryTarget  (scope=summary)
	//   add_skill                   → SkillTarget    (scope=skill)
	Target SuggestionTarget `json:"target"`
}

// SuggestionKind What this suggestion does to the resume. Each kind has a matching
// `target` shape (see SuggestionTarget) and a per-kind meaning for
// `original_text`:
//
//   - `rewrite_bullet`   Replace one `<li>` (or `<p>`) inside
//     `resume.sections[target.section_index].items[target.item_index].description`.
//     `original_text` is the verbatim HTML fragment
//     to find and replace.
//   - `add_bullet`       Append a new `<li>` to the same description.
//     `original_text` is the resume "anchor" — the
//     existing experience text the new bullet must
//     stay faithful to. The anchor is NOT in the
//     description being mutated; it's evidence from
//     elsewhere in the resume.
//   - `rewrite_summary`  Replace `resume.summary.value` entirely.
//     `original_text` is the current summary verbatim.
//   - `add_skill`        Append a SkillItem to a SkillsSection.
//     `original_text` is the bullet/text from the
//     resume that proves the user already has the
//     skill. Refused (no suggestion emitted) when
//     no anchor exists — the no-fabrication gate.
//
// Suggestions can be applied in any order. Frontend matches the
// verbatim `original_text` substring on `rewrite_*` to stay robust
// against user edits between fetch and accept; if not found, the
// card goes stale-grayed in the UI.
type SuggestionKind string

// SuggestionTarget Discriminated union pointing at the exact Resume object a Suggestion
// mutates. `scope` matches the Suggestion.kind's natural target:
//
//	rewrite_bullet, add_bullet  → BulletTarget   (scope=bullet)
//	rewrite_summary             → SummaryTarget  (scope=summary)
//	add_skill                   → SkillTarget    (scope=skill)
type SuggestionTarget struct {
	union json.RawMessage
}

// SummaryTarget Targets `resume.summary.value`. No indices — there's exactly one summary.
type SummaryTarget struct {
	Scope SummaryTargetScope `json:"scope"`
}

// SummaryTargetScope defines model for SummaryTarget.Scope.
type SummaryTargetScope string

// TailorJobCreateRequest Body of POST /ai/tailor-jobs. Replaces the synchronous
// TailorRequest at the backend boundary. Backend creates a job
// row, enqueues a runner, and returns the snapshot in status
// `pending` immediately — the client never waits for ai-core.
type TailorJobCreateRequest struct {
	// ApprovalMode Backwards-compatible passthrough from the existing sync
	// contract. Default is `reviewSuggestions`.
	ApprovalMode *TailorJobCreateRequestApprovalMode `json:"approval_mode,omitempty"`

	// Company Optional. Stored on the sibling resume metadata when the
	// job completes. Not sent to ai-core.
	Company        *string                      `json:"company,omitempty"`
	JobDescription string                       `json:"job_description"`
	Locale         TailorJobCreateRequestLocale `json:"locale"`

	// Position Optional. Stored on the sibling resume metadata.
	Position *string `json:"position,omitempty"`

	// Resume Resume DTO — same shape as TailorRequest.resume. See the
	// cross-file note on resume typing.
	Resume map[string]interface{} `json:"resume"`

	// TailorUuid The frontend's stable draft id (also the URL path param on
	// /tailor-resume/[id]). Used to find the most-recent job on
	// page refresh.
	TailorUuid openapi_types.UUID `json:"tailor_uuid"`
}

// TailorJobCreateRequestApprovalMode Backwards-compatible passthrough from the existing sync
// contract. Default is `reviewSuggestions`.
type TailorJobCreateRequestApprovalMode string

// TailorJobCreateRequestLocale defines model for TailorJobCreateRequest.Locale.
type TailorJobCreateRequestLocale string

// TailorJobEvent Append-only event emitted by ai-core during a tailor run.
// Persisted via UNIQUE (job_id, sequence) so duplicate POSTs (from
// ai-core retries or webhook redelivery) are idempotent no-ops.
// Sequence numbers are monotonic per job; reconnecting SSE clients
// pass the last seen sequence in `Last-Event-ID` and the server
// replays from there.
type TailorJobEvent struct {
	// EventType Closed set of event types ai-core emits. The frontend's progress
	// timeline renders one step per non-`fill.progress` event;
	// `tailor.fill.progress` is the only multi-event step (one event
	// per parallel filler completing a card).
	EventType TailorJobEventType `json:"event_type"`

	// JobId The TailorJob this event belongs to.
	JobId openapi_types.UUID `json:"job_id"`

	// OccurredAt ai-core's wall-clock at emit time. The backend also stamps
	// its own `ingested_at` for lag observability.
	OccurredAt time.Time `json:"occurred_at"`

	// Payload Step-specific payload. Shapes by event_type:
	//
	// - tailor.started
	//     { jd_length_chars: int, resume_version: string,
	//       locale: string }
	// - tailor.pretrim.done
	//     { trimmed: bool, before_chars: int, after_chars: int }
	// - tailor.extract_jd.done
	//     { archetype: string, title: string,
	//       required_skill_count: int, nice_count: int }
	// - tailor.extract_profile.done
	//     { archetype: string, years_experience: int,
	//       primary_stack_count: int, secondary_stack_count: int }
	// - tailor.match.done
	//     { matched_required: int, missing_required: int,
	//       hidden_skills_count: int }
	// - tailor.recommend.done
	//     { card_count: int,
	//       by_kind: { summary: int, skill: int, bullet: int } }
	// - tailor.fill.progress
	//     { card_id: string, kind: string, success: bool,
	//       error?: string }
	// - tailor.verdict.done
	//     { verdict: string, score: int, reason?: string }
	// - tailor.completed
	//     { result_summary: object, total_llm_calls: int,
	//       total_tokens: int, cost_usd: number,
	//       duration_ms: int }
	// - tailor.failed
	//     { failed_at_step: string, error_class: string,
	//       error_message: string, retryable: bool }
	// - tailor.cancelled
	//     { cancelled_at_step: string,
	//       reason: string }   # e.g. "user_requested"
	//
	// Consumers MUST NOT regex on the payload. Each shape is
	// switched on `event_type`, fields are read by name.
	Payload map[string]interface{} `json:"payload"`

	// Sequence Monotonic per-job sequence number. The first event a job
	// ever emits is sequence=1. If ai-core crashes mid-run and a
	// retry resumes the pipeline, sequence continues from the
	// backend's stored `last_event_seq + 1` — it never resets.
	Sequence int `json:"sequence"`
}

// TailorJobEventType Closed set of event types ai-core emits. The frontend's progress
// timeline renders one step per non-`fill.progress` event;
// `tailor.fill.progress` is the only multi-event step (one event
// per parallel filler completing a card).
type TailorJobEventType string

// TailorJobOverrideRequest Body of POST /ai/tailor-jobs/:id/override. Empty payload by
// design — the backend already has the source job_id, the
// tailor_uuid, the resume, and the JD. The override flag is a
// server-side trip so we always have the audit trail of "user
// was told no_fit, then chose to override."
type TailorJobOverrideRequest struct {
	// AcknowledgeNoFit Must be true. The frontend sets it as the user clicks the
	// "tailor anyway" button. Defends against accidental retries
	// that look like overrides.
	AcknowledgeNoFit *bool `json:"acknowledge_no_fit,omitempty"`
}

// TailorJobSnapshot Canonical durable view of a job. Returned by:
//   - GET /ai/tailor-jobs/:id
//   - GET /ai/tailor-jobs/by-uuid/:tailor_uuid
//
// and as the initial frame on the SSE stream before live events
// start flowing. The frontend reconstructs UI state by replaying
// `events` in sequence order, then subscribing for new ones.
type TailorJobSnapshot struct {
	// CompletedAt When the job reached a terminal status (completed | no_fit |
	// failed | cancelled). Null until then.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Events All persisted events for this job, in ascending sequence
	// order. On initial GET this is the full history; on the SSE
	// stream this is the catch-up replay before live events.
	Events []TailorJobEvent `json:"events"`

	// FailReason Present when status is `failed`. Machine + human halves so
	// the frontend can render verbatim AND branch UX on the class.
	FailReason *struct {
		// ErrorClass Closed set, e.g. ai_core_unreachable, llm_timeout,
		// invalid_ai_response, validator_rejected, internal_error.
		ErrorClass *string `json:"error_class,omitempty"`

		// ErrorMessage Locale-aware message the user is shown.
		ErrorMessage *string `json:"error_message,omitempty"`

		// Retryable Whether the frontend should surface a "retry" button.
		// False for hard failures (invalid_ai_response after
		// exhausted retries).
		Retryable *bool `json:"retryable,omitempty"`
	} `json:"fail_reason,omitempty"`
	JobId openapi_types.UUID `json:"job_id"`

	// LastEventSeq Highest sequence the backend has persisted for this job.
	// SSE clients reconnecting pass this as `Last-Event-ID`.
	LastEventSeq int `json:"last_event_seq"`

	// ParentJobId Set when this job is an override of a previous no_fit job
	// (POST /ai/tailor-jobs/:id/override). Lets us audit
	// "user was told no_fit, then chose to tailor anyway".
	ParentJobId *openapi_types.UUID `json:"parent_job_id,omitempty"`

	// Result Present when status is `completed` or `no_fit`. Cached so
	// revisits never re-run the pipeline — the page just renders
	// from this snapshot.
	Result *TailorResponse `json:"result,omitempty"`

	// RetryCount How many times the orphan sweeper has re-enqueued this job.
	// Hard ceiling at 3 — beyond that the job is marked failed.
	RetryCount *int `json:"retry_count,omitempty"`

	// StartedAt When the runner first transitioned status to running.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status State machine for a tailor job.
	//
	// - `pending`    Row created, runner not yet picked it up.
	// - `running`    Runner started, ai-core executing.
	// - `completed`  Terminal. result_json populated, fit_verdict in
	//                {strong_fit, partial_fit, weak_fit}.
	// - `no_fit`     Terminal but distinct from `completed` because
	//                suggestions[] is empty by construction. UI shows
	//                the no-fit reason + offers an explicit override.
	// - `failed`     Terminal after exhausting retries. fail_reason
	//                carries an error_class + locale-aware message.
	// - `cancelled`  User-initiated abort. ai-core honors via
	//                ctx.Done() at the next step boundary.
	Status TailorJobStatus `json:"status"`

	// TailorUuid The tailor draft / sibling resume slot this job belongs to.
	// Stable across retries and override jobs — the frontend
	// queries by tailor_uuid on page mount, regardless of how many
	// job_ids a user has accumulated for the same target.
	TailorUuid openapi_types.UUID `json:"tailor_uuid"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// TailorJobStatus State machine for a tailor job.
//
//   - `pending`    Row created, runner not yet picked it up.
//   - `running`    Runner started, ai-core executing.
//   - `completed`  Terminal. result_json populated, fit_verdict in
//     {strong_fit, partial_fit, weak_fit}.
//   - `no_fit`     Terminal but distinct from `completed` because
//     suggestions[] is empty by construction. UI shows
//     the no-fit reason + offers an explicit override.
//   - `failed`     Terminal after exhausting retries. fail_reason
//     carries an error_class + locale-aware message.
//   - `cancelled`  User-initiated abort. ai-core honors via
//     ctx.Done() at the next step boundary.
type TailorJobStatus string

// TailorRequest defines model for TailorRequest.
type TailorRequest struct {
	// JobDescription Raw JD text. The worker parses it.
	JobDescription string              `json:"job_description"`
	Locale         TailorRequestLocale `json:"locale"`

	// Resume The full Resume DTO. ai-core consumes it typed and walks every
	// section, item, and description in order to produce Suggestions
	// with valid `target.section_index` / `target.item_index` indices
	// into THIS resume. The frontend must send the resume verbatim
	// (no stripping) so suggestions remain applicable.
	//
	// Consumers MUST import the typed Resume from
	// `@laddro-app/schemas/resume`:
	//   - TS:  `import type { components } from '@laddro-app/schemas/resume'`
	//          then `components['schemas']['Resume']`
	//   - Go:  `github.com/laddro-app/laddro-schemas/go/resume.Resume`
	//
	// The field is declared as `type: object` here only because OpenAPI
	// 3.1 cross-file `$ref` support is uneven across our codegen tools.
	// Treat it as `Resume` at every call site.
	Resume map[string]interface{} `json:"resume"`
}

// TailorRequestLocale defines model for TailorRequest.Locale.
type TailorRequestLocale string

// TailorResponse defines model for TailorResponse.
type TailorResponse struct {
	CompatibilityScore CompatibilityScore `json:"compatibility_score"`

	// FitVerdict Honest verdict on whether this resume can be tailored to this JD
	// at all. Derived from compatibility_score, the recommender's anchor
	// coverage (how many required skills have any resume evidence), and
	// the seniority gap.
	//
	// - `strong_fit`   normal stack, most requirements have anchors.
	// - `partial_fit`  normal stack, some gaps the user should know about.
	// - `weak_fit`     stack rendered with a banner: "low fit, consider
	//                  a different job — these are what we could find."
	// - `no_fit`       suggestions[] is empty by construction. Frontend
	//                  shows "this isn't your job — we don't fake resumes,
	//                  we prepare you for the job." Backed by no_fit_reason.
	//
	// ai-core owns the decision rule. Frontend branches UX off this enum
	// only — it never re-derives the verdict from the score.
	FitVerdict TailorResponseFitVerdict `json:"fit_verdict"`

	// NoFitReason Present when fit_verdict is `weak_fit` or `no_fit`. Machine-readable
	// primary cause + locale-aware human explanation the frontend can
	// surface verbatim.
	NoFitReason *NoFitReason   `json:"no_fit_reason,omitempty"`
	ParsedJob   JobDescription `json:"parsed_job"`
	Suggestions []Suggestion   `json:"suggestions"`
}

// TailorResponseFitVerdict Honest verdict on whether this resume can be tailored to this JD
// at all. Derived from compatibility_score, the recommender's anchor
// coverage (how many required skills have any resume evidence), and
// the seniority gap.
//
//   - `strong_fit`   normal stack, most requirements have anchors.
//   - `partial_fit`  normal stack, some gaps the user should know about.
//   - `weak_fit`     stack rendered with a banner: "low fit, consider
//     a different job — these are what we could find."
//   - `no_fit`       suggestions[] is empty by construction. Frontend
//     shows "this isn't your job — we don't fake resumes,
//     we prepare you for the job." Backed by no_fit_reason.
//
// ai-core owns the decision rule. Frontend branches UX off this enum
// only — it never re-derives the verdict from the score.
type TailorResponseFitVerdict string

// WorkerAnalyzeRequest defines model for WorkerAnalyzeRequest.
type WorkerAnalyzeRequest struct {
	Locale WorkerAnalyzeRequestLocale `json:"locale"`

	// Text Raw job description as the user pasted it.
	Text string `json:"text"`
}

// WorkerAnalyzeRequestLocale defines model for WorkerAnalyzeRequest.Locale.
type WorkerAnalyzeRequestLocale string

// WorkerAnalyzeResponse defines model for WorkerAnalyzeResponse.
type WorkerAnalyzeResponse = JobDescription

// AsBulletTarget returns the union data inside the SuggestionTarget as a BulletTarget
func (t SuggestionTarget) AsBulletTarget() (BulletTarget, error) {
	var body BulletTarget
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBulletTarget overwrites any union data inside the SuggestionTarget as the provided BulletTarget
func (t *SuggestionTarget) FromBulletTarget(v BulletTarget) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"scope":"bullet"}`))
	t.union = b
	return err
}

// MergeBulletTarget performs a merge with any union data inside the SuggestionTarget, using the provided BulletTarget
func (t *SuggestionTarget) MergeBulletTarget(v BulletTarget) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"scope":"bullet"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSummaryTarget returns the union data inside the SuggestionTarget as a SummaryTarget
func (t SuggestionTarget) AsSummaryTarget() (SummaryTarget, error) {
	var body SummaryTarget
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSummaryTarget overwrites any union data inside the SuggestionTarget as the provided SummaryTarget
func (t *SuggestionTarget) FromSummaryTarget(v SummaryTarget) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"scope":"summary"}`))
	t.union = b
	return err
}

// MergeSummaryTarget performs a merge with any union data inside the SuggestionTarget, using the provided SummaryTarget
func (t *SuggestionTarget) MergeSummaryTarget(v SummaryTarget) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"scope":"summary"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSkillTarget returns the union data inside the SuggestionTarget as a SkillTarget
func (t SuggestionTarget) AsSkillTarget() (SkillTarget, error) {
	var body SkillTarget
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSkillTarget overwrites any union data inside the SuggestionTarget as the provided SkillTarget
func (t *SuggestionTarget) FromSkillTarget(v SkillTarget) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"scope":"skill"}`))
	t.union = b
	return err
}

// MergeSkillTarget performs a merge with any union data inside the SuggestionTarget, using the provided SkillTarget
func (t *SuggestionTarget) MergeSkillTarget(v SkillTarget) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"scope":"skill"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SuggestionTarget) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"scope"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SuggestionTarget) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "bullet":
		return t.AsBulletTarget()
	case "skill":
		return t.AsSkillTarget()
	case "summary":
		return t.AsSummaryTarget()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SuggestionTarget) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SuggestionTarget) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
