// Package tailor provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package tailor

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FillRequestLocale.
const (
	FillRequestLocaleDa FillRequestLocale = "da"
	FillRequestLocaleDe FillRequestLocale = "de"
	FillRequestLocaleEn FillRequestLocale = "en"
	FillRequestLocaleEs FillRequestLocale = "es"
	FillRequestLocaleEt FillRequestLocale = "et"
	FillRequestLocaleFi FillRequestLocale = "fi"
	FillRequestLocaleFr FillRequestLocale = "fr"
	FillRequestLocaleIs FillRequestLocale = "is"
	FillRequestLocaleIt FillRequestLocale = "it"
	FillRequestLocaleNl FillRequestLocale = "nl"
	FillRequestLocaleNo FillRequestLocale = "no"
	FillRequestLocalePl FillRequestLocale = "pl"
	FillRequestLocalePt FillRequestLocale = "pt"
	FillRequestLocaleSv FillRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the FillRequestLocale enum.
func (e FillRequestLocale) Valid() bool {
	switch e {
	case FillRequestLocaleDa:
		return true
	case FillRequestLocaleDe:
		return true
	case FillRequestLocaleEn:
		return true
	case FillRequestLocaleEs:
		return true
	case FillRequestLocaleEt:
		return true
	case FillRequestLocaleFi:
		return true
	case FillRequestLocaleFr:
		return true
	case FillRequestLocaleIs:
		return true
	case FillRequestLocaleIt:
		return true
	case FillRequestLocaleNl:
		return true
	case FillRequestLocaleNo:
		return true
	case FillRequestLocalePl:
		return true
	case FillRequestLocalePt:
		return true
	case FillRequestLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for JobDescriptionLocale.
const (
	JobDescriptionLocaleDa JobDescriptionLocale = "da"
	JobDescriptionLocaleDe JobDescriptionLocale = "de"
	JobDescriptionLocaleEn JobDescriptionLocale = "en"
	JobDescriptionLocaleEs JobDescriptionLocale = "es"
	JobDescriptionLocaleEt JobDescriptionLocale = "et"
	JobDescriptionLocaleFi JobDescriptionLocale = "fi"
	JobDescriptionLocaleFr JobDescriptionLocale = "fr"
	JobDescriptionLocaleIs JobDescriptionLocale = "is"
	JobDescriptionLocaleIt JobDescriptionLocale = "it"
	JobDescriptionLocaleNl JobDescriptionLocale = "nl"
	JobDescriptionLocaleNo JobDescriptionLocale = "no"
	JobDescriptionLocalePl JobDescriptionLocale = "pl"
	JobDescriptionLocalePt JobDescriptionLocale = "pt"
	JobDescriptionLocaleSv JobDescriptionLocale = "sv"
)

// Valid indicates whether the value is a known member of the JobDescriptionLocale enum.
func (e JobDescriptionLocale) Valid() bool {
	switch e {
	case JobDescriptionLocaleDa:
		return true
	case JobDescriptionLocaleDe:
		return true
	case JobDescriptionLocaleEn:
		return true
	case JobDescriptionLocaleEs:
		return true
	case JobDescriptionLocaleEt:
		return true
	case JobDescriptionLocaleFi:
		return true
	case JobDescriptionLocaleFr:
		return true
	case JobDescriptionLocaleIs:
		return true
	case JobDescriptionLocaleIt:
		return true
	case JobDescriptionLocaleNl:
		return true
	case JobDescriptionLocaleNo:
		return true
	case JobDescriptionLocalePl:
		return true
	case JobDescriptionLocalePt:
		return true
	case JobDescriptionLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for RequirementCategory.
const (
	RequirementCategoryExperience     RequirementCategory = "experience"
	RequirementCategoryQualification  RequirementCategory = "qualification"
	RequirementCategoryResponsibility RequirementCategory = "responsibility"
	RequirementCategorySkill          RequirementCategory = "skill"
	RequirementCategorySoft           RequirementCategory = "soft"
)

// Valid indicates whether the value is a known member of the RequirementCategory enum.
func (e RequirementCategory) Valid() bool {
	switch e {
	case RequirementCategoryExperience:
		return true
	case RequirementCategoryQualification:
		return true
	case RequirementCategoryResponsibility:
		return true
	case RequirementCategorySkill:
		return true
	case RequirementCategorySoft:
		return true
	default:
		return false
	}
}

// Defines values for SeniorityLevel.
const (
	Entry   SeniorityLevel = "entry"
	Lead    SeniorityLevel = "lead"
	Mid     SeniorityLevel = "mid"
	Senior  SeniorityLevel = "senior"
	Unknown SeniorityLevel = "unknown"
)

// Valid indicates whether the value is a known member of the SeniorityLevel enum.
func (e SeniorityLevel) Valid() bool {
	switch e {
	case Entry:
		return true
	case Lead:
		return true
	case Mid:
		return true
	case Senior:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SuggestionType.
const (
	AddBullet     SuggestionType = "add_bullet"
	RewriteBullet SuggestionType = "rewrite_bullet"
)

// Valid indicates whether the value is a known member of the SuggestionType enum.
func (e SuggestionType) Valid() bool {
	switch e {
	case AddBullet:
		return true
	case RewriteBullet:
		return true
	default:
		return false
	}
}

// Defines values for TailorRequestLocale.
const (
	TailorRequestLocaleDa TailorRequestLocale = "da"
	TailorRequestLocaleDe TailorRequestLocale = "de"
	TailorRequestLocaleEn TailorRequestLocale = "en"
	TailorRequestLocaleEs TailorRequestLocale = "es"
	TailorRequestLocaleEt TailorRequestLocale = "et"
	TailorRequestLocaleFi TailorRequestLocale = "fi"
	TailorRequestLocaleFr TailorRequestLocale = "fr"
	TailorRequestLocaleIs TailorRequestLocale = "is"
	TailorRequestLocaleIt TailorRequestLocale = "it"
	TailorRequestLocaleNl TailorRequestLocale = "nl"
	TailorRequestLocaleNo TailorRequestLocale = "no"
	TailorRequestLocalePl TailorRequestLocale = "pl"
	TailorRequestLocalePt TailorRequestLocale = "pt"
	TailorRequestLocaleSv TailorRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the TailorRequestLocale enum.
func (e TailorRequestLocale) Valid() bool {
	switch e {
	case TailorRequestLocaleDa:
		return true
	case TailorRequestLocaleDe:
		return true
	case TailorRequestLocaleEn:
		return true
	case TailorRequestLocaleEs:
		return true
	case TailorRequestLocaleEt:
		return true
	case TailorRequestLocaleFi:
		return true
	case TailorRequestLocaleFr:
		return true
	case TailorRequestLocaleIs:
		return true
	case TailorRequestLocaleIt:
		return true
	case TailorRequestLocaleNl:
		return true
	case TailorRequestLocaleNo:
		return true
	case TailorRequestLocalePl:
		return true
	case TailorRequestLocalePt:
		return true
	case TailorRequestLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for WorkerAnalyzeRequestLocale.
const (
	WorkerAnalyzeRequestLocaleDa WorkerAnalyzeRequestLocale = "da"
	WorkerAnalyzeRequestLocaleDe WorkerAnalyzeRequestLocale = "de"
	WorkerAnalyzeRequestLocaleEn WorkerAnalyzeRequestLocale = "en"
	WorkerAnalyzeRequestLocaleEs WorkerAnalyzeRequestLocale = "es"
	WorkerAnalyzeRequestLocaleEt WorkerAnalyzeRequestLocale = "et"
	WorkerAnalyzeRequestLocaleFi WorkerAnalyzeRequestLocale = "fi"
	WorkerAnalyzeRequestLocaleFr WorkerAnalyzeRequestLocale = "fr"
	WorkerAnalyzeRequestLocaleIs WorkerAnalyzeRequestLocale = "is"
	WorkerAnalyzeRequestLocaleIt WorkerAnalyzeRequestLocale = "it"
	WorkerAnalyzeRequestLocaleNl WorkerAnalyzeRequestLocale = "nl"
	WorkerAnalyzeRequestLocaleNo WorkerAnalyzeRequestLocale = "no"
	WorkerAnalyzeRequestLocalePl WorkerAnalyzeRequestLocale = "pl"
	WorkerAnalyzeRequestLocalePt WorkerAnalyzeRequestLocale = "pt"
	WorkerAnalyzeRequestLocaleSv WorkerAnalyzeRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the WorkerAnalyzeRequestLocale enum.
func (e WorkerAnalyzeRequestLocale) Valid() bool {
	switch e {
	case WorkerAnalyzeRequestLocaleDa:
		return true
	case WorkerAnalyzeRequestLocaleDe:
		return true
	case WorkerAnalyzeRequestLocaleEn:
		return true
	case WorkerAnalyzeRequestLocaleEs:
		return true
	case WorkerAnalyzeRequestLocaleEt:
		return true
	case WorkerAnalyzeRequestLocaleFi:
		return true
	case WorkerAnalyzeRequestLocaleFr:
		return true
	case WorkerAnalyzeRequestLocaleIs:
		return true
	case WorkerAnalyzeRequestLocaleIt:
		return true
	case WorkerAnalyzeRequestLocaleNl:
		return true
	case WorkerAnalyzeRequestLocaleNo:
		return true
	case WorkerAnalyzeRequestLocalePl:
		return true
	case WorkerAnalyzeRequestLocalePt:
		return true
	case WorkerAnalyzeRequestLocaleSv:
		return true
	default:
		return false
	}
}

// CompatibilityScore defines model for CompatibilityScore.
type CompatibilityScore struct {
	Breakdown ScoreBreakdown `json:"breakdown"`

	// Total Live-updating score shown at top of suggestion stack. Recomputed
	// client-side as suggestions are accepted/discarded using the same
	// formula the backend would produce.
	Total int `json:"total"`
}

// FillRequest defines model for FillRequest.
type FillRequest struct {
	// Evidence Resume bullets / facts the writer is allowed to draw from. The
	// writer refuses (422) when none of the evidence supports the
	// instruction — the no-fabrication gate.
	Evidence []struct {
		// Source e.g. 'experience[0].bullets[2]'
		Source string `json:"source"`
		Text   string `json:"text"`
	} `json:"evidence"`
	Locale     FillRequestLocale `json:"locale"`
	Suggestion Suggestion        `json:"suggestion"`
}

// FillRequestLocale defines model for FillRequest.Locale.
type FillRequestLocale string

// FillResponse defines model for FillResponse.
type FillResponse struct {
	// ProposedText Writer LLM output, in the requested locale. Single bullet, no
	// headers, no preamble. Strictly grounded in `evidence`.
	ProposedText string `json:"proposed_text"`
}

// JobDescription defines model for JobDescription.
type JobDescription struct {
	// Company Company / organization name from NER. Empty string when none
	// detected. Never falls back to text patterns.
	Company *string              `json:"company,omitempty"`
	Locale  JobDescriptionLocale `json:"locale"`

	// RawText The original input, preserved verbatim for source-span lookups.
	RawText      string        `json:"raw_text"`
	Requirements []Requirement `json:"requirements"`
	Seniority    Seniority     `json:"seniority"`
	Skills       []Skill       `json:"skills"`

	// Title Job title as identified by NER, in the JD's source language. Empty
	// string when the model could not identify one. Never falls back to
	// "first non-empty line" or any other structural heuristic.
	Title *string `json:"title,omitempty"`
}

// JobDescriptionLocale defines model for JobDescription.Locale.
type JobDescriptionLocale string

// Requirement defines model for Requirement.
type Requirement struct {
	// Category Canonical category, classified by the model. This set is
	// deliberately industry-agnostic: a nurse's "patient handover" and
	// an engineer's "deploy to prod" both map to `responsibility`. A
	// welder's "MIG certification" and a lawyer's "bar admission" both
	// map to `qualification`. New categories require a contract bump,
	// not a code patch.
	Category    RequirementCategory `json:"category"`
	Confidence  float32             `json:"confidence"`
	SourceQuote string              `json:"source_quote"`

	// Text The requirement span, verbatim from raw_text.
	Text string `json:"text"`
}

// RequirementCategory Canonical category, classified by the model. This set is
// deliberately industry-agnostic: a nurse's "patient handover" and
// an engineer's "deploy to prod" both map to `responsibility`. A
// welder's "MIG certification" and a lawyer's "bar admission" both
// map to `qualification`. New categories require a contract bump,
// not a code patch.
type RequirementCategory string

// ScoreBreakdown defines model for ScoreBreakdown.
type ScoreBreakdown struct {
	// AdjacentSkills Share covered by semantically-adjacent skills (embedding
	// similarity above the calibrated threshold). NEVER token overlap.
	AdjacentSkills float32 `json:"adjacent_skills"`

	// ExactSkills Share of required skills the resume already covers exactly.
	ExactSkills float32 `json:"exact_skills"`

	// SeniorityFit How well the resume's experience aligns with JobDescription.
	// seniority — calibrated against the eval set, not a hardcoded
	// ladder.
	SeniorityFit float32 `json:"seniority_fit"`
}

// Seniority defines model for Seniority.
type Seniority struct {
	// Confidence Model confidence in the `level` label.
	Confidence float32 `json:"confidence"`

	// Level Seniority bucket, classified by a multilingual model. `unknown`
	// when the model's confidence is below the configured floor — NEVER
	// inferred from years_min via a hardcoded ladder.
	Level SeniorityLevel `json:"level"`

	// YearsMax Maximum years asked for. 0 when none stated.
	YearsMax *int `json:"years_max,omitempty"`

	// YearsMin Minimum years-of-experience asked for, extracted via locale-aware
	// structured extraction. 0 when none stated. Phrasing varies wildly
	// across locales ("3+ years", "Berufserfahrung von 3 Jahren",
	// "5 vuoden kokemus") — extraction is the model's job, not regex.
	YearsMin *int `json:"years_min,omitempty"`
}

// SeniorityLevel Seniority bucket, classified by a multilingual model. `unknown`
// when the model's confidence is below the configured floor — NEVER
// inferred from years_min via a hardcoded ladder.
type SeniorityLevel string

// Skill defines model for Skill.
type Skill struct {
	Confidence float32 `json:"confidence"`

	// EscoId ESCO concept URI when the multilingual ESCO linker matched this
	// skill. Empty when no link — scorer falls back to embedding
	// similarity, never to string matching.
	EscoId *string `json:"esco_id,omitempty"`

	// Label Skill name as it appeared in the JD, in source language.
	Label string `json:"label"`

	// Normalized Canonical form for deduplication only. Produced by the model's
	// normalizer (lowercase + locale-aware diacritic handling). Not
	// used for semantic matching — that's embeddings' job.
	Normalized string `json:"normalized"`

	// Required Whether the JD treats this skill as required vs nice-to-have.
	// This is a span-classifier output across all 14 locales — NOT a
	// keyword scan over "required"/"must have"/"nice to have". When
	// the classifier's confidence is below the configured floor, the
	// worker omits the skill rather than defaulting to required.
	Required bool `json:"required"`

	// SourceQuote The original span the model attributed this skill to, verbatim
	// from raw_text. The frontend shows it as "from the JD: ...".
	SourceQuote string `json:"source_quote"`
}

// Suggestion defines model for Suggestion.
type Suggestion struct {
	Id openapi_types.UUID `json:"id"`

	// Instruction Locale-aware instruction the writer LLM uses to produce
	// proposed_text. Generated by the recommender, not free-form.
	Instruction string `json:"instruction"`

	// OriginalText For rewrite: the bullet text. For add: the anchor span from the
	// resume. Quoted to the user as proof we're not fabricating.
	OriginalText string `json:"original_text"`

	// ProposedText Empty until the writer LLM is called for this suggestion (lazy
	// per-card via /v1/tailor/fill). Discarded suggestions stay empty
	// and cost zero LLM tokens.
	ProposedText *string `json:"proposed_text,omitempty"`

	// RequirementRef ID of the JobDescription.requirement (or skill) this suggestion
	// addresses. Lets the frontend show "this card addresses THIS ask
	// from the JD" with the source_quote highlighted.
	RequirementRef string `json:"requirement_ref"`

	// Type `rewrite_bullet` — there's an existing bullet the user can sharpen
	// to match the requirement. `original_text` is the bullet,
	// `instruction` is what to change.
	//
	// `add_bullet` — the requirement is missing entirely AND we found
	// a resume anchor (existing experience that plausibly supports
	// it). `original_text` is the anchor span the new bullet must
	// stay faithful to; the writer is forbidden from going beyond it.
	Type SuggestionType `json:"type"`
}

// SuggestionType `rewrite_bullet` — there's an existing bullet the user can sharpen
// to match the requirement. `original_text` is the bullet,
// `instruction` is what to change.
//
// `add_bullet` — the requirement is missing entirely AND we found
// a resume anchor (existing experience that plausibly supports
// it). `original_text` is the anchor span the new bullet must
// stay faithful to; the writer is forbidden from going beyond it.
type SuggestionType string

// TailorRequest defines model for TailorRequest.
type TailorRequest struct {
	// JobDescription Raw JD text. The worker parses it.
	JobDescription string              `json:"job_description"`
	Locale         TailorRequestLocale `json:"locale"`

	// Resume Full Resume DTO from @laddro-app/schemas/resume. Reffed loosely
	// here because YAML cross-spec refs are awkward — code uses the
	// generated Resume type directly.
	Resume map[string]interface{} `json:"resume"`
}

// TailorRequestLocale defines model for TailorRequest.Locale.
type TailorRequestLocale string

// TailorResponse defines model for TailorResponse.
type TailorResponse struct {
	CompatibilityScore CompatibilityScore `json:"compatibility_score"`
	ParsedJob          JobDescription     `json:"parsed_job"`
	Suggestions        []Suggestion       `json:"suggestions"`
}

// WorkerAnalyzeRequest defines model for WorkerAnalyzeRequest.
type WorkerAnalyzeRequest struct {
	Locale WorkerAnalyzeRequestLocale `json:"locale"`

	// Text Raw job description as the user pasted it.
	Text string `json:"text"`
}

// WorkerAnalyzeRequestLocale defines model for WorkerAnalyzeRequest.Locale.
type WorkerAnalyzeRequestLocale string

// WorkerAnalyzeResponse defines model for WorkerAnalyzeResponse.
type WorkerAnalyzeResponse = JobDescription
