// Package tailor provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package tailor

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BulletTargetScope.
const (
	Bullet BulletTargetScope = "bullet"
)

// Valid indicates whether the value is a known member of the BulletTargetScope enum.
func (e BulletTargetScope) Valid() bool {
	switch e {
	case Bullet:
		return true
	default:
		return false
	}
}

// Defines values for FillRequestLocale.
const (
	FillRequestLocaleDa FillRequestLocale = "da"
	FillRequestLocaleDe FillRequestLocale = "de"
	FillRequestLocaleEn FillRequestLocale = "en"
	FillRequestLocaleEs FillRequestLocale = "es"
	FillRequestLocaleEt FillRequestLocale = "et"
	FillRequestLocaleFi FillRequestLocale = "fi"
	FillRequestLocaleFr FillRequestLocale = "fr"
	FillRequestLocaleIs FillRequestLocale = "is"
	FillRequestLocaleIt FillRequestLocale = "it"
	FillRequestLocaleNl FillRequestLocale = "nl"
	FillRequestLocaleNo FillRequestLocale = "no"
	FillRequestLocalePl FillRequestLocale = "pl"
	FillRequestLocalePt FillRequestLocale = "pt"
	FillRequestLocaleSv FillRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the FillRequestLocale enum.
func (e FillRequestLocale) Valid() bool {
	switch e {
	case FillRequestLocaleDa:
		return true
	case FillRequestLocaleDe:
		return true
	case FillRequestLocaleEn:
		return true
	case FillRequestLocaleEs:
		return true
	case FillRequestLocaleEt:
		return true
	case FillRequestLocaleFi:
		return true
	case FillRequestLocaleFr:
		return true
	case FillRequestLocaleIs:
		return true
	case FillRequestLocaleIt:
		return true
	case FillRequestLocaleNl:
		return true
	case FillRequestLocaleNo:
		return true
	case FillRequestLocalePl:
		return true
	case FillRequestLocalePt:
		return true
	case FillRequestLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for JobDescriptionLocale.
const (
	JobDescriptionLocaleDa JobDescriptionLocale = "da"
	JobDescriptionLocaleDe JobDescriptionLocale = "de"
	JobDescriptionLocaleEn JobDescriptionLocale = "en"
	JobDescriptionLocaleEs JobDescriptionLocale = "es"
	JobDescriptionLocaleEt JobDescriptionLocale = "et"
	JobDescriptionLocaleFi JobDescriptionLocale = "fi"
	JobDescriptionLocaleFr JobDescriptionLocale = "fr"
	JobDescriptionLocaleIs JobDescriptionLocale = "is"
	JobDescriptionLocaleIt JobDescriptionLocale = "it"
	JobDescriptionLocaleNl JobDescriptionLocale = "nl"
	JobDescriptionLocaleNo JobDescriptionLocale = "no"
	JobDescriptionLocalePl JobDescriptionLocale = "pl"
	JobDescriptionLocalePt JobDescriptionLocale = "pt"
	JobDescriptionLocaleSv JobDescriptionLocale = "sv"
)

// Valid indicates whether the value is a known member of the JobDescriptionLocale enum.
func (e JobDescriptionLocale) Valid() bool {
	switch e {
	case JobDescriptionLocaleDa:
		return true
	case JobDescriptionLocaleDe:
		return true
	case JobDescriptionLocaleEn:
		return true
	case JobDescriptionLocaleEs:
		return true
	case JobDescriptionLocaleEt:
		return true
	case JobDescriptionLocaleFi:
		return true
	case JobDescriptionLocaleFr:
		return true
	case JobDescriptionLocaleIs:
		return true
	case JobDescriptionLocaleIt:
		return true
	case JobDescriptionLocaleNl:
		return true
	case JobDescriptionLocaleNo:
		return true
	case JobDescriptionLocalePl:
		return true
	case JobDescriptionLocalePt:
		return true
	case JobDescriptionLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for NoFitReasonPrimary.
const (
	IndustryMismatch     NoFitReasonPrimary = "industry_mismatch"
	InsufficientEvidence NoFitReasonPrimary = "insufficient_evidence"
	SeniorityGap         NoFitReasonPrimary = "seniority_gap"
	SkillsGap            NoFitReasonPrimary = "skills_gap"
)

// Valid indicates whether the value is a known member of the NoFitReasonPrimary enum.
func (e NoFitReasonPrimary) Valid() bool {
	switch e {
	case IndustryMismatch:
		return true
	case InsufficientEvidence:
		return true
	case SeniorityGap:
		return true
	case SkillsGap:
		return true
	default:
		return false
	}
}

// Defines values for RequirementCategory.
const (
	RequirementCategoryExperience     RequirementCategory = "experience"
	RequirementCategoryQualification  RequirementCategory = "qualification"
	RequirementCategoryResponsibility RequirementCategory = "responsibility"
	RequirementCategorySkill          RequirementCategory = "skill"
	RequirementCategorySoft           RequirementCategory = "soft"
)

// Valid indicates whether the value is a known member of the RequirementCategory enum.
func (e RequirementCategory) Valid() bool {
	switch e {
	case RequirementCategoryExperience:
		return true
	case RequirementCategoryQualification:
		return true
	case RequirementCategoryResponsibility:
		return true
	case RequirementCategorySkill:
		return true
	case RequirementCategorySoft:
		return true
	default:
		return false
	}
}

// Defines values for SeniorityLevel.
const (
	Entry   SeniorityLevel = "entry"
	Lead    SeniorityLevel = "lead"
	Mid     SeniorityLevel = "mid"
	Senior  SeniorityLevel = "senior"
	Unknown SeniorityLevel = "unknown"
)

// Valid indicates whether the value is a known member of the SeniorityLevel enum.
func (e SeniorityLevel) Valid() bool {
	switch e {
	case Entry:
		return true
	case Lead:
		return true
	case Mid:
		return true
	case Senior:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SkillTargetScope.
const (
	SkillTargetScopeSkill SkillTargetScope = "skill"
)

// Valid indicates whether the value is a known member of the SkillTargetScope enum.
func (e SkillTargetScope) Valid() bool {
	switch e {
	case SkillTargetScopeSkill:
		return true
	default:
		return false
	}
}

// Defines values for SuggestionKind.
const (
	AddBullet      SuggestionKind = "add_bullet"
	AddSkill       SuggestionKind = "add_skill"
	RewriteBullet  SuggestionKind = "rewrite_bullet"
	RewriteSummary SuggestionKind = "rewrite_summary"
)

// Valid indicates whether the value is a known member of the SuggestionKind enum.
func (e SuggestionKind) Valid() bool {
	switch e {
	case AddBullet:
		return true
	case AddSkill:
		return true
	case RewriteBullet:
		return true
	case RewriteSummary:
		return true
	default:
		return false
	}
}

// Defines values for SummaryTargetScope.
const (
	Summary SummaryTargetScope = "summary"
)

// Valid indicates whether the value is a known member of the SummaryTargetScope enum.
func (e SummaryTargetScope) Valid() bool {
	switch e {
	case Summary:
		return true
	default:
		return false
	}
}

// Defines values for TailorRequestLocale.
const (
	TailorRequestLocaleDa TailorRequestLocale = "da"
	TailorRequestLocaleDe TailorRequestLocale = "de"
	TailorRequestLocaleEn TailorRequestLocale = "en"
	TailorRequestLocaleEs TailorRequestLocale = "es"
	TailorRequestLocaleEt TailorRequestLocale = "et"
	TailorRequestLocaleFi TailorRequestLocale = "fi"
	TailorRequestLocaleFr TailorRequestLocale = "fr"
	TailorRequestLocaleIs TailorRequestLocale = "is"
	TailorRequestLocaleIt TailorRequestLocale = "it"
	TailorRequestLocaleNl TailorRequestLocale = "nl"
	TailorRequestLocaleNo TailorRequestLocale = "no"
	TailorRequestLocalePl TailorRequestLocale = "pl"
	TailorRequestLocalePt TailorRequestLocale = "pt"
	TailorRequestLocaleSv TailorRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the TailorRequestLocale enum.
func (e TailorRequestLocale) Valid() bool {
	switch e {
	case TailorRequestLocaleDa:
		return true
	case TailorRequestLocaleDe:
		return true
	case TailorRequestLocaleEn:
		return true
	case TailorRequestLocaleEs:
		return true
	case TailorRequestLocaleEt:
		return true
	case TailorRequestLocaleFi:
		return true
	case TailorRequestLocaleFr:
		return true
	case TailorRequestLocaleIs:
		return true
	case TailorRequestLocaleIt:
		return true
	case TailorRequestLocaleNl:
		return true
	case TailorRequestLocaleNo:
		return true
	case TailorRequestLocalePl:
		return true
	case TailorRequestLocalePt:
		return true
	case TailorRequestLocaleSv:
		return true
	default:
		return false
	}
}

// Defines values for TailorResponseFitVerdict.
const (
	NoFit      TailorResponseFitVerdict = "no_fit"
	PartialFit TailorResponseFitVerdict = "partial_fit"
	StrongFit  TailorResponseFitVerdict = "strong_fit"
	WeakFit    TailorResponseFitVerdict = "weak_fit"
)

// Valid indicates whether the value is a known member of the TailorResponseFitVerdict enum.
func (e TailorResponseFitVerdict) Valid() bool {
	switch e {
	case NoFit:
		return true
	case PartialFit:
		return true
	case StrongFit:
		return true
	case WeakFit:
		return true
	default:
		return false
	}
}

// Defines values for WorkerAnalyzeRequestLocale.
const (
	WorkerAnalyzeRequestLocaleDa WorkerAnalyzeRequestLocale = "da"
	WorkerAnalyzeRequestLocaleDe WorkerAnalyzeRequestLocale = "de"
	WorkerAnalyzeRequestLocaleEn WorkerAnalyzeRequestLocale = "en"
	WorkerAnalyzeRequestLocaleEs WorkerAnalyzeRequestLocale = "es"
	WorkerAnalyzeRequestLocaleEt WorkerAnalyzeRequestLocale = "et"
	WorkerAnalyzeRequestLocaleFi WorkerAnalyzeRequestLocale = "fi"
	WorkerAnalyzeRequestLocaleFr WorkerAnalyzeRequestLocale = "fr"
	WorkerAnalyzeRequestLocaleIs WorkerAnalyzeRequestLocale = "is"
	WorkerAnalyzeRequestLocaleIt WorkerAnalyzeRequestLocale = "it"
	WorkerAnalyzeRequestLocaleNl WorkerAnalyzeRequestLocale = "nl"
	WorkerAnalyzeRequestLocaleNo WorkerAnalyzeRequestLocale = "no"
	WorkerAnalyzeRequestLocalePl WorkerAnalyzeRequestLocale = "pl"
	WorkerAnalyzeRequestLocalePt WorkerAnalyzeRequestLocale = "pt"
	WorkerAnalyzeRequestLocaleSv WorkerAnalyzeRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the WorkerAnalyzeRequestLocale enum.
func (e WorkerAnalyzeRequestLocale) Valid() bool {
	switch e {
	case WorkerAnalyzeRequestLocaleDa:
		return true
	case WorkerAnalyzeRequestLocaleDe:
		return true
	case WorkerAnalyzeRequestLocaleEn:
		return true
	case WorkerAnalyzeRequestLocaleEs:
		return true
	case WorkerAnalyzeRequestLocaleEt:
		return true
	case WorkerAnalyzeRequestLocaleFi:
		return true
	case WorkerAnalyzeRequestLocaleFr:
		return true
	case WorkerAnalyzeRequestLocaleIs:
		return true
	case WorkerAnalyzeRequestLocaleIt:
		return true
	case WorkerAnalyzeRequestLocaleNl:
		return true
	case WorkerAnalyzeRequestLocaleNo:
		return true
	case WorkerAnalyzeRequestLocalePl:
		return true
	case WorkerAnalyzeRequestLocalePt:
		return true
	case WorkerAnalyzeRequestLocaleSv:
		return true
	default:
		return false
	}
}

// BulletTarget defines model for BulletTarget.
type BulletTarget struct {
	// ItemIndex Index into `resume.sections[section_index].items[]`. The pointed-at
	// section MUST be one whose items have a `description` field:
	// employment, education, certifications, projects,
	// extraCurricularActivities. Skills/Languages/References sections
	// are not valid targets for rewrite_bullet/add_bullet.
	ItemIndex int               `json:"item_index"`
	Scope     BulletTargetScope `json:"scope"`

	// SectionIndex Index into `resume.sections[]`.
	SectionIndex int `json:"section_index"`
}

// BulletTargetScope defines model for BulletTarget.Scope.
type BulletTargetScope string

// CompatibilityScore defines model for CompatibilityScore.
type CompatibilityScore struct {
	Breakdown ScoreBreakdown `json:"breakdown"`

	// Total Live-updating score shown at top of suggestion stack. Recomputed
	// client-side as suggestions are accepted/discarded using the same
	// formula the backend would produce.
	Total int `json:"total"`
}

// Evidence defines model for Evidence.
type Evidence struct {
	Source EvidenceSource `json:"source"`

	// Text The evidence text verbatim from the resume.
	Text string `json:"text"`
}

// EvidenceSource defines model for EvidenceSource.
type EvidenceSource struct {
	// FragmentAnchor Verbatim HTML fragment within the item's description (or skill
	// label / etc) that this evidence quotes. Empty when the evidence
	// is the whole item (e.g. a SkillItem or LanguageItem). Used by
	// auditing and by the writer to know exactly which span to ground
	// against — NEVER for regex or substring rewriting in the writer.
	FragmentAnchor *string `json:"fragment_anchor,omitempty"`

	// ItemIndex Index into that section's `items[]`.
	ItemIndex int `json:"item_index"`

	// SectionIndex Index into `resume.sections[]` this evidence came from.
	SectionIndex int `json:"section_index"`
}

// FillRequest defines model for FillRequest.
type FillRequest struct {
	// Evidence Resume spans the writer is allowed to draw from. The writer
	// refuses (422) when none of the evidence supports the instruction
	// — the no-fabrication gate. Every span carries a structured
	// EvidenceSource so the writer's grounding is auditable: we can
	// always answer "which bullet did this proposed text come from?"
	Evidence   []Evidence        `json:"evidence"`
	Locale     FillRequestLocale `json:"locale"`
	Suggestion Suggestion        `json:"suggestion"`
}

// FillRequestLocale defines model for FillRequest.Locale.
type FillRequestLocale string

// FillResponse defines model for FillResponse.
type FillResponse struct {
	// ProposedText Writer LLM output, in the requested locale. Single bullet, no
	// headers, no preamble. Strictly grounded in `evidence`.
	ProposedText string `json:"proposed_text"`
}

// JobDescription defines model for JobDescription.
type JobDescription struct {
	// Company Company / organization name from NER. Empty string when none
	// detected. Never falls back to text patterns.
	Company *string              `json:"company,omitempty"`
	Locale  JobDescriptionLocale `json:"locale"`

	// RawText The original input, preserved verbatim for source-span lookups.
	RawText      string        `json:"raw_text"`
	Requirements []Requirement `json:"requirements"`
	Seniority    Seniority     `json:"seniority"`
	Skills       []Skill       `json:"skills"`

	// Title Job title as identified by NER, in the JD's source language. Empty
	// string when the model could not identify one. Never falls back to
	// "first non-empty line" or any other structural heuristic.
	Title *string `json:"title,omitempty"`
}

// JobDescriptionLocale defines model for JobDescription.Locale.
type JobDescriptionLocale string

// NoFitReason defines model for NoFitReason.
type NoFitReason struct {
	// Explanation One- or two-sentence reason in the user's locale, drawn from i18n
	// strings — not free-form LLM output. Frontend shows verbatim.
	Explanation string `json:"explanation"`

	// Primary - `skills_gap`            JD's required skills aren't present in the resume
	//                           and no anchors support adding them.
	// - `seniority_gap`         Resume's experience level is materially off from
	//                           what the JD asks for (junior → director, or vice
	//                           versa).
	// - `industry_mismatch`     Resume's occupation graph and the JD's occupation
	//                           don't overlap (nurse vs. backend engineer).
	// - `insufficient_evidence` Resume itself is too thin (empty descriptions,
	//                           no experiences) for any meaningful matching.
	Primary NoFitReasonPrimary `json:"primary"`
}

// NoFitReasonPrimary - `skills_gap`            JD's required skills aren't present in the resume
//
//		and no anchors support adding them.
//	  - `seniority_gap`         Resume's experience level is materially off from
//	    what the JD asks for (junior → director, or vice
//	    versa).
//	  - `industry_mismatch`     Resume's occupation graph and the JD's occupation
//	    don't overlap (nurse vs. backend engineer).
//	  - `insufficient_evidence` Resume itself is too thin (empty descriptions,
//	    no experiences) for any meaningful matching.
type NoFitReasonPrimary string

// Requirement defines model for Requirement.
type Requirement struct {
	// Category Canonical category, classified by the model. This set is
	// deliberately industry-agnostic: a nurse's "patient handover" and
	// an engineer's "deploy to prod" both map to `responsibility`. A
	// welder's "MIG certification" and a lawyer's "bar admission" both
	// map to `qualification`. New categories require a contract bump,
	// not a code patch.
	Category   RequirementCategory `json:"category"`
	Confidence float32             `json:"confidence"`

	// Id Stable identifier scoped to a single TailorResponse. Suggestion
	// records targeting this requirement set `requirement_ref` to
	// this UUID. See Skill.id for the same scoping rule.
	Id          openapi_types.UUID `json:"id"`
	SourceQuote string             `json:"source_quote"`

	// Text The requirement span, verbatim from raw_text.
	Text string `json:"text"`
}

// RequirementCategory Canonical category, classified by the model. This set is
// deliberately industry-agnostic: a nurse's "patient handover" and
// an engineer's "deploy to prod" both map to `responsibility`. A
// welder's "MIG certification" and a lawyer's "bar admission" both
// map to `qualification`. New categories require a contract bump,
// not a code patch.
type RequirementCategory string

// ScoreBreakdown defines model for ScoreBreakdown.
type ScoreBreakdown struct {
	// AdjacentSkills Share covered by semantically-adjacent skills (embedding
	// similarity above the calibrated threshold). NEVER token overlap.
	AdjacentSkills float32 `json:"adjacent_skills"`

	// ExactSkills Share of required skills the resume already covers exactly.
	ExactSkills float32 `json:"exact_skills"`

	// SeniorityFit How well the resume's experience aligns with JobDescription.
	// seniority — calibrated against the eval set, not a hardcoded
	// ladder.
	SeniorityFit float32 `json:"seniority_fit"`
}

// Seniority defines model for Seniority.
type Seniority struct {
	// Confidence Model confidence in the `level` label.
	Confidence float32 `json:"confidence"`

	// Level Seniority bucket, classified by a multilingual model. `unknown`
	// when the model's confidence is below the configured floor — NEVER
	// inferred from years_min via a hardcoded ladder.
	Level SeniorityLevel `json:"level"`

	// YearsMax Maximum years asked for. 0 when none stated.
	YearsMax *int `json:"years_max,omitempty"`

	// YearsMin Minimum years-of-experience asked for, extracted via locale-aware
	// structured extraction. 0 when none stated. Phrasing varies wildly
	// across locales ("3+ years", "Berufserfahrung von 3 Jahren",
	// "5 vuoden kokemus") — extraction is the model's job, not regex.
	YearsMin *int `json:"years_min,omitempty"`
}

// SeniorityLevel Seniority bucket, classified by a multilingual model. `unknown`
// when the model's confidence is below the configured floor — NEVER
// inferred from years_min via a hardcoded ladder.
type SeniorityLevel string

// Skill defines model for Skill.
type Skill struct {
	Confidence float32 `json:"confidence"`

	// EscoId ESCO concept URI when the multilingual ESCO linker matched this
	// skill. Empty when no link — scorer falls back to embedding
	// similarity, never to string matching.
	EscoId *string `json:"esco_id,omitempty"`

	// Id Stable identifier. The worker assigns a UUID at extraction time
	// so the orchestrator and the frontend can reference the same
	// Skill across the request → suggestion → fill round-trip. Suggestion
	// records targeting this skill set `requirement_ref` to this UUID.
	// Different worker calls on the same JD MAY produce different
	// UUIDs — IDs are scoped to a single TailorResponse, not stable
	// across calls.
	Id openapi_types.UUID `json:"id"`

	// Label Skill name as it appeared in the JD, in source language.
	Label string `json:"label"`

	// Normalized Canonical form for deduplication only. Produced by the model's
	// normalizer (lowercase + locale-aware diacritic handling). Not
	// used for semantic matching — that's embeddings' job.
	Normalized string `json:"normalized"`

	// Required Whether the JD treats this skill as required vs nice-to-have.
	// This is a span-classifier output across all 14 locales — NOT a
	// keyword scan over "required"/"must have"/"nice to have". When
	// the classifier's confidence is below the configured floor, the
	// worker omits the skill rather than defaulting to required.
	Required bool `json:"required"`

	// SourceQuote The original span the model attributed this skill to, verbatim
	// from raw_text. The frontend shows it as "from the JD: ...".
	SourceQuote string `json:"source_quote"`
}

// SkillTarget defines model for SkillTarget.
type SkillTarget struct {
	Scope SkillTargetScope `json:"scope"`

	// SectionIndex Index into `resume.sections[]`. The pointed-at section MUST be a
	// SkillsSection (`type: skills`). For `add_skill`, the new SkillItem
	// is appended to `items[]`.
	SectionIndex int `json:"section_index"`
}

// SkillTargetScope defines model for SkillTarget.Scope.
type SkillTargetScope string

// Suggestion defines model for Suggestion.
type Suggestion struct {
	Id openapi_types.UUID `json:"id"`

	// Instruction Locale-aware instruction the writer LLM uses to produce
	// proposed_text. Generated by the recommender, not free-form.
	Instruction string `json:"instruction"`

	// Kind What this suggestion does to the resume. Each kind has a matching
	// `target` shape (see SuggestionTarget) and a per-kind meaning for
	// `original_text`:
	//
	// - `rewrite_bullet`   Replace one `<li>` (or `<p>`) inside
	//                      `resume.sections[target.section_index].items[target.item_index].description`.
	//                      `original_text` is the verbatim HTML fragment
	//                      to find and replace.
	// - `add_bullet`       Append a new `<li>` to the same description.
	//                      `original_text` is the resume "anchor" — the
	//                      existing experience text the new bullet must
	//                      stay faithful to. The anchor is NOT in the
	//                      description being mutated; it's evidence from
	//                      elsewhere in the resume.
	// - `rewrite_summary`  Replace `resume.summary.value` entirely.
	//                      `original_text` is the current summary verbatim.
	// - `add_skill`        Append a SkillItem to a SkillsSection.
	//                      `original_text` is the bullet/text from the
	//                      resume that proves the user already has the
	//                      skill. Refused (no suggestion emitted) when
	//                      no anchor exists — the no-fabrication gate.
	//
	// Suggestions can be applied in any order. Frontend matches the
	// verbatim `original_text` substring on `rewrite_*` to stay robust
	// against user edits between fetch and accept; if not found, the
	// card goes stale-grayed in the UI.
	Kind SuggestionKind `json:"kind"`

	// OriginalText Per-kind semantics — see `kind`. Always shown to the user as proof
	// of grounding ("from your resume: ...").
	OriginalText string `json:"original_text"`

	// ProposedText Empty until the writer LLM is called for this suggestion (lazy
	// per-card via /v1/tailor/fill). Discarded suggestions stay empty
	// and cost zero LLM tokens.
	ProposedText *string `json:"proposed_text,omitempty"`

	// RequirementRef ID of the JobDescription requirement (or skill) this suggestion
	// addresses. Lets the frontend show "this card addresses THIS ask
	// from the JD" with the source_quote highlighted.
	RequirementRef string `json:"requirement_ref"`

	// Target Discriminated union pointing at the exact Resume object a Suggestion
	// mutates. `scope` matches the Suggestion.kind's natural target:
	//   rewrite_bullet, add_bullet  → BulletTarget   (scope=bullet)
	//   rewrite_summary             → SummaryTarget  (scope=summary)
	//   add_skill                   → SkillTarget    (scope=skill)
	Target SuggestionTarget `json:"target"`
}

// SuggestionKind What this suggestion does to the resume. Each kind has a matching
// `target` shape (see SuggestionTarget) and a per-kind meaning for
// `original_text`:
//
//   - `rewrite_bullet`   Replace one `<li>` (or `<p>`) inside
//     `resume.sections[target.section_index].items[target.item_index].description`.
//     `original_text` is the verbatim HTML fragment
//     to find and replace.
//   - `add_bullet`       Append a new `<li>` to the same description.
//     `original_text` is the resume "anchor" — the
//     existing experience text the new bullet must
//     stay faithful to. The anchor is NOT in the
//     description being mutated; it's evidence from
//     elsewhere in the resume.
//   - `rewrite_summary`  Replace `resume.summary.value` entirely.
//     `original_text` is the current summary verbatim.
//   - `add_skill`        Append a SkillItem to a SkillsSection.
//     `original_text` is the bullet/text from the
//     resume that proves the user already has the
//     skill. Refused (no suggestion emitted) when
//     no anchor exists — the no-fabrication gate.
//
// Suggestions can be applied in any order. Frontend matches the
// verbatim `original_text` substring on `rewrite_*` to stay robust
// against user edits between fetch and accept; if not found, the
// card goes stale-grayed in the UI.
type SuggestionKind string

// SuggestionTarget Discriminated union pointing at the exact Resume object a Suggestion
// mutates. `scope` matches the Suggestion.kind's natural target:
//
//	rewrite_bullet, add_bullet  → BulletTarget   (scope=bullet)
//	rewrite_summary             → SummaryTarget  (scope=summary)
//	add_skill                   → SkillTarget    (scope=skill)
type SuggestionTarget struct {
	union json.RawMessage
}

// SummaryTarget Targets `resume.summary.value`. No indices — there's exactly one summary.
type SummaryTarget struct {
	Scope SummaryTargetScope `json:"scope"`
}

// SummaryTargetScope defines model for SummaryTarget.Scope.
type SummaryTargetScope string

// TailorRequest defines model for TailorRequest.
type TailorRequest struct {
	// JobDescription Raw JD text. The worker parses it.
	JobDescription string              `json:"job_description"`
	Locale         TailorRequestLocale `json:"locale"`

	// Resume The full Resume DTO. ai-core consumes it typed and walks every
	// section, item, and description in order to produce Suggestions
	// with valid `target.section_index` / `target.item_index` indices
	// into THIS resume. The frontend must send the resume verbatim
	// (no stripping) so suggestions remain applicable.
	//
	// Consumers MUST import the typed Resume from
	// `@laddro-app/schemas/resume`:
	//   - TS:  `import type { components } from '@laddro-app/schemas/resume'`
	//          then `components['schemas']['Resume']`
	//   - Go:  `github.com/laddro-app/laddro-schemas/go/resume.Resume`
	//
	// The field is declared as `type: object` here only because OpenAPI
	// 3.1 cross-file `$ref` support is uneven across our codegen tools.
	// Treat it as `Resume` at every call site.
	Resume map[string]interface{} `json:"resume"`
}

// TailorRequestLocale defines model for TailorRequest.Locale.
type TailorRequestLocale string

// TailorResponse defines model for TailorResponse.
type TailorResponse struct {
	CompatibilityScore CompatibilityScore `json:"compatibility_score"`

	// FitVerdict Honest verdict on whether this resume can be tailored to this JD
	// at all. Derived from compatibility_score, the recommender's anchor
	// coverage (how many required skills have any resume evidence), and
	// the seniority gap.
	//
	// - `strong_fit`   normal stack, most requirements have anchors.
	// - `partial_fit`  normal stack, some gaps the user should know about.
	// - `weak_fit`     stack rendered with a banner: "low fit, consider
	//                  a different job — these are what we could find."
	// - `no_fit`       suggestions[] is empty by construction. Frontend
	//                  shows "this isn't your job — we don't fake resumes,
	//                  we prepare you for the job." Backed by no_fit_reason.
	//
	// ai-core owns the decision rule. Frontend branches UX off this enum
	// only — it never re-derives the verdict from the score.
	FitVerdict TailorResponseFitVerdict `json:"fit_verdict"`

	// NoFitReason Present when fit_verdict is `weak_fit` or `no_fit`. Machine-readable
	// primary cause + locale-aware human explanation the frontend can
	// surface verbatim.
	NoFitReason *NoFitReason   `json:"no_fit_reason,omitempty"`
	ParsedJob   JobDescription `json:"parsed_job"`
	Suggestions []Suggestion   `json:"suggestions"`
}

// TailorResponseFitVerdict Honest verdict on whether this resume can be tailored to this JD
// at all. Derived from compatibility_score, the recommender's anchor
// coverage (how many required skills have any resume evidence), and
// the seniority gap.
//
//   - `strong_fit`   normal stack, most requirements have anchors.
//   - `partial_fit`  normal stack, some gaps the user should know about.
//   - `weak_fit`     stack rendered with a banner: "low fit, consider
//     a different job — these are what we could find."
//   - `no_fit`       suggestions[] is empty by construction. Frontend
//     shows "this isn't your job — we don't fake resumes,
//     we prepare you for the job." Backed by no_fit_reason.
//
// ai-core owns the decision rule. Frontend branches UX off this enum
// only — it never re-derives the verdict from the score.
type TailorResponseFitVerdict string

// WorkerAnalyzeRequest defines model for WorkerAnalyzeRequest.
type WorkerAnalyzeRequest struct {
	Locale WorkerAnalyzeRequestLocale `json:"locale"`

	// Text Raw job description as the user pasted it.
	Text string `json:"text"`
}

// WorkerAnalyzeRequestLocale defines model for WorkerAnalyzeRequest.Locale.
type WorkerAnalyzeRequestLocale string

// WorkerAnalyzeResponse defines model for WorkerAnalyzeResponse.
type WorkerAnalyzeResponse = JobDescription

// AsBulletTarget returns the union data inside the SuggestionTarget as a BulletTarget
func (t SuggestionTarget) AsBulletTarget() (BulletTarget, error) {
	var body BulletTarget
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBulletTarget overwrites any union data inside the SuggestionTarget as the provided BulletTarget
func (t *SuggestionTarget) FromBulletTarget(v BulletTarget) error {
	v.Scope = "bullet"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBulletTarget performs a merge with any union data inside the SuggestionTarget, using the provided BulletTarget
func (t *SuggestionTarget) MergeBulletTarget(v BulletTarget) error {
	v.Scope = "bullet"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSummaryTarget returns the union data inside the SuggestionTarget as a SummaryTarget
func (t SuggestionTarget) AsSummaryTarget() (SummaryTarget, error) {
	var body SummaryTarget
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSummaryTarget overwrites any union data inside the SuggestionTarget as the provided SummaryTarget
func (t *SuggestionTarget) FromSummaryTarget(v SummaryTarget) error {
	v.Scope = "summary"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSummaryTarget performs a merge with any union data inside the SuggestionTarget, using the provided SummaryTarget
func (t *SuggestionTarget) MergeSummaryTarget(v SummaryTarget) error {
	v.Scope = "summary"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSkillTarget returns the union data inside the SuggestionTarget as a SkillTarget
func (t SuggestionTarget) AsSkillTarget() (SkillTarget, error) {
	var body SkillTarget
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSkillTarget overwrites any union data inside the SuggestionTarget as the provided SkillTarget
func (t *SuggestionTarget) FromSkillTarget(v SkillTarget) error {
	v.Scope = "skill"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSkillTarget performs a merge with any union data inside the SuggestionTarget, using the provided SkillTarget
func (t *SuggestionTarget) MergeSkillTarget(v SkillTarget) error {
	v.Scope = "skill"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SuggestionTarget) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"scope"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SuggestionTarget) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "bullet":
		return t.AsBulletTarget()
	case "skill":
		return t.AsSkillTarget()
	case "summary":
		return t.AsSummaryTarget()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SuggestionTarget) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SuggestionTarget) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
