// Package skills provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package skills

import (
	"time"
)

// Defines values for SkillsSuggestRequestLocale.
const (
	Da SkillsSuggestRequestLocale = "da"
	De SkillsSuggestRequestLocale = "de"
	En SkillsSuggestRequestLocale = "en"
	Es SkillsSuggestRequestLocale = "es"
	Et SkillsSuggestRequestLocale = "et"
	Fi SkillsSuggestRequestLocale = "fi"
	Fr SkillsSuggestRequestLocale = "fr"
	Is SkillsSuggestRequestLocale = "is"
	It SkillsSuggestRequestLocale = "it"
	Nl SkillsSuggestRequestLocale = "nl"
	No SkillsSuggestRequestLocale = "no"
	Pl SkillsSuggestRequestLocale = "pl"
	Pt SkillsSuggestRequestLocale = "pt"
	Sv SkillsSuggestRequestLocale = "sv"
)

// Valid indicates whether the value is a known member of the SkillsSuggestRequestLocale enum.
func (e SkillsSuggestRequestLocale) Valid() bool {
	switch e {
	case Da:
		return true
	case De:
		return true
	case En:
		return true
	case Es:
		return true
	case Et:
		return true
	case Fi:
		return true
	case Fr:
		return true
	case Is:
		return true
	case It:
		return true
	case Nl:
		return true
	case No:
		return true
	case Pl:
		return true
	case Pt:
		return true
	case Sv:
		return true
	default:
		return false
	}
}

// Defines values for SkillsSuggestResponseSource.
const (
	Embedding            SkillsSuggestResponseSource = "embedding"
	EmbeddingCrowdsource SkillsSuggestResponseSource = "embedding+crowdsource"
	LlmFallback          SkillsSuggestResponseSource = "llm_fallback"
)

// Valid indicates whether the value is a known member of the SkillsSuggestResponseSource enum.
func (e SkillsSuggestResponseSource) Valid() bool {
	switch e {
	case Embedding:
		return true
	case EmbeddingCrowdsource:
		return true
	case LlmFallback:
		return true
	default:
		return false
	}
}

// ResumeSkillSuggestions Persisted per-resume state. Inlined into `getResumeById` so the
// frontend can render the first 5 chips with zero API calls on every
// return visit. Updated whenever ai-core returns a fresh batch.
type ResumeSkillSuggestions struct {
	// BucketId The bucket the classifier put this resume into. Cached so we never
	// re-run the classifier just to refill a chip. If the resume changes
	// shape enough that the classifier would route it elsewhere, we
	// recompute on the next first-paint suggest.
	BucketId string `json:"bucketId"`

	// Displayed The skill names currently visible on chips (length <= 5).
	Displayed []string `json:"displayed"`

	// Excluded Cumulative blocklist of everything ever shown on a chip for this
	// resume, regardless of whether the user picked or skipped. Keeps
	// us from re-suggesting a skill the user has already seen.
	Excluded  []string  `json:"excluded"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SkillsGenerationUsage Per-call usage block. On the embedding path token counts are zero and
// `model` is the sentence-transformer id (e.g. `sentence-transformers/
// paraphrase-multilingual-mpnet-base-v2`). On the LLM-fallback path
// token counts reflect the small prompt and `model` is the LLM that
// produced the completion.
type SkillsGenerationUsage struct {
	Model        string `json:"model"`
	OutputTokens *int   `json:"outputTokens,omitempty"`
	PromptTokens *int   `json:"promptTokens,omitempty"`
}

// SkillsSuggestRequest Request body for `POST /v1/skills/suggest` on laddro-ai-core (and the
// matching `POST /api/skills/suggest` on laddro-backend, which forwards
// the same envelope after persisting the pick side-effect).
type SkillsSuggestRequest struct {
	// Exclude Skills currently visible on chips but not picked. ai-core never
	// returns these even if they outrank everything else — protects the
	// "remove one chip, refill one chip, other four stay put" UX.
	Exclude []string `json:"exclude"`

	// ExistingSkills Skills already on the resume. Filtered out of the candidate pool
	// and also concatenated into the profile vector so the matcher
	// reads the direction the user is committing to.
	ExistingSkills []string `json:"existingSkills"`

	// JobDescription Optional. When the user is in a tailor flow we pass the JD so the
	// profile vector skews toward the role they're targeting rather than
	// their resume baseline. Omitted on the standalone build-resume page.
	JobDescription *string `json:"jobDescription,omitempty"`

	// Limit How many fresh skills to return. Initial first-paint suggest is 5;
	// chip-refill calls send 1.
	Limit int `json:"limit"`

	// Locale Drives which locale-labelled skill names ai-core returns AND which
	// slice of `skill_selections` (bucket_id, skill, locale) drives the
	// crowdsource boost. No English fallback labels — if a skill has no
	// label in this locale we surface the next best skill that does.
	Locale SkillsSuggestRequestLocale `json:"locale"`

	// PickedSkill Set by laddro-backend when this request was triggered by a user
	// tapping a chip. Backend uses it to increment
	// `skill_selections.(bucket_id, pickedSkill, locale).count` before
	// forwarding to ai-core. ai-core ignores this field — the picked
	// skill will already be reflected in `existingSkills`.
	PickedSkill *string `json:"pickedSkill,omitempty"`

	// Resume The candidate's V1 Resume. The classifier reads `personal.role`,
	// recent `employments[*].position`, and the latest employment
	// description to build the bucket id and profile vector. The
	// employer domain (when present) seeds the industry hint.
	Resume map[string]interface{} `json:"resume"`
}

// SkillsSuggestRequestLocale Drives which locale-labelled skill names ai-core returns AND which
// slice of `skill_selections` (bucket_id, skill, locale) drives the
// crowdsource boost. No English fallback labels — if a skill has no
// label in this locale we surface the next best skill that does.
type SkillsSuggestRequestLocale string

// SkillsSuggestResponse Result of a `POST /v1/skills/suggest` call. Returns up to `limit`
// skills, all of which are absent from `existingSkills` and `exclude`.
type SkillsSuggestResponse struct {
	Skills []SuggestedSkill `json:"skills"`

	// Source Which path produced this batch. `embedding` = pure cosine match,
	// no crowdsource signal had any influence on the top results.
	// `embedding+crowdsource` = at least one returned skill was boosted
	// past a rival by `skill_selections` counts. `llm_fallback` = the
	// embedding pool didn't produce enough above-threshold candidates
	// and we called the LLM to complete the batch. Logged for telemetry,
	// not user-visible.
	Source SkillsSuggestResponseSource `json:"source"`

	// Usage Per-call usage block. On the embedding path token counts are zero and
	// `model` is the sentence-transformer id (e.g. `sentence-transformers/
	// paraphrase-multilingual-mpnet-base-v2`). On the LLM-fallback path
	// token counts reflect the small prompt and `model` is the LLM that
	// produced the completion.
	Usage *SkillsGenerationUsage `json:"usage,omitempty"`
}

// SkillsSuggestResponseSource Which path produced this batch. `embedding` = pure cosine match,
// no crowdsource signal had any influence on the top results.
// `embedding+crowdsource` = at least one returned skill was boosted
// past a rival by `skill_selections` counts. `llm_fallback` = the
// embedding pool didn't produce enough above-threshold candidates
// and we called the LLM to complete the batch. Logged for telemetry,
// not user-visible.
type SkillsSuggestResponseSource string

// SuggestedSkill defines model for SuggestedSkill.
type SuggestedSkill struct {
	// Name Locale-labelled skill name. This is the literal string we put on
	// the chip and append to `resume.skills` if the user picks it.
	Name string `json:"name"`
}
