// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterPersonalDetails

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

@Serializable
data class CoverLetterPersonalDetails(
    val fullName: String,
    val jobTitle: String? = null,
    val address: String? = null,
    val email: String? = null,
    val phone: String? = null,
)
