// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetter

package com.laddro.schemas.coverletter

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CoverLetter(
    val id: String? = null,
    val title: String,
    val locale: CoverLetterLocale,
    /**
     * Slug from the cover-letter template catalog. Defaults to `emerald`
     * when omitted.
     */
    val templateId: String? = "emerald",
    val content: CoverLetterContent,
    val styling: CoverLetterStyling? = null,
    val completeness: Int? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
)

@Serializable
enum class CoverLetterLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
