// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterPersonalDetailsPartial

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

/**
 * Same fields as `CoverLetterPersonalDetails` but every field is
 * optional. Used in `CoverLetterGenerateRequest.initialContent` so
 * the caller can submit whatever it already has (or nothing) and let
 * ai-core fill the gaps from the resume.
 */
@Serializable
data class CoverLetterPersonalDetailsPartial(
    val fullName: String? = null,
    val jobTitle: String? = null,
    val address: String? = null,
    val email: String? = null,
    val phone: String? = null,
)
