// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterStyling

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

/**
 * Cover letter visual settings. All fields optional — template defaults
 * apply when omitted.
 */
@Serializable
data class CoverLetterStyling(
    val colors: TemplateColors? = null,
    /**
     * DEPRECATED as an input, still written for backwards compatibility.
     * Readers MUST prefer `colors`; see the note on
     * `resume.v1.yaml#/components/schemas/Styling/properties/color`.
     */
    val color: String? = null,
    val font: String? = null,
    val fontSize: Int? = null,
    val margin: Double? = null,
    val lineHeight: Double? = null,
)
