// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterGenerateRequest

package com.laddro.schemas.coverletter

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * Request body for `POST /v1/cover-letter` on laddro-ai-core.
 *
 * `initialContent` is a possibly-partial envelope — the caller passes
 * whatever it already has from the user (the standalone CL page often
 * has everything; the tailor flow usually has only company name on
 * `employerDetails`). ai-core fills empty personal fields from the
 * resume verbatim and runs a narrow LLM extract on the JD for empty
 * employer fields. Always-overwritten: `letterContent` is generated.
 */
@Serializable
data class CoverLetterGenerateRequest(
    /**
     * Partial content envelope. Every nested field is optional. ai-core
     * echoes what's provided and fills only the empties.
     */
    val initialContent: CoverLetterGenerateRequestInitialContent? = null,
    /**
     * The candidate's V1 Resume. Used both as the source for personal
     * field fills (firstName, lastName, email, phone, city/country)
     * and as the evidence the body writer cites in the experience
     * paragraph. Required because we cannot write a believable letter
     * without grounding.
     */
    val resume: JsonObject,
    /**
     * Raw job description text the user submitted. Used by the employer
     * extractor (only when companyName / hiringManagerName are absent)
     * and by the body writer to ground the experience paragraph.
     */
    val jobDescription: String,
    /**
     * Position name. Tailor flow always passes this from the form. The
     * standalone page may omit it; ai-core falls back to
     * `resume.personal.role` when this is absent AND the user did not
     * fill `personalDetails.jobTitle`.
     */
    val positionName: String? = null,
    /**
     * BCP-47-ish locale code. Drives salutation + closing template
     * selection AND the body writer's output language. Every word of
     * the returned letter is in this language — no English fallback
     * phrases sneak in.
     */
    val locale: CoverLetterGenerateRequestLocale,
    /**
     * Voice for the body writer. `professional` is the default formal
     * register most industries expect. `enthusiastic` leans warmer for
     * startups / creative roles. `concise` produces tighter
     * paragraphs for senior-IC roles that want signal over fluff.
     */
    val tone: CoverLetterGenerateRequestTone? = CoverLetterGenerateRequestTone.PROFESSIONAL,
)

/**
 * Partial content envelope. Every nested field is optional. ai-core
 * echoes what's provided and fills only the empties.
 */
@Serializable
data class CoverLetterGenerateRequestInitialContent(
    val personalDetails: CoverLetterPersonalDetailsPartial? = null,
    val employerDetails: CoverLetterEmployerDetails? = null,
)

/**
 * BCP-47-ish locale code. Drives salutation + closing template
 * selection AND the body writer's output language. Every word of
 * the returned letter is in this language — no English fallback
 * phrases sneak in.
 */
@Serializable
enum class CoverLetterGenerateRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}

/**
 * Voice for the body writer. `professional` is the default formal
 * register most industries expect. `enthusiastic` leans warmer for
 * startups / creative roles. `concise` produces tighter
 * paragraphs for senior-IC roles that want signal over fluff.
 */
@Serializable
enum class CoverLetterGenerateRequestTone {
    @SerialName("professional") PROFESSIONAL,
    @SerialName("enthusiastic") ENTHUSIASTIC,
    @SerialName("concise") CONCISE,
}
