// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterEmployerDetails

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

@Serializable
data class CoverLetterEmployerDetails(
    val companyName: String? = null,
    val hiringManagerName: String? = null,
)
