// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterGenerateResponse

package com.laddro.schemas.coverletter

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Result of a `POST /v1/cover-letter` call. `content` is the existing
 * `CoverLetterContent` shape — same envelope the editor and the
 * renderer already consume — so the response is drop-in for both the
 * standalone page (which then opens the editor) and the tailor worker
 * (which persists it into the reserved CL UUID slot).
 */
@Serializable
data class CoverLetterGenerateResponse(
    val content: CoverLetterContent,
    /**
     * Which fields ai-core synthesized vs echoed from the request.
     * Lets the standalone CL editor render a subtle "AI filled this"
     * badge so the user knows which fields to double-check. Empty
     * arrays mean the caller provided every field verbatim.
     */
    val filled: CoverLetterGenerateResponseFilled,
    val usage: GenerationUsage,
)

@Serializable
enum class CoverLetterGenerateResponseFilledPersonalDetails {
    @SerialName("fullName") FULL_NAME,
    @SerialName("jobTitle") JOB_TITLE,
    @SerialName("address") ADDRESS,
    @SerialName("email") EMAIL,
    @SerialName("phone") PHONE,
}

@Serializable
enum class CoverLetterGenerateResponseFilledEmployerDetails {
    @SerialName("companyName") COMPANY_NAME,
    @SerialName("hiringManagerName") HIRING_MANAGER_NAME,
}

/**
 * Which fields ai-core synthesized vs echoed from the request.
 * Lets the standalone CL editor render a subtle "AI filled this"
 * badge so the user knows which fields to double-check. Empty
 * arrays mean the caller provided every field verbatim.
 */
@Serializable
data class CoverLetterGenerateResponseFilled(
    val personalDetails: List<CoverLetterGenerateResponseFilledPersonalDetails>,
    val employerDetails: List<CoverLetterGenerateResponseFilledEmployerDetails>,
)
