// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.CoverLetterContent

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

@Serializable
data class CoverLetterContent(
    val personalDetails: CoverLetterPersonalDetails,
    val employerDetails: CoverLetterEmployerDetails,
    /**
     * Body of the letter. HTML allowed (paragraphs and lists).
     */
    val letterContent: String,
)
