// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.GenerationUsage

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

/**
 * Per-call usage block returned by ai-core for any LLM-backed endpoint.
 * Centralised in the cover-letter spec because that's the first place
 * we need it; the tailor spec will reuse this shape once the same
 * accounting is added to `/v1/tailor`.
 */
@Serializable
data class GenerationUsage(
    /**
     * Sum of input tokens across the extractor + writer calls.
     */
    val promptTokens: Int,
    /**
     * Sum of output tokens across the extractor + writer calls.
     */
    val outputTokens: Int,
    /**
     * Provider + model that produced the body (`gemini-2.5-flash` /
     * `gpt-4.1-mini` / `claude-sonnet-4-6` / ...). Reflects the writer
     * call only — the extractor reports separately when needed.
     */
    val model: String,
)
