// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: cover-letter/cover-letter.v1.yaml -> components.schemas.TemplateColors

package com.laddro.schemas.coverletter

import kotlinx.serialization.Serializable

/**
 * A complete template colour palette — the five slots every template
 * renders. One row of a cover-letter template's `availableColors` in the
 * renderer catalog, stored verbatim so the choice round-trips exactly.
 *
 * Duplicated from `resume.v1.yaml` rather than referenced: each spec is
 * generated independently (see `scripts/generate-ts.sh`), so a cross-file
 * `$ref` would not resolve. Keep the two definitions identical.
 *
 * All five are REQUIRED when the object is present — present means
 * complete. Omit the whole object to accept the template's default
 * palette.
 */
@Serializable
data class TemplateColors(
    val backgroundColor: String,
    val backgroundPartColor: String,
    val underlineColor: String,
    val text: String,
    val textMuted: String,
)
