// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: bullets/bullets.v1.yaml -> components.schemas.BulletsWorkerRequest

package com.laddro.schemas.bullets

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Backend → ai-core wire body for `POST /v1/bullets/suggest`. Backend
 * has the DB and the user session, so it pre-extracts every field the
 * worker needs to fill auto-placeholders. ai-core stays stateless and
 * the worker never queries Postgres.
 *
 * The per-section context fields below are populated only when relevant
 * to `section`. The worker reads only the ones its template references
 * — sending an unused field is a no-op, not an error.
 */
@Serializable
data class BulletsWorkerRequest(
    val section: BulletSection,
    val locale: BulletsWorkerRequestLocale,
    /**
     * Up to ~5 skill names from the resume. Joined locale-aware by the
     * worker to fill the `[STACK]` placeholder. Used by every section
     * that references `[STACK]` (employment, projects, custom).
     */
    val existingSkills: List<String>? = null,
    /**
     * Fills `[ROLE]`. Source per section:
     * - employment: employment item's `position`
     * - extra_curricular: extra-curricular item's `role`
     * - other sections: empty string
     */
    val role: String? = null,
    /**
     * Fills `[COMPANY]`. Sourced from the employment item's `company`.
     * Empty for non-employment sections.
     */
    val company: String? = null,
    /**
     * Fills `[PROJECT_NAME]`. Sourced from the project item's `title`.
     * Empty for non-project sections.
     */
    val projectName: String? = null,
    /**
     * Fills `[FIELD]`. Sourced from the education item's `field`.
     * Empty for non-education sections.
     */
    val educationField: String? = null,
    /**
     * Fills `[SCHOOL]`. Sourced from the education item's `institution`.
     * Empty for non-education sections.
     */
    val school: String? = null,
    /**
     * Fills `[ORG]`. Sourced from the extra-curricular item's
     * `organization`. Empty for other sections.
     */
    val organization: String? = null,
    /**
     * Raw template strings to suppress. Forwarded verbatim.
     */
    val exclude: List<String>? = null,
    val limit: Int,
)

@Serializable
enum class BulletsWorkerRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
