// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: bullets/bullets.v1.yaml -> components.schemas.BulletsSuggestRequest

package com.laddro.schemas.bullets

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Public envelope: `POST /api/bullets/suggest` body (web → backend).
 * Backend looks up the resume, walks to the section item the matching
 * `*ItemId` field points at, extracts context, then forwards a
 * `BulletsWorkerRequest` to ai-core. Exactly one of the five item-id
 * fields must be present and it must match `section`.
 */
@Serializable
data class BulletsSuggestRequest(
    /**
     * Resume id the bullets belong to.
     */
    val resumeId: String,
    val section: BulletSection,
    /**
     * Required when `section = employment`. Id of the employment item
     * the chip strip will render under.
     */
    val employmentItemId: String? = null,
    /**
     * Required when `section = projects`.
     */
    val projectItemId: String? = null,
    /**
     * Required when `section = education`.
     */
    val educationItemId: String? = null,
    /**
     * Required when `section = extra_curricular`.
     */
    val extraCurricularItemId: String? = null,
    /**
     * Required when `section = custom`.
     */
    val customItemId: String? = null,
    /**
     * Drives which `<bucket>_<locale>.json` cell the worker loads. No
     * English fallback — if the locale × section cell is empty, the
     * response returns zero templates and the frontend renders nothing.
     */
    val locale: BulletsSuggestRequestLocale,
    /**
     * Raw template strings currently visible on the chip strip — the
     * worker never re-suggests these even if they outrank everything
     * else. Protects the "remove one chip, refill one chip, others
     * stay put" UX.
     */
    val exclude: List<String>? = null,
    /**
     * How many fresh templates to return. First paint sends 5; chip
     * refill sends 1.
     */
    val limit: Int,
)

/**
 * Drives which `<bucket>_<locale>.json` cell the worker loads. No
 * English fallback — if the locale × section cell is empty, the
 * response returns zero templates and the frontend renders nothing.
 */
@Serializable
enum class BulletsSuggestRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
