// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: bullets/bullets.v1.yaml -> components.schemas.BulletsSuggestResponse

package com.laddro.schemas.bullets

import kotlinx.serialization.Serializable

/**
 * Response from ai-core for `POST /v1/bullets/suggest`. Backend
 * forwards this verbatim to the frontend on `POST /api/bullets/suggest`.
 *
 * Two parallel arrays of equal length:
 * - `bullets` — templates after auto-placeholder substitution. User-fill
 *   placeholders ([METRIC], [X%], etc.) remain in the string and the
 *   frontend renders them as editable spans.
 * - `rawTemplates` — the original template strings before substitution.
 *   The frontend uses these as stable identifiers for the `exclude`
 *   list (substituted strings change as resume context changes).
 */
@Serializable
data class BulletsSuggestResponse(
    /**
     * Length 0..limit. Empty array means the locale × section cell has
     * no templates yet — frontend renders nothing (no English fallback).
     */
    val bullets: List<String>,
    /**
     * Same length as `bullets`. Indexed pair: `rawTemplates[i]` is the
     * unsubstituted source of `bullets[i]`.
     */
    val rawTemplates: List<String>,
)
