// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: bullets/bullets.v1.yaml -> components.schemas.BulletSection

package com.laddro.schemas.bullets

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Which resume section the chip strip is rendering under. Drives:
 * - which `<section>/` subdirectory of the template bank the worker reads
 * - which item-id field on the request the backend honors
 * - which auto-fill placeholders the worker substitutes
 */
@Serializable
enum class BulletSection {
    @SerialName("employment") EMPLOYMENT,
    @SerialName("projects") PROJECTS,
    @SerialName("education") EDUCATION,
    @SerialName("extra_curricular") EXTRA_CURRICULAR,
    @SerialName("custom") CUSTOM,
}
