// Package content provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package content

// Defines values for ContentImproveRequestLocale.
const (
	ContentImproveRequestLocaleCs ContentImproveRequestLocale = "cs"
	ContentImproveRequestLocaleDa ContentImproveRequestLocale = "da"
	ContentImproveRequestLocaleDe ContentImproveRequestLocale = "de"
	ContentImproveRequestLocaleEn ContentImproveRequestLocale = "en"
	ContentImproveRequestLocaleEs ContentImproveRequestLocale = "es"
	ContentImproveRequestLocaleEt ContentImproveRequestLocale = "et"
	ContentImproveRequestLocaleFi ContentImproveRequestLocale = "fi"
	ContentImproveRequestLocaleFr ContentImproveRequestLocale = "fr"
	ContentImproveRequestLocaleHu ContentImproveRequestLocale = "hu"
	ContentImproveRequestLocaleIs ContentImproveRequestLocale = "is"
	ContentImproveRequestLocaleIt ContentImproveRequestLocale = "it"
	ContentImproveRequestLocaleLt ContentImproveRequestLocale = "lt"
	ContentImproveRequestLocaleLv ContentImproveRequestLocale = "lv"
	ContentImproveRequestLocaleNl ContentImproveRequestLocale = "nl"
	ContentImproveRequestLocaleNo ContentImproveRequestLocale = "no"
	ContentImproveRequestLocalePl ContentImproveRequestLocale = "pl"
	ContentImproveRequestLocalePt ContentImproveRequestLocale = "pt"
	ContentImproveRequestLocaleRo ContentImproveRequestLocale = "ro"
	ContentImproveRequestLocaleSk ContentImproveRequestLocale = "sk"
	ContentImproveRequestLocaleSv ContentImproveRequestLocale = "sv"
	ContentImproveRequestLocaleUk ContentImproveRequestLocale = "uk"
)

// Valid indicates whether the value is a known member of the ContentImproveRequestLocale enum.
func (e ContentImproveRequestLocale) Valid() bool {
	switch e {
	case ContentImproveRequestLocaleCs:
		return true
	case ContentImproveRequestLocaleDa:
		return true
	case ContentImproveRequestLocaleDe:
		return true
	case ContentImproveRequestLocaleEn:
		return true
	case ContentImproveRequestLocaleEs:
		return true
	case ContentImproveRequestLocaleEt:
		return true
	case ContentImproveRequestLocaleFi:
		return true
	case ContentImproveRequestLocaleFr:
		return true
	case ContentImproveRequestLocaleHu:
		return true
	case ContentImproveRequestLocaleIs:
		return true
	case ContentImproveRequestLocaleIt:
		return true
	case ContentImproveRequestLocaleLt:
		return true
	case ContentImproveRequestLocaleLv:
		return true
	case ContentImproveRequestLocaleNl:
		return true
	case ContentImproveRequestLocaleNo:
		return true
	case ContentImproveRequestLocalePl:
		return true
	case ContentImproveRequestLocalePt:
		return true
	case ContentImproveRequestLocaleRo:
		return true
	case ContentImproveRequestLocaleSk:
		return true
	case ContentImproveRequestLocaleSv:
		return true
	case ContentImproveRequestLocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for ContentImproveSource.
const (
	ContentImproveSourceCache            ContentImproveSource = "cache"
	ContentImproveSourceGemini           ContentImproveSource = "gemini"
	ContentImproveSourceNoChangeNeeded   ContentImproveSource = "no_change_needed"
	ContentImproveSourceRejectedScorer   ContentImproveSource = "rejected_scorer"
	ContentImproveSourceRejectedVerifier ContentImproveSource = "rejected_verifier"
	ContentImproveSourceTooShort         ContentImproveSource = "too_short"
)

// Valid indicates whether the value is a known member of the ContentImproveSource enum.
func (e ContentImproveSource) Valid() bool {
	switch e {
	case ContentImproveSourceCache:
		return true
	case ContentImproveSourceGemini:
		return true
	case ContentImproveSourceNoChangeNeeded:
		return true
	case ContentImproveSourceRejectedScorer:
		return true
	case ContentImproveSourceRejectedVerifier:
		return true
	case ContentImproveSourceTooShort:
		return true
	default:
		return false
	}
}

// Defines values for ContentScoreRequestLocale.
const (
	ContentScoreRequestLocaleCs ContentScoreRequestLocale = "cs"
	ContentScoreRequestLocaleDa ContentScoreRequestLocale = "da"
	ContentScoreRequestLocaleDe ContentScoreRequestLocale = "de"
	ContentScoreRequestLocaleEn ContentScoreRequestLocale = "en"
	ContentScoreRequestLocaleEs ContentScoreRequestLocale = "es"
	ContentScoreRequestLocaleEt ContentScoreRequestLocale = "et"
	ContentScoreRequestLocaleFi ContentScoreRequestLocale = "fi"
	ContentScoreRequestLocaleFr ContentScoreRequestLocale = "fr"
	ContentScoreRequestLocaleHu ContentScoreRequestLocale = "hu"
	ContentScoreRequestLocaleIs ContentScoreRequestLocale = "is"
	ContentScoreRequestLocaleIt ContentScoreRequestLocale = "it"
	ContentScoreRequestLocaleLt ContentScoreRequestLocale = "lt"
	ContentScoreRequestLocaleLv ContentScoreRequestLocale = "lv"
	ContentScoreRequestLocaleNl ContentScoreRequestLocale = "nl"
	ContentScoreRequestLocaleNo ContentScoreRequestLocale = "no"
	ContentScoreRequestLocalePl ContentScoreRequestLocale = "pl"
	ContentScoreRequestLocalePt ContentScoreRequestLocale = "pt"
	ContentScoreRequestLocaleRo ContentScoreRequestLocale = "ro"
	ContentScoreRequestLocaleSk ContentScoreRequestLocale = "sk"
	ContentScoreRequestLocaleSv ContentScoreRequestLocale = "sv"
	ContentScoreRequestLocaleUk ContentScoreRequestLocale = "uk"
)

// Valid indicates whether the value is a known member of the ContentScoreRequestLocale enum.
func (e ContentScoreRequestLocale) Valid() bool {
	switch e {
	case ContentScoreRequestLocaleCs:
		return true
	case ContentScoreRequestLocaleDa:
		return true
	case ContentScoreRequestLocaleDe:
		return true
	case ContentScoreRequestLocaleEn:
		return true
	case ContentScoreRequestLocaleEs:
		return true
	case ContentScoreRequestLocaleEt:
		return true
	case ContentScoreRequestLocaleFi:
		return true
	case ContentScoreRequestLocaleFr:
		return true
	case ContentScoreRequestLocaleHu:
		return true
	case ContentScoreRequestLocaleIs:
		return true
	case ContentScoreRequestLocaleIt:
		return true
	case ContentScoreRequestLocaleLt:
		return true
	case ContentScoreRequestLocaleLv:
		return true
	case ContentScoreRequestLocaleNl:
		return true
	case ContentScoreRequestLocaleNo:
		return true
	case ContentScoreRequestLocalePl:
		return true
	case ContentScoreRequestLocalePt:
		return true
	case ContentScoreRequestLocaleRo:
		return true
	case ContentScoreRequestLocaleSk:
		return true
	case ContentScoreRequestLocaleSv:
		return true
	case ContentScoreRequestLocaleUk:
		return true
	default:
		return false
	}
}

// Defines values for ContentWeakness.
const (
	ContentWeaknessFirstPerson ContentWeakness = "first_person"
	ContentWeaknessNoMetric    ContentWeakness = "no_metric"
	ContentWeaknessNoOutcome   ContentWeakness = "no_outcome"
	ContentWeaknessTooLong     ContentWeakness = "too_long"
	ContentWeaknessTooShort    ContentWeakness = "too_short"
	ContentWeaknessVagueFiller ContentWeakness = "vague_filler"
	ContentWeaknessWeakVerb    ContentWeakness = "weak_verb"
)

// Valid indicates whether the value is a known member of the ContentWeakness enum.
func (e ContentWeakness) Valid() bool {
	switch e {
	case ContentWeaknessFirstPerson:
		return true
	case ContentWeaknessNoMetric:
		return true
	case ContentWeaknessNoOutcome:
		return true
	case ContentWeaknessTooLong:
		return true
	case ContentWeaknessTooShort:
		return true
	case ContentWeaknessVagueFiller:
		return true
	case ContentWeaknessWeakVerb:
		return true
	default:
		return false
	}
}

// ContentGenerationUsage Per-call usage block. On `cache` / `no_change_needed` / `too_short`,
// token counts are zero and `model` is the empty string. On the Gemini
// path, counts include BOTH the rewrite call and the verifier call so
// downstream cost accounting is honest.
type ContentGenerationUsage struct {
	Model        string `json:"model"`
	OutputTokens *int   `json:"outputTokens,omitempty"`
	PromptTokens *int   `json:"promptTokens,omitempty"`
}

// ContentImproveRequest Request body for `POST /v1/content/improve` on laddro-ai-core (and the
// matching `POST /api/content/improve` on laddro-backend, which forwards
// the same envelope after loading the resume + crowdsource slice).
//
// The contract is intentionally narrow: backend has the DB and the user
// session, so it knows the role / company / other bullets / top skills
// of the item the user is editing. Shipping them directly keeps the
// ai-core surface stateless and the LLM brief honest — every field here
// lands in the prompt, nothing else does. The full resume is never
// sent to ai-core for improve (it would just inflate the request and
// risk Gemini drifting into unrelated sections).
type ContentImproveRequest struct {
	// BucketId Cached bucket id from a previous skills-suggest response on the
	// same resume. When present, ai-core skips classifying. When absent,
	// ai-core classifies the bullet via the same nearest-centroid pass
	// and returns the chosen bucket in `bucketId` of the response.
	BucketId *string `json:"bucketId,omitempty"`

	// Company Employer name from the employment item. Used in the prompt for
	// anchoring; never echoed into the rewrite unless the original text
	// already mentions it.
	Company string `json:"company"`

	// CrowdsourceImprovements Top accepted improvement candidates for this
	// `(bucketId, weaknessPattern, locale)` slice, ranked by
	// `accepts - rejects`. Backend reads `improve_selections` and ships
	// the top ~10 per slice. ai-core checks if any candidate's
	// `inputPatternHash` matches the current input's shingled fingerprint
	// (k=3, MinHash, similarity >= 0.8); on hit it returns the candidate
	// output with `source: cache` and zero LLM cost.
	CrowdsourceImprovements *[]CrowdsourcedImprovement `json:"crowdsourceImprovements,omitempty"`

	// ExistingSkills Up to 5 skill names from the candidate's resume. Used to anchor
	// Gemini's stack choice — "preserve {existingSkills}; don't swap for
	// adjacent tech." Without this anchor the model will happily swap
	// Postgres for MySQL or React for Vue. Backend caps at 5.
	ExistingSkills *[]string `json:"existingSkills,omitempty"`

	// Locale Drives prompt language for Gemini and which slice of
	// `improve_selections` is consulted for the cache hit. No English
	// fallback — if the user's bullet is German, the rewrite is German.
	Locale ContentImproveRequestLocale `json:"locale"`

	// OtherBullets Up to 3 other description bullets from the same employment item,
	// excluding the one being improved. Used as a non-repetition signal
	// in the prompt so Gemini doesn't propose a rewrite that duplicates
	// another bullet on the same role. Backend caps at 3 — sending more
	// inflates the brief without changing model behaviour.
	OtherBullets *[]string `json:"otherBullets,omitempty"`

	// Role Position title from the employment item the bullet belongs to.
	// E.g. "Senior Backend Engineer". Used in the prompt to anchor the
	// rewrite ("for {role} at {company}") and as a signal to the
	// seniority detector when bucketId is absent.
	Role string `json:"role"`

	// Text The current bullet text the user wants to improve. Passed verbatim
	// to the local scorer and (if the input gate passes) into the Gemini
	// prompt as `Original:`.
	Text string `json:"text"`
}

// ContentImproveRequestLocale Drives prompt language for Gemini and which slice of
// `improve_selections` is consulted for the cache hit. No English
// fallback — if the user's bullet is German, the rewrite is German.
type ContentImproveRequestLocale string

// ContentImproveResponse Result of a `POST /v1/content/improve` call. `text` is omitted on the
// no-change-needed / rejected paths so the frontend can render the
// right state without a sentinel string. `source` always reports which
// path produced the response, for observability.
type ContentImproveResponse struct {
	// BucketId Bucket id ai-core used — either passed in by the caller (verbatim)
	// or classified locally when the request omitted it. Backend
	// persists this on the content_improvements row.
	BucketId *string `json:"bucketId,omitempty"`

	// Score Composite 0–100 score the local scorer assigned to the INPUT.
	// Useful for the visibility gate on the ✨ button (frontend hides
	// the button when score >= 85).
	Score *int `json:"score,omitempty"`

	// Source Which path produced this response.
	// - `no_change_needed` — input scored >= 85, no LLM call, no rewrite.
	// - `too_short` — input under 5 tokens, refused. Improve and write-for-me
	//   are conceptually different; we don't silently switch lanes.
	// - `cache` — a `crowdsourceImprovements` candidate matched the input
	//   fingerprint above the Jaccard threshold; that candidate is returned.
	//   Zero LLM cost.
	// - `gemini` — input had fixable weaknesses, cache miss, Gemini Flash 2.5
	//   produced a rewrite that passed BOTH the scorer gate (new score >
	//   old score) AND the verifier gate (no fabricated numbers).
	// - `rejected_scorer` — Gemini's rewrite did not improve the score.
	//   Returned with `text` omitted; frontend leaves the user's draft.
	// - `rejected_verifier` — Gemini's rewrite contained a number,
	//   percentage, or quantity not in the original. Hard reject.
	Source ContentImproveSource `json:"source"`

	// Text The rewritten bullet. Present only when `source` is `gemini` or
	// `cache`. Omitted (null) on `no_change_needed`, `rejected_scorer`,
	// `rejected_verifier`, and `too_short`.
	Text *string `json:"text,omitempty"`

	// Usage Per-call usage block. On `cache` / `no_change_needed` / `too_short`,
	// token counts are zero and `model` is the empty string. On the Gemini
	// path, counts include BOTH the rewrite call and the verifier call so
	// downstream cost accounting is honest.
	Usage ContentGenerationUsage `json:"usage"`

	// Weaknesses What the local scorer flagged on the input — surfaced even when
	// the LLM call is skipped so the frontend can show a "looks good"
	// or "too short to improve" message with detail.
	Weaknesses []ContentWeakness `json:"weaknesses"`
}

// ContentImproveSource Which path produced this response.
//   - `no_change_needed` — input scored >= 85, no LLM call, no rewrite.
//   - `too_short` — input under 5 tokens, refused. Improve and write-for-me
//     are conceptually different; we don't silently switch lanes.
//   - `cache` — a `crowdsourceImprovements` candidate matched the input
//     fingerprint above the Jaccard threshold; that candidate is returned.
//     Zero LLM cost.
//   - `gemini` — input had fixable weaknesses, cache miss, Gemini Flash 2.5
//     produced a rewrite that passed BOTH the scorer gate (new score >
//     old score) AND the verifier gate (no fabricated numbers).
//   - `rejected_scorer` — Gemini's rewrite did not improve the score.
//     Returned with `text` omitted; frontend leaves the user's draft.
//   - `rejected_verifier` — Gemini's rewrite contained a number,
//     percentage, or quantity not in the original. Hard reject.
type ContentImproveSource string

// ContentScoreRequest Lightweight request for the local scorer alone — used by the frontend
// to decide whether to render the ✨ button on a bullet (debounce ~800ms).
// Same scorer as the improve flow, exposed as its own endpoint so the
// button visibility check doesn't pay for the brief assembly.
type ContentScoreRequest struct {
	Locale ContentScoreRequestLocale `json:"locale"`
	Text   string                    `json:"text"`
}

// ContentScoreRequestLocale defines model for ContentScoreRequest.Locale.
type ContentScoreRequestLocale string

// ContentScoreResponse defines model for ContentScoreResponse.
type ContentScoreResponse struct {
	Score      int               `json:"score"`
	Weaknesses []ContentWeakness `json:"weaknesses"`
}

// ContentWeakness Classes of weakness the local scorer detects. All detected without
// regex or keyword lists — `weak_verb` / `vague_filler` use cosine
// against pre-computed centroids; `no_metric` / `first_person` /
// `no_outcome` use GLiNER entity extraction; `too_short` / `too_long`
// are structural token counts (not extraction).
type ContentWeakness string

// CrowdsourcedImprovement defines model for CrowdsourcedImprovement.
type CrowdsourcedImprovement struct {
	Accepts int `json:"accepts"`

	// InputPatternHash MinHash fingerprint of the original input text (k=3 shingles).
	// ai-core compares the current input's fingerprint against this and
	// promotes a cache hit when Jaccard estimate >= 0.8.
	InputPatternHash string `json:"inputPatternHash"`

	// OutputText The accepted rewrite to serve on a hit.
	OutputText string `json:"outputText"`
	Rejects    int    `json:"rejects"`
}
