// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.BulletTarget

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BulletTarget(
    val scope: BulletTargetScope,
    /**
     * Index into `resume.sections[]`.
     */
    @SerialName("section_index")
    val sectionIndex: Int,
    /**
     * Index into `resume.sections[section_index].items[]`. The pointed-at
     * section MUST be one whose items have a `description` field:
     * employment, education, certifications, projects,
     * extraCurricularActivities. Skills/Languages/References sections
     * are not valid targets for rewrite_bullet/add_bullet.
     */
    @SerialName("item_index")
    val itemIndex: Int,
)

@Serializable
enum class BulletTargetScope {
    @SerialName("bullet") BULLET,
}
