// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.CompatibilityScore

package com.laddro.schemas.tailor

import kotlinx.serialization.Serializable

@Serializable
data class CompatibilityScore(
    /**
     * Live-updating score shown at top of suggestion stack. Recomputed
     * client-side as suggestions are accepted/discarded using the same
     * formula the backend would produce.
     */
    val total: Int,
    val breakdown: ScoreBreakdown,
)
