// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.Evidence

package com.laddro.schemas.tailor

import kotlinx.serialization.Serializable

@Serializable
data class Evidence(
    /**
     * The evidence text verbatim from the resume.
     */
    val text: String,
    val source: EvidenceSource,
)
