// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.EvidenceSource

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class EvidenceSource(
    /**
     * Index into `resume.sections[]` this evidence came from.
     */
    @SerialName("section_index")
    val sectionIndex: Int,
    /**
     * Index into that section's `items[]`.
     */
    @SerialName("item_index")
    val itemIndex: Int,
    /**
     * Verbatim HTML fragment within the item's description (or skill
     * label / etc) that this evidence quotes. Empty when the evidence
     * is the whole item (e.g. a SkillItem or LanguageItem). Used by
     * auditing and by the writer to know exactly which span to ground
     * against — NEVER for regex or substring rewriting in the writer.
     */
    @SerialName("fragment_anchor")
    val fragmentAnchor: String? = null,
)
