// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.FillRequest

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FillRequest(
    val suggestion: Suggestion,
    /**
     * Resume spans the writer is allowed to draw from. The writer
     * refuses (422) when none of the evidence supports the instruction
     * — the no-fabrication gate. Every span carries a structured
     * EvidenceSource so the writer's grounding is auditable: we can
     * always answer "which bullet did this proposed text come from?"
     */
    val evidence: List<Evidence>,
    val locale: FillRequestLocale,
)

@Serializable
enum class FillRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
