// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.FillResponse

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FillResponse(
    /**
     * Writer LLM output, in the requested locale. Single bullet, no
     * headers, no preamble. Strictly grounded in `evidence`.
     */
    @SerialName("proposed_text")
    val proposedText: String,
)
