// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.JobDescription

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class JobDescription(
    /**
     * The original input, preserved verbatim for source-span lookups.
     */
    @SerialName("raw_text")
    val rawText: String,
    val locale: JobDescriptionLocale,
    /**
     * Job title as identified by NER, in the JD's source language. Empty
     * string when the model could not identify one. Never falls back to
     * "first non-empty line" or any other structural heuristic.
     */
    val title: String? = null,
    /**
     * Company / organization name from NER. Empty string when none
     * detected. Never falls back to text patterns.
     */
    val company: String? = null,
    val seniority: Seniority,
    val skills: List<Skill>,
    val requirements: List<Requirement>,
)

@Serializable
enum class JobDescriptionLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
