// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.NoFitReason

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NoFitReason(
    /**
     * - `skills_gap`            JD's required skills aren't present in the resume
     *                           and no anchors support adding them.
     * - `seniority_gap`         Resume's experience level is materially off from
     *                           what the JD asks for (junior → director, or vice
     *                           versa).
     * - `industry_mismatch`     Resume's occupation graph and the JD's occupation
     *                           don't overlap (nurse vs. backend engineer).
     * - `insufficient_evidence` Resume itself is too thin (empty descriptions,
     *                           no experiences) for any meaningful matching.
     */
    val primary: NoFitReasonPrimary,
    /**
     * One- or two-sentence reason in the user's locale, drawn from i18n
     * strings — not free-form LLM output. Frontend shows verbatim.
     */
    val explanation: String,
)

/**
 * - `skills_gap`            JD's required skills aren't present in the resume
 *                           and no anchors support adding them.
 * - `seniority_gap`         Resume's experience level is materially off from
 *                           what the JD asks for (junior → director, or vice
 *                           versa).
 * - `industry_mismatch`     Resume's occupation graph and the JD's occupation
 *                           don't overlap (nurse vs. backend engineer).
 * - `insufficient_evidence` Resume itself is too thin (empty descriptions,
 *                           no experiences) for any meaningful matching.
 */
@Serializable
enum class NoFitReasonPrimary {
    @SerialName("skills_gap") SKILLS_GAP,
    @SerialName("seniority_gap") SENIORITY_GAP,
    @SerialName("industry_mismatch") INDUSTRY_MISMATCH,
    @SerialName("insufficient_evidence") INSUFFICIENT_EVIDENCE,
}
