// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.Requirement

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Requirement(
    /**
     * Stable identifier scoped to a single TailorResponse. Suggestion
     * records targeting this requirement set `requirement_ref` to
     * this UUID. See Skill.id for the same scoping rule.
     */
    val id: String,
    /**
     * The requirement span, verbatim from raw_text.
     */
    val text: String,
    /**
     * Canonical category, classified by the model. This set is
     * deliberately industry-agnostic: a nurse's "patient handover" and
     * an engineer's "deploy to prod" both map to `responsibility`. A
     * welder's "MIG certification" and a lawyer's "bar admission" both
     * map to `qualification`. New categories require a contract bump,
     * not a code patch.
     */
    val category: RequirementCategory,
    val confidence: Double,
    @SerialName("source_quote")
    val sourceQuote: String,
)

/**
 * Canonical category, classified by the model. This set is
 * deliberately industry-agnostic: a nurse's "patient handover" and
 * an engineer's "deploy to prod" both map to `responsibility`. A
 * welder's "MIG certification" and a lawyer's "bar admission" both
 * map to `qualification`. New categories require a contract bump,
 * not a code patch.
 */
@Serializable
enum class RequirementCategory {
    @SerialName("skill") SKILL,
    @SerialName("responsibility") RESPONSIBILITY,
    @SerialName("qualification") QUALIFICATION,
    @SerialName("experience") EXPERIENCE,
    @SerialName("soft") SOFT,
}
