// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.ScoreBreakdown

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ScoreBreakdown(
    /**
     * Share of required skills the resume already covers exactly.
     */
    @SerialName("exact_skills")
    val exactSkills: Double,
    /**
     * Share covered by semantically-adjacent skills (embedding
     * similarity above the calibrated threshold). NEVER token overlap.
     */
    @SerialName("adjacent_skills")
    val adjacentSkills: Double,
    /**
     * How well the resume's experience aligns with JobDescription.
     * seniority — calibrated against the eval set, not a hardcoded
     * ladder.
     */
    @SerialName("seniority_fit")
    val seniorityFit: Double,
)
