// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.Seniority

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Seniority(
    /**
     * Seniority bucket, classified by a multilingual model. `unknown`
     * when the model's confidence is below the configured floor — NEVER
     * inferred from years_min via a hardcoded ladder.
     */
    val level: SeniorityLevel,
    /**
     * Minimum years-of-experience asked for, extracted via locale-aware
     * structured extraction. 0 when none stated. Phrasing varies wildly
     * across locales ("3+ years", "Berufserfahrung von 3 Jahren",
     * "5 vuoden kokemus") — extraction is the model's job, not regex.
     */
    @SerialName("years_min")
    val yearsMin: Int? = null,
    /**
     * Maximum years asked for. 0 when none stated.
     */
    @SerialName("years_max")
    val yearsMax: Int? = null,
    /**
     * Model confidence in the `level` label.
     */
    val confidence: Double,
)

/**
 * Seniority bucket, classified by a multilingual model. `unknown`
 * when the model's confidence is below the configured floor — NEVER
 * inferred from years_min via a hardcoded ladder.
 */
@Serializable
enum class SeniorityLevel {
    @SerialName("entry") ENTRY,
    @SerialName("mid") MID,
    @SerialName("senior") SENIOR,
    @SerialName("lead") LEAD,
    @SerialName("unknown") UNKNOWN,
}
