// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.Skill

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Skill(
    /**
     * Stable identifier. The worker assigns a UUID at extraction time
     * so the orchestrator and the frontend can reference the same
     * Skill across the request → suggestion → fill round-trip. Suggestion
     * records targeting this skill set `requirement_ref` to this UUID.
     * Different worker calls on the same JD MAY produce different
     * UUIDs — IDs are scoped to a single TailorResponse, not stable
     * across calls.
     */
    val id: String,
    /**
     * Skill name as it appeared in the JD, in source language.
     */
    val label: String,
    /**
     * Canonical form for deduplication only. Produced by the model's
     * normalizer (lowercase + locale-aware diacritic handling). Not
     * used for semantic matching — that's embeddings' job.
     */
    val normalized: String,
    /**
     * ESCO concept URI when the multilingual ESCO linker matched this
     * skill. Empty when no link — scorer falls back to embedding
     * similarity, never to string matching.
     */
    @SerialName("esco_id")
    val escoId: String? = null,
    /**
     * Whether the JD treats this skill as required vs nice-to-have.
     * This is a span-classifier output across all 14 locales — NOT a
     * keyword scan over "required"/"must have"/"nice to have". When
     * the classifier's confidence is below the configured floor, the
     * worker omits the skill rather than defaulting to required.
     */
    val required: Boolean,
    val confidence: Double,
    /**
     * The original span the model attributed this skill to, verbatim
     * from raw_text. The frontend shows it as "from the JD: ...".
     */
    @SerialName("source_quote")
    val sourceQuote: String,
)
