// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.SkillTarget

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SkillTarget(
    val scope: SkillTargetScope,
    /**
     * Index into `resume.sections[]`. The pointed-at section MUST be a
     * SkillsSection (`type: skills`). For `add_skill`, the new SkillItem
     * is appended to `items[]`.
     */
    @SerialName("section_index")
    val sectionIndex: Int,
)

@Serializable
enum class SkillTargetScope {
    @SerialName("skill") SKILL,
}
