// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.SuggestionTarget

package com.laddro.schemas.tailor

import kotlinx.serialization.Serializable

/**
 * Discriminated union pointing at the exact Resume object a Suggestion
 * mutates. `scope` matches the Suggestion.kind's natural target:
 *   rewrite_bullet, add_bullet  → BulletTarget   (scope=bullet)
 *   rewrite_summary             → SummaryTarget  (scope=summary)
 *   add_skill                   → SkillTarget    (scope=skill)
 */
@Serializable
class SuggestionTarget
