// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.Suggestion

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Suggestion(
    val id: String,
    /**
     * What this suggestion does to the resume. Each kind has a matching
     * `target` shape (see SuggestionTarget) and a per-kind meaning for
     * `original_text`:
     *
     * - `rewrite_bullet`   Replace one `<li>` (or `<p>`) inside
     *                      `resume.sections[target.section_index].items[target.item_index].description`.
     *                      `original_text` is the verbatim HTML fragment
     *                      to find and replace.
     * - `add_bullet`       Append a new `<li>` to the same description.
     *                      `original_text` is the resume "anchor" — the
     *                      existing experience text the new bullet must
     *                      stay faithful to. The anchor is NOT in the
     *                      description being mutated; it's evidence from
     *                      elsewhere in the resume.
     * - `rewrite_summary`  Replace `resume.summary.value` entirely.
     *                      `original_text` is the current summary verbatim.
     * - `add_skill`        Append a SkillItem to a SkillsSection.
     *                      `original_text` is the bullet/text from the
     *                      resume that proves the user already has the
     *                      skill. Refused (no suggestion emitted) when
     *                      no anchor exists — the no-fabrication gate.
     *
     * Suggestions can be applied in any order. Frontend matches the
     * verbatim `original_text` substring on `rewrite_*` to stay robust
     * against user edits between fetch and accept; if not found, the
     * card goes stale-grayed in the UI.
     */
    val kind: SuggestionKind,
    val target: SuggestionTarget,
    /**
     * Per-kind semantics — see `kind`. Always shown to the user as proof
     * of grounding ("from your resume: ...").
     */
    @SerialName("original_text")
    val originalText: String,
    /**
     * Locale-aware instruction the writer LLM uses to produce
     * proposed_text. Generated by the recommender, not free-form.
     */
    val instruction: String,
    /**
     * Empty until the writer LLM is called for this suggestion (lazy
     * per-card via /v1/tailor/fill). Discarded suggestions stay empty
     * and cost zero LLM tokens.
     */
    @SerialName("proposed_text")
    val proposedText: String? = null,
    /**
     * ID of the JobDescription requirement (or skill) this suggestion
     * addresses. Lets the frontend show "this card addresses THIS ask
     * from the JD" with the source_quote highlighted.
     */
    @SerialName("requirement_ref")
    val requirementRef: String,
)

/**
 * What this suggestion does to the resume. Each kind has a matching
 * `target` shape (see SuggestionTarget) and a per-kind meaning for
 * `original_text`:
 *
 * - `rewrite_bullet`   Replace one `<li>` (or `<p>`) inside
 *                      `resume.sections[target.section_index].items[target.item_index].description`.
 *                      `original_text` is the verbatim HTML fragment
 *                      to find and replace.
 * - `add_bullet`       Append a new `<li>` to the same description.
 *                      `original_text` is the resume "anchor" — the
 *                      existing experience text the new bullet must
 *                      stay faithful to. The anchor is NOT in the
 *                      description being mutated; it's evidence from
 *                      elsewhere in the resume.
 * - `rewrite_summary`  Replace `resume.summary.value` entirely.
 *                      `original_text` is the current summary verbatim.
 * - `add_skill`        Append a SkillItem to a SkillsSection.
 *                      `original_text` is the bullet/text from the
 *                      resume that proves the user already has the
 *                      skill. Refused (no suggestion emitted) when
 *                      no anchor exists — the no-fabrication gate.
 *
 * Suggestions can be applied in any order. Frontend matches the
 * verbatim `original_text` substring on `rewrite_*` to stay robust
 * against user edits between fetch and accept; if not found, the
 * card goes stale-grayed in the UI.
 */
@Serializable
enum class SuggestionKind {
    @SerialName("rewrite_bullet") REWRITE_BULLET,
    @SerialName("add_bullet") ADD_BULLET,
    @SerialName("rewrite_summary") REWRITE_SUMMARY,
    @SerialName("add_skill") ADD_SKILL,
}
