// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.SummaryTarget

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Targets `resume.summary.value`. No indices — there's exactly one summary.
 */
@Serializable
data class SummaryTarget(
    val scope: SummaryTargetScope,
)

@Serializable
enum class SummaryTargetScope {
    @SerialName("summary") SUMMARY,
}
