// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorRequest

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
data class TailorRequest(
    /**
     * The full Resume DTO. ai-core consumes it typed and walks every
     * section, item, and description in order to produce Suggestions
     * with valid `target.section_index` / `target.item_index` indices
     * into THIS resume. The frontend must send the resume verbatim
     * (no stripping) so suggestions remain applicable.
     *
     * Consumers MUST import the typed Resume from
     * `@laddro-app/schemas/resume`:
     *   - TS:  `import type { components } from '@laddro-app/schemas/resume'`
     *          then `components['schemas']['Resume']`
     *   - Go:  `github.com/laddro-app/laddro-schemas/go/resume.Resume`
     *
     * The field is declared as `type: object` here only because OpenAPI
     * 3.1 cross-file `$ref` support is uneven across our codegen tools.
     * Treat it as `Resume` at every call site.
     */
    val resume: JsonObject,
    /**
     * Raw JD text. The worker parses it.
     */
    @SerialName("job_description")
    val jobDescription: String,
    val locale: TailorRequestLocale,
)

@Serializable
enum class TailorRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
