// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorJobEventType

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Closed set of event types ai-core emits. The frontend's progress
 * timeline renders one step per non-`fill.progress` event;
 * `tailor.fill.progress` is the only multi-event step (one event
 * per parallel filler completing a card).
 */
@Serializable
enum class TailorJobEventType {
    @SerialName("tailor.started") TAILOR_STARTED,
    @SerialName("tailor.pretrim.done") TAILOR_PRETRIM_DONE,
    @SerialName("tailor.extract_jd.done") TAILOR_EXTRACT_JD_DONE,
    @SerialName("tailor.extract_profile.done") TAILOR_EXTRACT_PROFILE_DONE,
    @SerialName("tailor.match.done") TAILOR_MATCH_DONE,
    @SerialName("tailor.recommend.done") TAILOR_RECOMMEND_DONE,
    @SerialName("tailor.fill.progress") TAILOR_FILL_PROGRESS,
    @SerialName("tailor.verdict.done") TAILOR_VERDICT_DONE,
    @SerialName("tailor.completed") TAILOR_COMPLETED,
    @SerialName("tailor.failed") TAILOR_FAILED,
    @SerialName("tailor.cancelled") TAILOR_CANCELLED,
}
