// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorJobEvent

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * Append-only event emitted by ai-core during a tailor run.
 * Persisted via UNIQUE (job_id, sequence) so duplicate POSTs (from
 * ai-core retries or webhook redelivery) are idempotent no-ops.
 * Sequence numbers are monotonic per job; reconnecting SSE clients
 * pass the last seen sequence in `Last-Event-ID` and the server
 * replays from there.
 */
@Serializable
data class TailorJobEvent(
    /**
     * The TailorJob this event belongs to.
     */
    @SerialName("job_id")
    val jobId: String,
    /**
     * Monotonic per-job sequence number. The first event a job
     * ever emits is sequence=1. If ai-core crashes mid-run and a
     * retry resumes the pipeline, sequence continues from the
     * backend's stored `last_event_seq + 1` — it never resets.
     */
    val sequence: Int,
    @SerialName("event_type")
    val eventType: TailorJobEventType,
    /**
     * ai-core's wall-clock at emit time. The backend also stamps
     * its own `ingested_at` for lag observability.
     */
    @SerialName("occurred_at")
    val occurredAt: String,
    /**
     * Step-specific payload. Shapes by event_type:
     *
     * - tailor.started
     *     { jd_length_chars: int, resume_version: string,
     *       locale: string }
     * - tailor.pretrim.done
     *     { trimmed: bool, before_chars: int, after_chars: int }
     * - tailor.extract_jd.done
     *     { archetype: string, title: string,
     *       required_skill_count: int, nice_count: int }
     * - tailor.extract_profile.done
     *     { archetype: string, years_experience: int,
     *       primary_stack_count: int, secondary_stack_count: int }
     * - tailor.match.done
     *     { matched_required: int, missing_required: int,
     *       hidden_skills_count: int }
     * - tailor.recommend.done
     *     { card_count: int,
     *       by_kind: { summary: int, skill: int, bullet: int } }
     * - tailor.fill.progress
     *     { card_id: string, kind: string, success: bool,
     *       error?: string }
     * - tailor.verdict.done
     *     { verdict: string, score: int, reason?: string }
     * - tailor.completed
     *     { result_summary: object, total_llm_calls: int,
     *       total_tokens: int, cost_usd: number,
     *       duration_ms: int }
     * - tailor.failed
     *     { failed_at_step: string, error_class: string,
     *       error_message: string, retryable: bool }
     * - tailor.cancelled
     *     { cancelled_at_step: string,
     *       reason: string }   # e.g. "user_requested"
     *
     * Consumers MUST NOT regex on the payload. Each shape is
     * switched on `event_type`, fields are read by name.
     */
    val payload: JsonObject,
)
