// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorResponse

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class TailorResponse(
    @SerialName("parsed_job")
    val parsedJob: JobDescription,
    @SerialName("compatibility_score")
    val compatibilityScore: CompatibilityScore,
    /**
     * Honest verdict on whether this resume can be tailored to this JD
     * at all. Derived from compatibility_score, the recommender's anchor
     * coverage (how many required skills have any resume evidence), and
     * the seniority gap.
     *
     * - `strong_fit`   normal stack, most requirements have anchors.
     * - `partial_fit`  normal stack, some gaps the user should know about.
     * - `weak_fit`     stack rendered with a banner: "low fit, consider
     *                  a different job — these are what we could find."
     * - `no_fit`       suggestions[] is empty by construction. Frontend
     *                  shows "this isn't your job — we don't fake resumes,
     *                  we prepare you for the job." Backed by no_fit_reason.
     *
     * ai-core owns the decision rule. Frontend branches UX off this enum
     * only — it never re-derives the verdict from the score.
     */
    @SerialName("fit_verdict")
    val fitVerdict: TailorResponseFitVerdict,
    /**
     * Present when fit_verdict is `weak_fit` or `no_fit`. Machine-readable
     * primary cause + locale-aware human explanation the frontend can
     * surface verbatim.
     */
    @SerialName("no_fit_reason")
    val noFitReason: JsonElement? = null,
    val suggestions: List<Suggestion>,
)

/**
 * Honest verdict on whether this resume can be tailored to this JD
 * at all. Derived from compatibility_score, the recommender's anchor
 * coverage (how many required skills have any resume evidence), and
 * the seniority gap.
 *
 * - `strong_fit`   normal stack, most requirements have anchors.
 * - `partial_fit`  normal stack, some gaps the user should know about.
 * - `weak_fit`     stack rendered with a banner: "low fit, consider
 *                  a different job — these are what we could find."
 * - `no_fit`       suggestions[] is empty by construction. Frontend
 *                  shows "this isn't your job — we don't fake resumes,
 *                  we prepare you for the job." Backed by no_fit_reason.
 *
 * ai-core owns the decision rule. Frontend branches UX off this enum
 * only — it never re-derives the verdict from the score.
 */
@Serializable
enum class TailorResponseFitVerdict {
    @SerialName("strong_fit") STRONG_FIT,
    @SerialName("partial_fit") PARTIAL_FIT,
    @SerialName("weak_fit") WEAK_FIT,
    @SerialName("no_fit") NO_FIT,
}
