// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorJobCreateRequest

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * Body of POST /ai/tailor-jobs. Replaces the synchronous
 * TailorRequest at the backend boundary. Backend creates a job
 * row, enqueues a runner, and returns the snapshot in status
 * `pending` immediately — the client never waits for ai-core.
 */
@Serializable
data class TailorJobCreateRequest(
    /**
     * The frontend's stable draft id (also the URL path param on
     * /tailor-resume/[id]). Used to find the most-recent job on
     * page refresh.
     */
    @SerialName("tailor_uuid")
    val tailorUuid: String,
    /**
     * Resume DTO — same shape as TailorRequest.resume. See the
     * cross-file note on resume typing.
     */
    val resume: JsonObject,
    @SerialName("job_description")
    val jobDescription: String,
    val locale: TailorJobCreateRequestLocale,
    /**
     * Optional. Stored on the sibling resume metadata when the
     * job completes. Not sent to ai-core.
     */
    val company: String? = null,
    /**
     * Optional. Stored on the sibling resume metadata.
     */
    val position: String? = null,
    /**
     * Backwards-compatible passthrough from the existing sync
     * contract. Default is `reviewSuggestions`.
     */
    @SerialName("approval_mode")
    val approvalMode: TailorJobCreateRequestApprovalMode? = null,
)

@Serializable
enum class TailorJobCreateRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}

/**
 * Backwards-compatible passthrough from the existing sync
 * contract. Default is `reviewSuggestions`.
 */
@Serializable
enum class TailorJobCreateRequestApprovalMode {
    @SerialName("autoApply") AUTO_APPLY,
    @SerialName("reviewSuggestions") REVIEW_SUGGESTIONS,
}
