// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorJobStatus

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * State machine for a tailor job.
 *
 * - `pending`    Row created, runner not yet picked it up.
 * - `running`    Runner started, ai-core executing.
 * - `completed`  Terminal. result_json populated, fit_verdict in
 *                {strong_fit, partial_fit, weak_fit}.
 * - `no_fit`     Terminal but distinct from `completed` because
 *                suggestions[] is empty by construction. UI shows
 *                the no-fit reason + offers an explicit override.
 * - `failed`     Terminal after exhausting retries. fail_reason
 *                carries an error_class + locale-aware message.
 * - `cancelled`  User-initiated abort. ai-core honors via
 *                ctx.Done() at the next step boundary.
 */
@Serializable
enum class TailorJobStatus {
    @SerialName("pending") PENDING,
    @SerialName("running") RUNNING,
    @SerialName("completed") COMPLETED,
    @SerialName("no_fit") NO_FIT,
    @SerialName("failed") FAILED,
    @SerialName("cancelled") CANCELLED,
}
