// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorJobOverrideRequest

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Body of POST /ai/tailor-jobs/:id/override. Empty payload by
 * design — the backend already has the source job_id, the
 * tailor_uuid, the resume, and the JD. The override flag is a
 * server-side trip so we always have the audit trail of "user
 * was told no_fit, then chose to override."
 */
@Serializable
data class TailorJobOverrideRequest(
    /**
     * Must be true. The frontend sets it as the user clicks the
     * "tailor anyway" button. Defends against accidental retries
     * that look like overrides.
     */
    @SerialName("acknowledge_no_fit")
    val acknowledgeNoFit: Boolean? = null,
)
