// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.TailorJobSnapshot

package com.laddro.schemas.tailor

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Canonical durable view of a job. Returned by:
 *   - GET /ai/tailor-jobs/:id
 *   - GET /ai/tailor-jobs/by-uuid/:tailor_uuid
 * and as the initial frame on the SSE stream before live events
 * start flowing. The frontend reconstructs UI state by replaying
 * `events` in sequence order, then subscribing for new ones.
 */
@Serializable
data class TailorJobSnapshot(
    @SerialName("job_id")
    val jobId: String,
    /**
     * The tailor draft / sibling resume slot this job belongs to.
     * Stable across retries and override jobs — the frontend
     * queries by tailor_uuid on page mount, regardless of how many
     * job_ids a user has accumulated for the same target.
     */
    @SerialName("tailor_uuid")
    val tailorUuid: String,
    /**
     * Set when this job is an override of a previous no_fit job
     * (POST /ai/tailor-jobs/:id/override). Lets us audit
     * "user was told no_fit, then chose to tailor anyway".
     */
    @SerialName("parent_job_id")
    val parentJobId: String? = null,
    val status: TailorJobStatus,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    /**
     * When the runner first transitioned status to running.
     */
    @SerialName("started_at")
    val startedAt: String? = null,
    /**
     * When the job reached a terminal status (completed | no_fit |
     * failed | cancelled). Null until then.
     */
    @SerialName("completed_at")
    val completedAt: String? = null,
    /**
     * Highest sequence the backend has persisted for this job.
     * SSE clients reconnecting pass this as `Last-Event-ID`.
     */
    @SerialName("last_event_seq")
    val lastEventSeq: Int,
    /**
     * How many times the orphan sweeper has re-enqueued this job.
     * Hard ceiling at 3 — beyond that the job is marked failed.
     */
    @SerialName("retry_count")
    val retryCount: Int? = null,
    /**
     * All persisted events for this job, in ascending sequence
     * order. On initial GET this is the full history; on the SSE
     * stream this is the catch-up replay before live events.
     */
    val events: List<TailorJobEvent>,
    /**
     * Present when status is `completed` or `no_fit`. Cached so
     * revisits never re-run the pipeline — the page just renders
     * from this snapshot.
     */
    val result: JsonElement? = null,
    /**
     * Present when status is `failed`. Machine + human halves so
     * the frontend can render verbatim AND branch UX on the class.
     */
    @SerialName("fail_reason")
    val failReason: TailorJobSnapshotFailReason? = null,
)

/**
 * Present when status is `failed`. Machine + human halves so
 * the frontend can render verbatim AND branch UX on the class.
 */
@Serializable
data class TailorJobSnapshotFailReason(
    /**
     * Closed set, e.g. ai_core_unreachable, llm_timeout,
     * invalid_ai_response, validator_rejected, internal_error.
     */
    @SerialName("error_class")
    val errorClass: String? = null,
    /**
     * Locale-aware message the user is shown.
     */
    @SerialName("error_message")
    val errorMessage: String? = null,
    /**
     * Whether the frontend should surface a "retry" button.
     * False for hard failures (invalid_ai_response after
     * exhausted retries).
     */
    val retryable: Boolean? = null,
)
