// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: tailor/tailor.v1.yaml -> components.schemas.WorkerAnalyzeResponse

package com.laddro.schemas.tailor

import kotlinx.serialization.Serializable

@Serializable
class WorkerAnalyzeResponse
