// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.BaseEvent

package com.laddro.schemas.inbox

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
data class BaseEvent(
    val userId: String,
    val routeParams: JsonObject? = null,
)
