// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.Event_DocumentReviewCommentReceived

package com.laddro.schemas.inbox

import kotlinx.serialization.json.JsonElement

/**
 * A reviewer left one or more comments on the user's online resume.
 * This kind is AGGREGATED by the pipeline: the backend supplies an
 * `aggregationKey` on the envelope (never a param) so repeat comments
 * from the same reviewer on the same resume collapse into one inbox
 * row and refresh its `commentCount` instead of stacking new rows.
 * `commentCount` is the cumulative count computed by the backend at
 * publish time (single source of truth).
 */
typealias EventDocumentReviewCommentReceived = JsonElement
