// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.Event_CreditsMonthlyReset

package com.laddro.schemas.inbox

import kotlinx.serialization.json.JsonElement

typealias EventCreditsMonthlyReset = JsonElement
