// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.Event_DocumentAiComplete

package com.laddro.schemas.inbox

import kotlinx.serialization.Serializable

@Serializable
class EventDocumentAiComplete
