// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.InboxEventInput

package com.laddro.schemas.inbox

import kotlinx.serialization.json.JsonElement

/**
 * Discriminated union of every inbox event a backend can publish.
 * Callers use this type. The transport layer wraps it in an
 * `InboxEnvelope` before publishing.
 */
typealias InboxEventInput = JsonElement
