// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.InboxEnvelope

package com.laddro.schemas.inbox

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * The on-wire shape Pub/Sub carries / the HTTP transport POSTs. Adds
 * a UUID `id` for idempotency on top of the caller-supplied input.
 */
@Serializable
data class InboxEnvelope(
    /**
     * Idempotency key generated by the publisher.
     */
    val id: String,
    val kind: InboxKind,
    val userId: String,
    val params: JsonObject,
    /**
     * Optional per-action payload data the Go renderer attaches to
     * BlockAction.routeParams (used by failure-with-retry kinds so
     * the frontend can re-fire the original request one-click).
     */
    val routeParams: JsonObject? = null,
)
