// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: inbox/inbox.v1.yaml -> components.schemas.InboxKind

package com.laddro.schemas.inbox

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The full taxonomy of in-app notification kinds Laddro supports.
 * Backend authors should NOT publish a kind that is not in this enum —
 * the Go renderer drops unknown kinds on receive.
 */
@Serializable
enum class InboxKind {
    @SerialName("account.welcome") ACCOUNT_WELCOME,
    @SerialName("account.email_verified") ACCOUNT_EMAIL_VERIFIED,
    @SerialName("account.password_changed") ACCOUNT_PASSWORD_CHANGED,
    @SerialName("account.password_reset_requested") ACCOUNT_PASSWORD_RESET_REQUESTED,
    @SerialName("account.deletion_warning") ACCOUNT_DELETION_WARNING,
    @SerialName("account.connected_added") ACCOUNT_CONNECTED_ADDED,
    @SerialName("account.connected_removed") ACCOUNT_CONNECTED_REMOVED,
    @SerialName("billing.payment_succeeded") BILLING_PAYMENT_SUCCEEDED,
    @SerialName("billing.payment_failed") BILLING_PAYMENT_FAILED,
    @SerialName("billing.subscription_renewed") BILLING_SUBSCRIPTION_RENEWED,
    @SerialName("billing.cancellation_scheduled") BILLING_CANCELLATION_SCHEDULED,
    @SerialName("billing.cancellation_confirmed") BILLING_CANCELLATION_CONFIRMED,
    @SerialName("billing.reactivated") BILLING_REACTIVATED,
    @SerialName("billing.trial_ending") BILLING_TRIAL_ENDING,
    @SerialName("billing.card_expiring") BILLING_CARD_EXPIRING,
    @SerialName("billing.invoice_available") BILLING_INVOICE_AVAILABLE,
    @SerialName("billing.refund_issued") BILLING_REFUND_ISSUED,
    @SerialName("credits.added") CREDITS_ADDED,
    @SerialName("credits.low") CREDITS_LOW,
    @SerialName("credits.depleted") CREDITS_DEPLETED,
    @SerialName("credits.monthly_reset") CREDITS_MONTHLY_RESET,
    @SerialName("document.tailor_complete") DOCUMENT_TAILOR_COMPLETE,
    @SerialName("document.tailor_complete_failed") DOCUMENT_TAILOR_COMPLETE_FAILED,
    @SerialName("document.tailor_no_fit") DOCUMENT_TAILOR_NO_FIT,
    @SerialName("document.ai_complete") DOCUMENT_AI_COMPLETE,
    @SerialName("document.download_ready") DOCUMENT_DOWNLOAD_READY,
    @SerialName("document.shared_by_you") DOCUMENT_SHARED_BY_YOU,
    @SerialName("document.viewed_by_visitor") DOCUMENT_VIEWED_BY_VISITOR,
    @SerialName("document.review_comment_received") DOCUMENT_REVIEW_COMMENT_RECEIVED,
    @SerialName("tracker.application_reminder") TRACKER_APPLICATION_REMINDER,
    @SerialName("tracker.interview_scheduled") TRACKER_INTERVIEW_SCHEDULED,
    @SerialName("tracker.followup_due") TRACKER_FOLLOWUP_DUE,
    @SerialName("tracker.status_changed") TRACKER_STATUS_CHANGED,
    @SerialName("tracker.deadline_approaching") TRACKER_DEADLINE_APPROACHING,
    @SerialName("engagement.onboarding_incomplete") ENGAGEMENT_ONBOARDING_INCOMPLETE,
    @SerialName("engagement.first_resume_incomplete") ENGAGEMENT_FIRST_RESUME_INCOMPLETE,
    @SerialName("engagement.inactivity_nudge") ENGAGEMENT_INACTIVITY_NUDGE,
    @SerialName("engagement.weekly_tip") ENGAGEMENT_WEEKLY_TIP,
    @SerialName("engagement.linkedin_update_reminder") ENGAGEMENT_LINKEDIN_UPDATE_REMINDER,
    @SerialName("legal.terms_updated") LEGAL_TERMS_UPDATED,
    @SerialName("legal.privacy_updated") LEGAL_PRIVACY_UPDATED,
    @SerialName("legal.cookie_updated") LEGAL_COOKIE_UPDATED,
    @SerialName("legal.gdpr_export_ready") LEGAL_GDPR_EXPORT_READY,
    @SerialName("legal.gdpr_deletion_confirmed") LEGAL_GDPR_DELETION_CONFIRMED,
    @SerialName("feedback.raw_prompt") FEEDBACK_RAW_PROMPT,
    @SerialName("feedback.trustpilot_request") FEEDBACK_TRUSTPILOT_REQUEST,
    @SerialName("feedback.nps_survey") FEEDBACK_NPS_SURVEY,
    @SerialName("feedback.feature_feedback") FEEDBACK_FEATURE_FEEDBACK,
    @SerialName("feedback.beta_feedback") FEEDBACK_BETA_FEEDBACK,
    @SerialName("referral.friend_signed_up") REFERRAL_FRIEND_SIGNED_UP,
    @SerialName("referral.credits_earned") REFERRAL_CREDITS_EARNED,
    @SerialName("referral.threshold_reached") REFERRAL_THRESHOLD_REACHED,
    @SerialName("system.feature_announcement") SYSTEM_FEATURE_ANNOUNCEMENT,
    @SerialName("system.scheduled_maintenance") SYSTEM_SCHEDULED_MAINTENANCE,
    @SerialName("system.service_restored") SYSTEM_SERVICE_RESTORED,
}
