// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ActivityItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class ActivityItem(
    val activity: String,
    val startDate: MonthDate? = null,
    val endDate: MonthDate? = null,
    val current: Boolean? = false,
    /**
     * HTML allowed.
     */
    val description: String? = null,
)
