// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.CertificationItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class CertificationItem(
    val certification: String,
    val institution: String? = null,
    val startDate: MonthDate? = null,
    val endDate: MonthDate? = null,
    /**
     * HTML allowed.
     */
    val description: String? = null,
)
