// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.CustomSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
data class CustomSection(
    val type: CustomSectionType,
    /**
     * Stable developer-supplied slug, used as customSectionId in storage.
     */
    val id: String,
    val title: String,
    val items: List<CustomSectionItems>,
)

@Serializable
enum class CustomSectionType {
    @SerialName("custom") CUSTOM,
}

@Serializable
data class CustomSectionItems(
    val fields: JsonObject? = null,
)
