// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.EducationItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class EducationItem(
    val institution: String,
    val degree: String? = null,
    val major: String? = null,
    val startDate: MonthDate? = null,
    val endDate: MonthDate? = null,
    val current: Boolean? = false,
    val city: String? = null,
    /**
     * HTML allowed.
     */
    val description: String? = null,
)
