// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.EducationSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class EducationSection(
    val type: EducationSectionType,
    val title: String? = null,
    val items: List<EducationItem>,
)

@Serializable
enum class EducationSectionType {
    @SerialName("education") EDUCATION,
}
