// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.EmploymentSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class EmploymentSection(
    val type: EmploymentSectionType,
    /**
     * Optional title override; falls back to localized default.
     */
    val title: String? = null,
    val items: List<EmploymentItem>,
)

@Serializable
enum class EmploymentSectionType {
    @SerialName("employment") EMPLOYMENT,
}
