// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.EmploymentItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class EmploymentItem(
    val company: String,
    val position: String,
    val startDate: MonthDate? = null,
    val endDate: MonthDate? = null,
    val current: Boolean? = false,
    val city: String? = null,
    /**
     * HTML allowed (paragraphs and lists).
     */
    val description: String? = null,
)
