// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ExtraCurricularActivitiesSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ExtraCurricularActivitiesSection(
    val type: ExtraCurricularActivitiesSectionType,
    val title: String? = null,
    val items: List<ActivityItem>,
)

@Serializable
enum class ExtraCurricularActivitiesSectionType {
    @SerialName("extraCurricularActivities") EXTRA_CURRICULAR_ACTIVITIES,
}
