// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.LanguageItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class LanguageItem(
    val language: String,
    /**
     * Free text level e.g. Native, C1, B2, Conversational.
     */
    val level: String? = null,
)
