// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.LanguagesSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class LanguagesSection(
    val type: LanguagesSectionType,
    val title: String? = null,
    val items: List<LanguageItem>,
)

@Serializable
enum class LanguagesSectionType {
    @SerialName("languages") LANGUAGES,
}
