// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.MonthDate

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

/**
 * Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
 */
@Serializable
class MonthDate
