// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.MonthDate

package com.laddro.schemas.resume


/**
 * Month precision (YYYY-MM), or year-only (YYYY) when the source states no month. Use null endDate + current=true for ongoing entries.
 */
typealias MonthDate = String
