// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.PersonalSection

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class PersonalSection(
    val role: String? = null,
    val firstName: String? = null,
    val lastName: String? = null,
    val email: String? = null,
    val phone: String? = null,
    val city: String? = null,
    val country: String? = null,
    val website: String? = null,
    val linkedin: String? = null,
    /**
     * Optional user-supplied label+url pairs. Render as a separate cluster attached
     * to the contact area (single-column templates: second-line strip below contact
     * dots; sidebar templates: vertical block below the contact block). The fixed
     * website/linkedin fields above keep their own slots in the contact dots row.
     */
    val links: List<PersonalSectionLinks>? = null,
)

@Serializable
data class PersonalSectionLinks(
    val label: String,
    val url: String,
)
