// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ProjectsSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ProjectsSection(
    val type: ProjectsSectionType,
    val title: String? = null,
    val items: List<ProjectItem>,
)

@Serializable
enum class ProjectsSectionType {
    @SerialName("projects") PROJECTS,
}
