// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ProjectItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class ProjectItem(
    val title: String,
    /**
     * HTML allowed.
     */
    val description: String? = null,
    /**
     * Optional link to deployed project or repository.
     */
    val url: String? = null,
    val startDate: MonthDate? = null,
    val endDate: MonthDate? = null,
    val current: Boolean? = false,
)
