// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ReferencesSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ReferencesSection(
    val type: ReferencesSectionType,
    val title: String? = null,
    val items: List<ReferenceItem>,
)

@Serializable
enum class ReferencesSectionType {
    @SerialName("references") REFERENCES,
}
