// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ReferenceItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class ReferenceItem(
    val name: String,
    val position: String? = null,
    val company: String? = null,
    val email: String? = null,
    val phone: String? = null,
)
