// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.ReorderableSection

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
class ReorderableSection
