// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.Resume

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Resume(
    val id: String? = null,
    val title: String,
    val locale: ResumeLocale,
    /**
     * Slug from the template catalog. Defaults to `emerald` when
     * omitted. The read path always returns a resolved templateId.
     */
    val templateId: String? = "emerald",
    val isDefault: Boolean? = false,
    val personal: PersonalSection,
    val summary: SummarySection,
    /**
     * Reorderable sections. Array position IS the display order — no
     * per-section `order` field. `personal` and `summary` are top-level
     * and not part of this array.
     */
    val sections: List<ReorderableSection>? = null,
    val styling: Styling? = null,
    val completeness: Int? = null,
    val guidedFlowStatus: ResumeGuidedFlowStatus? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
)

@Serializable
enum class ResumeLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}

@Serializable
enum class ResumeGuidedFlowStatus {
    @SerialName("in_progress") IN_PROGRESS,
    @SerialName("completed") COMPLETED,
}
