// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.SkillsSection

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SkillsSection(
    val type: SkillsSectionType,
    val title: String? = null,
    val items: List<SkillItem>,
)

@Serializable
enum class SkillsSectionType {
    @SerialName("skills") SKILLS,
}
