// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.SkillItem

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class SkillItem(
    val skill: String,
    /**
     * Free-text proficiency e.g. Expert, Advanced, Intermediate, Beginner,
     * or a custom value. Optional — templates render gracefully when omitted.
     */
    val level: String? = null,
)
