// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.Styling

package com.laddro.schemas.resume

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Resume visual settings. All fields optional — the template's default
 * applies when omitted. Backend persists this as part of the encrypted
 * resume content.
 */
@Serializable
data class Styling(
    val colors: TemplateColors? = null,
    /**
     * DEPRECATED as an input, still written for backwards compatibility.
     *
     * A single accent hex. Readers MUST prefer `colors` when present and
     * fall back to this only for documents saved before `colors` existed.
     * Writers should emit both, with `color` mirroring
     * `colors.backgroundPartColor`.
     *
     * On its own this cannot express a palette: it carries no
     * `backgroundColor`, `text` or `textMuted`, and readers historically
     * applied it to `backgroundPartColor` AND `underlineColor` at once,
     * so any palette whose divider differs from its accent came back
     * wrong. Keep writing it so older clients still get an accent; keep
     * reading it so older documents still resolve.
     */
    val color: String? = null,
    /**
     * Font family override. Falls back to the template's default.
     */
    val font: String? = null,
    /**
     * Body font size in points.
     */
    val fontSize: Int? = null,
    /**
     * Page margin in points.
     */
    val margin: Double? = null,
    /**
     * Body line-height multiplier (e.g. 1.2, 1.4).
     */
    val lineHeight: Double? = null,
    /**
     * Profile photo URL. Templates that support photos render it; others ignore.
     */
    val photo: String? = null,
    /**
     * Photo size in points (square).
     */
    val photoSize: Double? = null,
    /**
     * Explicit on/off for the photo. When omitted, falls back to the
     * template's default (templates declare supportsProfileImage).
     */
    val showProfileImage: Boolean? = null,
    /**
     * Pagination style. `none` hides numbers; `simple` shows "1"; `fraction`
     * shows "1/3"; `page` shows "Page 1".
     */
    val pageNumbering: StylingPageNumbering? = null,
)

/**
 * Pagination style. `none` hides numbers; `simple` shows "1"; `fraction`
 * shows "1/3"; `page` shows "Page 1".
 */
@Serializable
enum class StylingPageNumbering {
    @SerialName("none") NONE,
    @SerialName("simple") SIMPLE,
    @SerialName("fraction") FRACTION,
    @SerialName("page") PAGE,
}
