// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.SummarySection

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

@Serializable
data class SummarySection(
    /**
     * Professional summary. HTML allowed (e.g. <p>, <strong>, <em>, <ul>, <li>).
     * Renderer parses inline tags.
     */
    val value: String? = null,
)
