// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: resume/resume.v1.yaml -> components.schemas.TemplateColors

package com.laddro.schemas.resume

import kotlinx.serialization.Serializable

/**
 * A complete template colour palette — the five slots every template
 * renders. This is one row of a template's `availableColors` in the
 * renderer catalog, stored verbatim so the choice round-trips exactly.
 *
 * All five are REQUIRED when the object is present. A partial palette is
 * what the single-hex `Styling.color` already is, and mixing a partial
 * palette with template defaults is what made saved colours unreadable:
 * the reader could not tell an intentional slot from an omitted one.
 * Present means complete; omit the whole object to accept the
 * template's default palette.
 *
 * Slot meanings, as the templates use them:
 *   backgroundColor      page fill, or the sidebar fill on two-column layouts
 *   backgroundPartColor  accent panels and filled blocks
 *   underlineColor       section dividers and rules
 *   text                 body text
 *   textMuted            secondary text (dates, locations, meta)
 */
@Serializable
data class TemplateColors(
    val backgroundColor: String,
    val backgroundPartColor: String,
    val underlineColor: String,
    val text: String,
    val textMuted: String,
)
