// Gradle module for the generated Kotlin models.
//
// Sources under src/main/kotlin are GENERATED by scripts/generate-kotlin.mjs.
// Do not hand-edit them; change the *.v1.yaml spec and regenerate.
//
// This is a plain Kotlin JVM library, deliberately not an Android library: the
// models are pure data with no Android dependency, so they stay usable from a
// JVM unit test, a server-side tool, or a future Kotlin Multiplatform target
// without dragging in the Android plugin.
//
// NOT PUBLISHED YET. `laddro-android` consumes it from source until we decide
// where Kotlin artifacts live (GitHub Packages alongside the npm package is the
// obvious candidate, matching the tag-push publish flow the TS package uses).

plugins {
    kotlin("jvm") version "2.1.0"
    kotlin("plugin.serialization") version "2.1.0"
}

// Tracks the TS package version (ts/package.json) so all three generated
// surfaces of one spec revision carry the same number.
group = "com.laddro"
version = "0.14.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
}

kotlin {
    jvmToolchain(17)
}
