// Package resume provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package resume

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CertificationsSectionType.
const (
	Certifications CertificationsSectionType = "certifications"
)

// Valid indicates whether the value is a known member of the CertificationsSectionType enum.
func (e CertificationsSectionType) Valid() bool {
	switch e {
	case Certifications:
		return true
	default:
		return false
	}
}

// Defines values for CustomSectionType.
const (
	Custom CustomSectionType = "custom"
)

// Valid indicates whether the value is a known member of the CustomSectionType enum.
func (e CustomSectionType) Valid() bool {
	switch e {
	case Custom:
		return true
	default:
		return false
	}
}

// Defines values for EducationSectionType.
const (
	Education EducationSectionType = "education"
)

// Valid indicates whether the value is a known member of the EducationSectionType enum.
func (e EducationSectionType) Valid() bool {
	switch e {
	case Education:
		return true
	default:
		return false
	}
}

// Defines values for EmploymentSectionType.
const (
	Employment EmploymentSectionType = "employment"
)

// Valid indicates whether the value is a known member of the EmploymentSectionType enum.
func (e EmploymentSectionType) Valid() bool {
	switch e {
	case Employment:
		return true
	default:
		return false
	}
}

// Defines values for ExtraCurricularActivitiesSectionType.
const (
	ExtraCurricularActivities ExtraCurricularActivitiesSectionType = "extraCurricularActivities"
)

// Valid indicates whether the value is a known member of the ExtraCurricularActivitiesSectionType enum.
func (e ExtraCurricularActivitiesSectionType) Valid() bool {
	switch e {
	case ExtraCurricularActivities:
		return true
	default:
		return false
	}
}

// Defines values for LanguagesSectionType.
const (
	Languages LanguagesSectionType = "languages"
)

// Valid indicates whether the value is a known member of the LanguagesSectionType enum.
func (e LanguagesSectionType) Valid() bool {
	switch e {
	case Languages:
		return true
	default:
		return false
	}
}

// Defines values for ProjectsSectionType.
const (
	Projects ProjectsSectionType = "projects"
)

// Valid indicates whether the value is a known member of the ProjectsSectionType enum.
func (e ProjectsSectionType) Valid() bool {
	switch e {
	case Projects:
		return true
	default:
		return false
	}
}

// Defines values for ReferencesSectionType.
const (
	References ReferencesSectionType = "references"
)

// Valid indicates whether the value is a known member of the ReferencesSectionType enum.
func (e ReferencesSectionType) Valid() bool {
	switch e {
	case References:
		return true
	default:
		return false
	}
}

// Defines values for ResumeGuidedFlowStatus.
const (
	Completed  ResumeGuidedFlowStatus = "completed"
	InProgress ResumeGuidedFlowStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the ResumeGuidedFlowStatus enum.
func (e ResumeGuidedFlowStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case InProgress:
		return true
	default:
		return false
	}
}

// Defines values for ResumeLocale.
const (
	Cs ResumeLocale = "cs"
	Da ResumeLocale = "da"
	De ResumeLocale = "de"
	En ResumeLocale = "en"
	Es ResumeLocale = "es"
	Et ResumeLocale = "et"
	Fi ResumeLocale = "fi"
	Fr ResumeLocale = "fr"
	Hu ResumeLocale = "hu"
	Is ResumeLocale = "is"
	It ResumeLocale = "it"
	Lt ResumeLocale = "lt"
	Lv ResumeLocale = "lv"
	Nl ResumeLocale = "nl"
	No ResumeLocale = "no"
	Pl ResumeLocale = "pl"
	Pt ResumeLocale = "pt"
	Ro ResumeLocale = "ro"
	Sk ResumeLocale = "sk"
	Sv ResumeLocale = "sv"
	Uk ResumeLocale = "uk"
)

// Valid indicates whether the value is a known member of the ResumeLocale enum.
func (e ResumeLocale) Valid() bool {
	switch e {
	case Cs:
		return true
	case Da:
		return true
	case De:
		return true
	case En:
		return true
	case Es:
		return true
	case Et:
		return true
	case Fi:
		return true
	case Fr:
		return true
	case Hu:
		return true
	case Is:
		return true
	case It:
		return true
	case Lt:
		return true
	case Lv:
		return true
	case Nl:
		return true
	case No:
		return true
	case Pl:
		return true
	case Pt:
		return true
	case Ro:
		return true
	case Sk:
		return true
	case Sv:
		return true
	case Uk:
		return true
	default:
		return false
	}
}

// Defines values for SkillsSectionType.
const (
	Skills SkillsSectionType = "skills"
)

// Valid indicates whether the value is a known member of the SkillsSectionType enum.
func (e SkillsSectionType) Valid() bool {
	switch e {
	case Skills:
		return true
	default:
		return false
	}
}

// Defines values for StylingPageNumbering.
const (
	Fraction StylingPageNumbering = "fraction"
	None     StylingPageNumbering = "none"
	Page     StylingPageNumbering = "page"
	Simple   StylingPageNumbering = "simple"
)

// Valid indicates whether the value is a known member of the StylingPageNumbering enum.
func (e StylingPageNumbering) Valid() bool {
	switch e {
	case Fraction:
		return true
	case None:
		return true
	case Page:
		return true
	case Simple:
		return true
	default:
		return false
	}
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	Activity string `json:"activity"`
	Current  *bool  `json:"current,omitempty"`

	// Description HTML allowed.
	Description *string `json:"description,omitempty"`

	// EndDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	EndDate *MonthDate `json:"endDate,omitempty"`

	// StartDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	StartDate *MonthDate `json:"startDate,omitempty"`
}

// CertificationItem defines model for CertificationItem.
type CertificationItem struct {
	Certification string `json:"certification"`

	// Description HTML allowed.
	Description *string `json:"description,omitempty"`

	// EndDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	EndDate     *MonthDate `json:"endDate,omitempty"`
	Institution *string    `json:"institution,omitempty"`

	// StartDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	StartDate *MonthDate `json:"startDate,omitempty"`
}

// CertificationsSection defines model for CertificationsSection.
type CertificationsSection struct {
	Items []CertificationItem       `json:"items"`
	Title *string                   `json:"title,omitempty"`
	Type  CertificationsSectionType `json:"type"`
}

// CertificationsSectionType defines model for CertificationsSection.Type.
type CertificationsSectionType string

// CustomSection defines model for CustomSection.
type CustomSection struct {
	// Id Stable developer-supplied slug, used as customSectionId in storage.
	Id    string `json:"id"`
	Items []struct {
		Fields *map[string]CustomSection_Items_Fields_AdditionalProperties `json:"fields,omitempty"`
	} `json:"items"`
	Title string            `json:"title"`
	Type  CustomSectionType `json:"type"`
}

// CustomSectionItemsFields0 defines model for CustomSection.Items.Fields.0.
type CustomSectionItemsFields0 = string

// CustomSectionItemsFields1 defines model for CustomSection.Items.Fields.1.
type CustomSectionItemsFields1 = float32

// CustomSectionItemsFields2 defines model for CustomSection.Items.Fields.2.
type CustomSectionItemsFields2 = bool

// CustomSection_Items_Fields_AdditionalProperties defines model for CustomSection.Items.Fields.AdditionalProperties.
type CustomSection_Items_Fields_AdditionalProperties struct {
	union json.RawMessage
}

// CustomSectionType defines model for CustomSection.Type.
type CustomSectionType string

// EducationItem defines model for EducationItem.
type EducationItem struct {
	City    *string `json:"city,omitempty"`
	Current *bool   `json:"current,omitempty"`
	Degree  *string `json:"degree,omitempty"`

	// Description HTML allowed.
	Description *string `json:"description,omitempty"`

	// EndDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	EndDate     *MonthDate `json:"endDate,omitempty"`
	Institution string     `json:"institution"`
	Major       *string    `json:"major,omitempty"`

	// StartDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	StartDate *MonthDate `json:"startDate,omitempty"`
}

// EducationSection defines model for EducationSection.
type EducationSection struct {
	Items []EducationItem      `json:"items"`
	Title *string              `json:"title,omitempty"`
	Type  EducationSectionType `json:"type"`
}

// EducationSectionType defines model for EducationSection.Type.
type EducationSectionType string

// EmploymentItem defines model for EmploymentItem.
type EmploymentItem struct {
	City    *string `json:"city,omitempty"`
	Company string  `json:"company"`
	Current *bool   `json:"current,omitempty"`

	// Description HTML allowed (paragraphs and lists).
	Description *string `json:"description,omitempty"`

	// EndDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	EndDate  *MonthDate `json:"endDate,omitempty"`
	Position string     `json:"position"`

	// StartDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	StartDate *MonthDate `json:"startDate,omitempty"`
}

// EmploymentSection defines model for EmploymentSection.
type EmploymentSection struct {
	Items []EmploymentItem `json:"items"`

	// Title Optional title override; falls back to localized default.
	Title *string               `json:"title,omitempty"`
	Type  EmploymentSectionType `json:"type"`
}

// EmploymentSectionType defines model for EmploymentSection.Type.
type EmploymentSectionType string

// ExtraCurricularActivitiesSection defines model for ExtraCurricularActivitiesSection.
type ExtraCurricularActivitiesSection struct {
	Items []ActivityItem                       `json:"items"`
	Title *string                              `json:"title,omitempty"`
	Type  ExtraCurricularActivitiesSectionType `json:"type"`
}

// ExtraCurricularActivitiesSectionType defines model for ExtraCurricularActivitiesSection.Type.
type ExtraCurricularActivitiesSectionType string

// LanguageItem defines model for LanguageItem.
type LanguageItem struct {
	Language string `json:"language"`

	// Level Free text level e.g. Native, C1, B2, Conversational.
	Level *string `json:"level,omitempty"`
}

// LanguagesSection defines model for LanguagesSection.
type LanguagesSection struct {
	Items []LanguageItem       `json:"items"`
	Title *string              `json:"title,omitempty"`
	Type  LanguagesSectionType `json:"type"`
}

// LanguagesSectionType defines model for LanguagesSection.Type.
type LanguagesSectionType string

// MonthDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
type MonthDate = string

// PersonalSection defines model for PersonalSection.
type PersonalSection struct {
	City      *string              `json:"city,omitempty"`
	Country   *string              `json:"country,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName *string              `json:"firstName,omitempty"`
	LastName  *string              `json:"lastName,omitempty"`
	Linkedin  *string              `json:"linkedin,omitempty"`

	// Links Optional user-supplied label+url pairs. Render as a separate cluster attached
	// to the contact area (single-column templates: second-line strip below contact
	// dots; sidebar templates: vertical block below the contact block). The fixed
	// website/linkedin fields above keep their own slots in the contact dots row.
	Links *[]struct {
		Label string `json:"label"`
		Url   string `json:"url"`
	} `json:"links,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Role    *string `json:"role,omitempty"`
	Website *string `json:"website,omitempty"`
}

// ProjectItem defines model for ProjectItem.
type ProjectItem struct {
	Current *bool `json:"current,omitempty"`

	// Description HTML allowed.
	Description *string `json:"description,omitempty"`

	// EndDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	EndDate *MonthDate `json:"endDate,omitempty"`

	// StartDate Month precision (YYYY-MM). Use null endDate + current=true for ongoing entries.
	StartDate *MonthDate `json:"startDate,omitempty"`
	Title     string     `json:"title"`

	// Url Optional link to deployed project or repository.
	Url *string `json:"url,omitempty"`
}

// ProjectsSection defines model for ProjectsSection.
type ProjectsSection struct {
	Items []ProjectItem       `json:"items"`
	Title *string             `json:"title,omitempty"`
	Type  ProjectsSectionType `json:"type"`
}

// ProjectsSectionType defines model for ProjectsSection.Type.
type ProjectsSectionType string

// ReferenceItem defines model for ReferenceItem.
type ReferenceItem struct {
	Company  *string              `json:"company,omitempty"`
	Email    *openapi_types.Email `json:"email,omitempty"`
	Name     string               `json:"name"`
	Phone    *string              `json:"phone,omitempty"`
	Position *string              `json:"position,omitempty"`
}

// ReferencesSection defines model for ReferencesSection.
type ReferencesSection struct {
	Items []ReferenceItem       `json:"items"`
	Title *string               `json:"title,omitempty"`
	Type  ReferencesSectionType `json:"type"`
}

// ReferencesSectionType defines model for ReferencesSection.Type.
type ReferencesSectionType string

// ReorderableSection defines model for ReorderableSection.
type ReorderableSection struct {
	union json.RawMessage
}

// Resume defines model for Resume.
type Resume struct {
	Completeness     *int                    `json:"completeness,omitempty"`
	CreatedAt        *time.Time              `json:"createdAt,omitempty"`
	GuidedFlowStatus *ResumeGuidedFlowStatus `json:"guidedFlowStatus,omitempty"`
	Id               *openapi_types.UUID     `json:"id,omitempty"`
	IsDefault        *bool                   `json:"isDefault,omitempty"`
	Locale           ResumeLocale            `json:"locale"`
	Personal         PersonalSection         `json:"personal"`

	// Sections Reorderable sections. Array position IS the display order — no
	// per-section `order` field. `personal` and `summary` are top-level
	// and not part of this array.
	Sections *[]ReorderableSection `json:"sections,omitempty"`

	// Styling Resume visual settings. All fields optional — the template's default
	// applies when omitted. Backend persists this as part of the encrypted
	// resume content.
	Styling *Styling       `json:"styling,omitempty"`
	Summary SummarySection `json:"summary"`

	// TemplateId Slug from the template catalog. Defaults to `emerald` when
	// omitted. The read path always returns a resolved templateId.
	TemplateId *string    `json:"templateId,omitempty"`
	Title      string     `json:"title"`
	UpdatedAt  *time.Time `json:"updatedAt,omitempty"`
}

// ResumeGuidedFlowStatus defines model for Resume.GuidedFlowStatus.
type ResumeGuidedFlowStatus string

// ResumeLocale defines model for Resume.Locale.
type ResumeLocale string

// SkillItem defines model for SkillItem.
type SkillItem struct {
	// Level Free-text proficiency e.g. Expert, Advanced, Intermediate, Beginner,
	// or a custom value. Optional — templates render gracefully when omitted.
	Level *string `json:"level,omitempty"`
	Skill string  `json:"skill"`
}

// SkillsSection defines model for SkillsSection.
type SkillsSection struct {
	Items []SkillItem       `json:"items"`
	Title *string           `json:"title,omitempty"`
	Type  SkillsSectionType `json:"type"`
}

// SkillsSectionType defines model for SkillsSection.Type.
type SkillsSectionType string

// Styling Resume visual settings. All fields optional — the template's default
// applies when omitted. Backend persists this as part of the encrypted
// resume content.
type Styling struct {
	// Color DEPRECATED as an input, still written for backwards compatibility.
	//
	// A single accent hex. Readers MUST prefer `colors` when present and
	// fall back to this only for documents saved before `colors` existed.
	// Writers should emit both, with `color` mirroring
	// `colors.backgroundPartColor`.
	//
	// On its own this cannot express a palette: it carries no
	// `backgroundColor`, `text` or `textMuted`, and readers historically
	// applied it to `backgroundPartColor` AND `underlineColor` at once,
	// so any palette whose divider differs from its accent came back
	// wrong. Keep writing it so older clients still get an accent; keep
	// reading it so older documents still resolve.
	Color *string `json:"color,omitempty"`

	// Colors A complete template colour palette — the five slots every template
	// renders. This is one row of a template's `availableColors` in the
	// renderer catalog, stored verbatim so the choice round-trips exactly.
	//
	// All five are REQUIRED when the object is present. A partial palette is
	// what the single-hex `Styling.color` already is, and mixing a partial
	// palette with template defaults is what made saved colours unreadable:
	// the reader could not tell an intentional slot from an omitted one.
	// Present means complete; omit the whole object to accept the
	// template's default palette.
	//
	// Slot meanings, as the templates use them:
	//   backgroundColor      page fill, or the sidebar fill on two-column layouts
	//   backgroundPartColor  accent panels and filled blocks
	//   underlineColor       section dividers and rules
	//   text                 body text
	//   textMuted            secondary text (dates, locations, meta)
	Colors *TemplateColors `json:"colors,omitempty"`

	// Font Font family override. Falls back to the template's default.
	Font *string `json:"font,omitempty"`

	// FontSize Body font size in points.
	FontSize *int `json:"fontSize,omitempty"`

	// LineHeight Body line-height multiplier (e.g. 1.2, 1.4).
	LineHeight *float32 `json:"lineHeight,omitempty"`

	// Margin Page margin in points.
	Margin *float32 `json:"margin,omitempty"`

	// PageNumbering Pagination style. `none` hides numbers; `simple` shows "1"; `fraction`
	// shows "1/3"; `page` shows "Page 1".
	PageNumbering *StylingPageNumbering `json:"pageNumbering,omitempty"`

	// Photo Profile photo URL. Templates that support photos render it; others ignore.
	Photo *string `json:"photo,omitempty"`

	// PhotoSize Photo size in points (square).
	PhotoSize *float32 `json:"photoSize,omitempty"`

	// ShowProfileImage Explicit on/off for the photo. When omitted, falls back to the
	// template's default (templates declare supportsProfileImage).
	ShowProfileImage *bool `json:"showProfileImage,omitempty"`
}

// StylingPageNumbering Pagination style. `none` hides numbers; `simple` shows "1"; `fraction`
// shows "1/3"; `page` shows "Page 1".
type StylingPageNumbering string

// SummarySection defines model for SummarySection.
type SummarySection struct {
	// Value Professional summary. HTML allowed (e.g. <p>, <strong>, <em>, <ul>, <li>).
	// Renderer parses inline tags.
	Value *string `json:"value,omitempty"`
}

// TemplateColors A complete template colour palette — the five slots every template
// renders. This is one row of a template's `availableColors` in the
// renderer catalog, stored verbatim so the choice round-trips exactly.
//
// All five are REQUIRED when the object is present. A partial palette is
// what the single-hex `Styling.color` already is, and mixing a partial
// palette with template defaults is what made saved colours unreadable:
// the reader could not tell an intentional slot from an omitted one.
// Present means complete; omit the whole object to accept the
// template's default palette.
//
// Slot meanings, as the templates use them:
//
//	backgroundColor      page fill, or the sidebar fill on two-column layouts
//	backgroundPartColor  accent panels and filled blocks
//	underlineColor       section dividers and rules
//	text                 body text
//	textMuted            secondary text (dates, locations, meta)
type TemplateColors struct {
	BackgroundColor     string `json:"backgroundColor"`
	BackgroundPartColor string `json:"backgroundPartColor"`
	Text                string `json:"text"`
	TextMuted           string `json:"textMuted"`
	UnderlineColor      string `json:"underlineColor"`
}

// AsCustomSectionItemsFields0 returns the union data inside the CustomSection_Items_Fields_AdditionalProperties as a CustomSectionItemsFields0
func (t CustomSection_Items_Fields_AdditionalProperties) AsCustomSectionItemsFields0() (CustomSectionItemsFields0, error) {
	var body CustomSectionItemsFields0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCustomSectionItemsFields0 overwrites any union data inside the CustomSection_Items_Fields_AdditionalProperties as the provided CustomSectionItemsFields0
func (t *CustomSection_Items_Fields_AdditionalProperties) FromCustomSectionItemsFields0(v CustomSectionItemsFields0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCustomSectionItemsFields0 performs a merge with any union data inside the CustomSection_Items_Fields_AdditionalProperties, using the provided CustomSectionItemsFields0
func (t *CustomSection_Items_Fields_AdditionalProperties) MergeCustomSectionItemsFields0(v CustomSectionItemsFields0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCustomSectionItemsFields1 returns the union data inside the CustomSection_Items_Fields_AdditionalProperties as a CustomSectionItemsFields1
func (t CustomSection_Items_Fields_AdditionalProperties) AsCustomSectionItemsFields1() (CustomSectionItemsFields1, error) {
	var body CustomSectionItemsFields1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCustomSectionItemsFields1 overwrites any union data inside the CustomSection_Items_Fields_AdditionalProperties as the provided CustomSectionItemsFields1
func (t *CustomSection_Items_Fields_AdditionalProperties) FromCustomSectionItemsFields1(v CustomSectionItemsFields1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCustomSectionItemsFields1 performs a merge with any union data inside the CustomSection_Items_Fields_AdditionalProperties, using the provided CustomSectionItemsFields1
func (t *CustomSection_Items_Fields_AdditionalProperties) MergeCustomSectionItemsFields1(v CustomSectionItemsFields1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCustomSectionItemsFields2 returns the union data inside the CustomSection_Items_Fields_AdditionalProperties as a CustomSectionItemsFields2
func (t CustomSection_Items_Fields_AdditionalProperties) AsCustomSectionItemsFields2() (CustomSectionItemsFields2, error) {
	var body CustomSectionItemsFields2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCustomSectionItemsFields2 overwrites any union data inside the CustomSection_Items_Fields_AdditionalProperties as the provided CustomSectionItemsFields2
func (t *CustomSection_Items_Fields_AdditionalProperties) FromCustomSectionItemsFields2(v CustomSectionItemsFields2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCustomSectionItemsFields2 performs a merge with any union data inside the CustomSection_Items_Fields_AdditionalProperties, using the provided CustomSectionItemsFields2
func (t *CustomSection_Items_Fields_AdditionalProperties) MergeCustomSectionItemsFields2(v CustomSectionItemsFields2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CustomSection_Items_Fields_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CustomSection_Items_Fields_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmploymentSection returns the union data inside the ReorderableSection as a EmploymentSection
func (t ReorderableSection) AsEmploymentSection() (EmploymentSection, error) {
	var body EmploymentSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmploymentSection overwrites any union data inside the ReorderableSection as the provided EmploymentSection
func (t *ReorderableSection) FromEmploymentSection(v EmploymentSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"employment"}`))
	t.union = b
	return err
}

// MergeEmploymentSection performs a merge with any union data inside the ReorderableSection, using the provided EmploymentSection
func (t *ReorderableSection) MergeEmploymentSection(v EmploymentSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"employment"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEducationSection returns the union data inside the ReorderableSection as a EducationSection
func (t ReorderableSection) AsEducationSection() (EducationSection, error) {
	var body EducationSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEducationSection overwrites any union data inside the ReorderableSection as the provided EducationSection
func (t *ReorderableSection) FromEducationSection(v EducationSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"education"}`))
	t.union = b
	return err
}

// MergeEducationSection performs a merge with any union data inside the ReorderableSection, using the provided EducationSection
func (t *ReorderableSection) MergeEducationSection(v EducationSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"education"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSkillsSection returns the union data inside the ReorderableSection as a SkillsSection
func (t ReorderableSection) AsSkillsSection() (SkillsSection, error) {
	var body SkillsSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSkillsSection overwrites any union data inside the ReorderableSection as the provided SkillsSection
func (t *ReorderableSection) FromSkillsSection(v SkillsSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"skills"}`))
	t.union = b
	return err
}

// MergeSkillsSection performs a merge with any union data inside the ReorderableSection, using the provided SkillsSection
func (t *ReorderableSection) MergeSkillsSection(v SkillsSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"skills"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLanguagesSection returns the union data inside the ReorderableSection as a LanguagesSection
func (t ReorderableSection) AsLanguagesSection() (LanguagesSection, error) {
	var body LanguagesSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLanguagesSection overwrites any union data inside the ReorderableSection as the provided LanguagesSection
func (t *ReorderableSection) FromLanguagesSection(v LanguagesSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"languages"}`))
	t.union = b
	return err
}

// MergeLanguagesSection performs a merge with any union data inside the ReorderableSection, using the provided LanguagesSection
func (t *ReorderableSection) MergeLanguagesSection(v LanguagesSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"languages"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCertificationsSection returns the union data inside the ReorderableSection as a CertificationsSection
func (t ReorderableSection) AsCertificationsSection() (CertificationsSection, error) {
	var body CertificationsSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCertificationsSection overwrites any union data inside the ReorderableSection as the provided CertificationsSection
func (t *ReorderableSection) FromCertificationsSection(v CertificationsSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"certifications"}`))
	t.union = b
	return err
}

// MergeCertificationsSection performs a merge with any union data inside the ReorderableSection, using the provided CertificationsSection
func (t *ReorderableSection) MergeCertificationsSection(v CertificationsSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"certifications"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProjectsSection returns the union data inside the ReorderableSection as a ProjectsSection
func (t ReorderableSection) AsProjectsSection() (ProjectsSection, error) {
	var body ProjectsSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProjectsSection overwrites any union data inside the ReorderableSection as the provided ProjectsSection
func (t *ReorderableSection) FromProjectsSection(v ProjectsSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"projects"}`))
	t.union = b
	return err
}

// MergeProjectsSection performs a merge with any union data inside the ReorderableSection, using the provided ProjectsSection
func (t *ReorderableSection) MergeProjectsSection(v ProjectsSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"projects"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReferencesSection returns the union data inside the ReorderableSection as a ReferencesSection
func (t ReorderableSection) AsReferencesSection() (ReferencesSection, error) {
	var body ReferencesSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReferencesSection overwrites any union data inside the ReorderableSection as the provided ReferencesSection
func (t *ReorderableSection) FromReferencesSection(v ReferencesSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"references"}`))
	t.union = b
	return err
}

// MergeReferencesSection performs a merge with any union data inside the ReorderableSection, using the provided ReferencesSection
func (t *ReorderableSection) MergeReferencesSection(v ReferencesSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"references"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExtraCurricularActivitiesSection returns the union data inside the ReorderableSection as a ExtraCurricularActivitiesSection
func (t ReorderableSection) AsExtraCurricularActivitiesSection() (ExtraCurricularActivitiesSection, error) {
	var body ExtraCurricularActivitiesSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExtraCurricularActivitiesSection overwrites any union data inside the ReorderableSection as the provided ExtraCurricularActivitiesSection
func (t *ReorderableSection) FromExtraCurricularActivitiesSection(v ExtraCurricularActivitiesSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"extraCurricularActivities"}`))
	t.union = b
	return err
}

// MergeExtraCurricularActivitiesSection performs a merge with any union data inside the ReorderableSection, using the provided ExtraCurricularActivitiesSection
func (t *ReorderableSection) MergeExtraCurricularActivitiesSection(v ExtraCurricularActivitiesSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"extraCurricularActivities"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCustomSection returns the union data inside the ReorderableSection as a CustomSection
func (t ReorderableSection) AsCustomSection() (CustomSection, error) {
	var body CustomSection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCustomSection overwrites any union data inside the ReorderableSection as the provided CustomSection
func (t *ReorderableSection) FromCustomSection(v CustomSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"custom"}`))
	t.union = b
	return err
}

// MergeCustomSection performs a merge with any union data inside the ReorderableSection, using the provided CustomSection
func (t *ReorderableSection) MergeCustomSection(v CustomSection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"custom"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ReorderableSection) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ReorderableSection) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "certifications":
		return t.AsCertificationsSection()
	case "custom":
		return t.AsCustomSection()
	case "education":
		return t.AsEducationSection()
	case "employment":
		return t.AsEmploymentSection()
	case "extraCurricularActivities":
		return t.AsExtraCurricularActivitiesSection()
	case "languages":
		return t.AsLanguagesSection()
	case "projects":
		return t.AsProjectsSection()
	case "references":
		return t.AsReferencesSection()
	case "skills":
		return t.AsSkillsSection()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ReorderableSection) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ReorderableSection) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
