// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: skills/skills.v1.yaml -> components.schemas.ResumeSkillSuggestions

package com.laddro.schemas.skills

import kotlinx.serialization.Serializable

/**
 * Persisted per-resume state. Inlined into `getResumeById` so the
 * frontend can render the first 5 chips with zero API calls on every
 * return visit. Updated whenever ai-core returns a fresh batch.
 */
@Serializable
data class ResumeSkillSuggestions(
    /**
     * The bucket the classifier put this resume into. Cached so we never
     * re-run the classifier just to refill a chip. If the resume changes
     * shape enough that the classifier would route it elsewhere, we
     * recompute on the next first-paint suggest.
     */
    val bucketId: String,
    /**
     * The skill names currently visible on chips (length <= 5).
     */
    val displayed: List<String>,
    /**
     * Cumulative blocklist of everything ever shown on a chip for this
     * resume, regardless of whether the user picked or skipped. Keeps
     * us from re-suggesting a skill the user has already seen.
     */
    val excluded: List<String>,
    val updatedAt: String,
)
