// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: skills/skills.v1.yaml -> components.schemas.SkillsSuggestRequest

package com.laddro.schemas.skills

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * Request body for `POST /v1/skills/suggest` on laddro-ai-core (and the
 * matching `POST /api/skills/suggest` on laddro-backend, which forwards
 * the same envelope after persisting the pick side-effect).
 */
@Serializable
data class SkillsSuggestRequest(
    /**
     * The candidate's V1 Resume. The classifier reads `personal.role`,
     * recent `employments[*].position`, and the latest employment
     * description to build the bucket id and profile vector. The
     * employer domain (when present) seeds the industry hint.
     */
    val resume: JsonObject,
    /**
     * Optional. When the user is in a tailor flow we pass the JD so the
     * profile vector skews toward the role they're targeting rather than
     * their resume baseline. Omitted on the standalone build-resume page.
     */
    val jobDescription: String? = null,
    /**
     * Drives which locale-labelled skill names ai-core returns AND which
     * slice of `skill_selections` (bucket_id, skill, locale) drives the
     * crowdsource boost. No English fallback labels — if a skill has no
     * label in this locale we surface the next best skill that does.
     */
    val locale: SkillsSuggestRequestLocale,
    /**
     * Skills already on the resume. Filtered out of the candidate pool
     * and also concatenated into the profile vector so the matcher
     * reads the direction the user is committing to.
     */
    val existingSkills: List<String>,
    /**
     * Skills currently visible on chips but not picked. ai-core never
     * returns these even if they outrank everything else — protects the
     * "remove one chip, refill one chip, other four stay put" UX.
     */
    val exclude: List<String>,
    /**
     * How many fresh skills to return. Initial first-paint suggest is 5;
     * chip-refill calls send 1.
     */
    val limit: Int,
    /**
     * Set by laddro-backend when this request was triggered by a user
     * tapping a chip. Backend uses it to increment
     * `skill_selections.(bucket_id, pickedSkill, locale).count` before
     * forwarding to ai-core. ai-core ignores this field — the picked
     * skill will already be reflected in `existingSkills`.
     */
    val pickedSkill: String? = null,
    /**
     * Cached bucket id from a previous response. When present, ai-core
     * skips classification and trusts this assignment (the resume hasn't
     * shifted shape enough to re-route). When omitted (first paint or
     * forced reclassify), ai-core classifies and returns the bucket it
     * picked in `bucketId` of the response.
     */
    val bucketId: String? = null,
    /**
     * Per-skill pick counts derived from `skill_selections` for this
     * `(bucketId, locale)` slice — typically the top ~100 most-picked
     * skills. ai-core adds `0.15 * log(1 + count)` to the cosine score
     * of any candidate whose name matches a key here. The crowdsource
     * counts live on the backend; ai-core is stateless wrt this table
     * and receives the snapshot per request. Omitted on the very first
     * call when no bucketId is cached yet (boost is empty in that case).
     */
    val crowdsourceBoost: JsonObject? = null,
)

/**
 * Drives which locale-labelled skill names ai-core returns AND which
 * slice of `skill_selections` (bucket_id, skill, locale) drives the
 * crowdsource boost. No English fallback labels — if a skill has no
 * label in this locale we surface the next best skill that does.
 */
@Serializable
enum class SkillsSuggestRequestLocale {
    @SerialName("en") EN,
    @SerialName("de") DE,
    @SerialName("es") ES,
    @SerialName("fr") FR,
    @SerialName("it") IT,
    @SerialName("nl") NL,
    @SerialName("pl") PL,
    @SerialName("pt") PT,
    @SerialName("is") IS,
    @SerialName("fi") FI,
    @SerialName("sv") SV,
    @SerialName("no") NO,
    @SerialName("da") DA,
    @SerialName("et") ET,
    @SerialName("ro") RO,
    @SerialName("cs") CS,
    @SerialName("sk") SK,
    @SerialName("hu") HU,
    @SerialName("lt") LT,
    @SerialName("lv") LV,
    @SerialName("uk") UK,
}
