// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: skills/skills.v1.yaml -> components.schemas.SkillsGenerationUsage

package com.laddro.schemas.skills

import kotlinx.serialization.Serializable

/**
 * Per-call usage block. On the embedding path token counts are zero and
 * `model` is the sentence-transformer id (e.g. `sentence-transformers/
 * paraphrase-multilingual-mpnet-base-v2`). On the LLM-fallback path
 * token counts reflect the small prompt and `model` is the LLM that
 * produced the completion.
 */
@Serializable
data class SkillsGenerationUsage(
    val promptTokens: Int? = 0,
    val outputTokens: Int? = 0,
    val model: String,
)
