// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: skills/skills.v1.yaml -> components.schemas.SkillsSuggestResponse

package com.laddro.schemas.skills

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Result of a `POST /v1/skills/suggest` call. Returns up to `limit`
 * skills, all of which are absent from `existingSkills` and `exclude`.
 */
@Serializable
data class SkillsSuggestResponse(
    val skills: List<SuggestedSkill>,
    /**
     * Bucket id ai-core used for this response — either the one the
     * caller passed in `request.bucketId` (verbatim) or the one ai-core
     * picked via embedding-match classification when the request omitted
     * it. Backend persists this on `resume_skill_suggestions.bucket_id`
     * so subsequent refill calls can scope the crowdsource fetch.
     */
    val bucketId: String,
    /**
     * Which path produced this batch. `embedding` = pure cosine match,
     * no crowdsource signal had any influence on the top results.
     * `embedding+crowdsource` = at least one returned skill was boosted
     * past a rival by `skill_selections` counts. `llm_fallback` = the
     * embedding pool didn't produce enough above-threshold candidates
     * and we called the LLM to complete the batch. Logged for telemetry,
     * not user-visible.
     */
    val source: SkillsSuggestResponseSource,
    val usage: SkillsGenerationUsage? = null,
)

/**
 * Which path produced this batch. `embedding` = pure cosine match,
 * no crowdsource signal had any influence on the top results.
 * `embedding+crowdsource` = at least one returned skill was boosted
 * past a rival by `skill_selections` counts. `llm_fallback` = the
 * embedding pool didn't produce enough above-threshold candidates
 * and we called the LLM to complete the batch. Logged for telemetry,
 * not user-visible.
 */
@Serializable
enum class SkillsSuggestResponseSource {
    @SerialName("embedding") EMBEDDING,
    @SerialName("embedding+crowdsource") EMBEDDING_CROWDSOURCE,
    @SerialName("llm_fallback") LLM_FALLBACK,
}
