// GENERATED by scripts/generate-kotlin.mjs. Do not edit by hand.
// Source: skills/skills.v1.yaml -> components.schemas.SuggestedSkill

package com.laddro.schemas.skills

import kotlinx.serialization.Serializable

@Serializable
data class SuggestedSkill(
    /**
     * Locale-labelled skill name. This is the literal string we put on
     * the chip and append to `resume.skills` if the user picks it.
     */
    val name: String,
)
